### ISSUE TITLE
CRM2015 missing bin directory expected by package.ps1

### ISSUE THREAD

**Issue by NightshadowZ** [WaelHamze/xrm-ci-framework#10]
The following command line in the package.ps1 script calls for DLLs under a \bin directory which doesn't seem to exist in the CRM2015 Folder.
Copy-Item ($scriptPath + "\Xrm.Framework.CI.PowerShell\bin\Release\microsoft.xrm.client.dll") $CIPowerShellDir -Force -Recurse
All 5 DLL copy-Item lines call for this folder which doesn't exist.  was it removed by accident?  Or has the script not been updated after an update?

**Comment by WaelHamze** [comment]
You need to build the solution in release mode before running this script.
