### ISSUE TITLE
Provision Sandbox Instance "InternalServerError"

### ISSUE THREAD

**Issue by mnecker** [WaelHamze/xrm-ci-framework#103]
Hey,

I'm using the framework with Visual Studio Team Services in our build process. I can't seem to get the provisioning of a sandbox instance working. It always returns the follwing error:

Operation returned an invalid status code 'InternalServerError'

If I switch the parameter "Type" from "Sandbox" to "Production" it works fine. There is also a sandbox license available in the target environment, if I provision a sandbox using the admin UI it works. I tried it with a production instance present in the tenant and without one. 

Any idea why I keep running in the error? Or is it not possible to provision a sandbox with this? I'm happy for any help/comments :)

Cheers,
Mats

**Comment by mnecker** [comment]
@WaelHamze thanks for your response. I ran the PowerShell script directly, but the result is the same. Also tested it in different environments but always the same error.

I opened a ticket with the Dynamics 365 support, hopefully they can locate the issue on their side.

**Comment by WaelHamze** [comment]
@mnecker thanks for the feedback. I will close the issue for now as there isn't any change I can do to the code. If MS come back with any feedback that can be fixed by code, please re-open the issue and I will make the necessary changes.

**Comment by mnecker** [comment]
@WaelHamze just a quick update: Didn't hear anything from MS but it is working again without me changing anything. So the error must have been on their side :)
