### ISSUE TITLE
The Extension is to large to upload into TFS

### ISSUE THREAD

**Issue by shaibarlev** [WaelHamze/xrm-ci-framework#104]
When trying to update the extension in TFS (2017.3) I'm getting this error :
The files being added total 23 MB which exceeds the maximum total size allowed to be uploaded (20 MB).

Is there a workaround ?

**Comment by eNeRGy164** [comment]
Maybe you can look into making a tools installer task: https://github.com/Microsoft/vsts-tasks/blob/master/docs/tools.md
That way your tasks can remain small.

**Comment by WaelHamze** [comment]
@eNeRGy164 thx for the suggestion, I was considering this as well after running out of unneeded DLLs I can remove.

So do you see this as another task you add in the beginning of your build/release definition that then will down the xRM CI Framework Cmdlets from Nuget which will be available for the remainder of the tasks to consume?

Was thinking if there is an easier way to use existing Nuget capabilities without making it too complex for consumers.

**Comment by WaelHamze** [comment]
@shaibarlev Do you have a previous version you can use in the meantime?

**Comment by shaibarlev** [comment]
Yes. I'm also checking for solutions from MS.

**Comment by eNeRGy164** [comment]
@WaelHamze I don't think adding a tools step as "too complex", it's what you also should add for other things you want to use like NuGet, .NET core, VSTest, node/npm, etc.
Maybe people are not yet used to it, but it is the way Microsoft is designing the build system for TFS/VSTS these days.
Using NuGet as a source is possible, but just doing a simple zip download is much easier to provide.

**Comment by WaelHamze** [comment]
@eNeRGy164 Agreed that this is the way forward. Where do you suggest the task downloads this zip from?

**Comment by eNeRGy164** [comment]
You might have versioned zips on something like azure blob storage, or on GitHub. But this might be tricky because I'm not sure you're allowed to distribute those dll's.
You could also download the official nuget packages, and unpack them this might be a bit harder (not sure) but would leave out any distribution license issues.

**Comment by Mehdi-najjar** [comment]
I have the same problem, I don't need all the tasks but only to download an extract a solution. is there a way to install only some tasks? 

Thanks

**Comment by WaelHamze** [comment]
@MehdiNaj you download the source and compile a cut down version of the extension if needed. I am working on a way to reduce the package by dynamically downloading dependencies at run time but this will require lots of testing so will not be out for a while

**Comment by FixRM** [comment]
@WaelHamze May be it's easier to divide tasks into separate extensions? For example: CI extension (pack/unpack) + DI extension (import/export) + Admin extension (backup/restore).

I believe most people don't use all these tasks. In my case admin tasks are not used as we have on-premise version.

**Comment by FixRM** [comment]
I looked through code and found that several tasks use their own copy of CRM CoreTools as well as xRMCIFramework. Why not to move them to root folder?

**Comment by pwalsh31** [comment]
For anyone stuck here dealing with the on-prem 20mb upload limit, it's easy enough just to either package the bits you need or hack the .vsix to remove the components you don't need right now (just edit the manifest to remove the bity you don't want and remove those bits from the tasks also).

**Comment by WaelHamze** [comment]
@eNeRGy164 @mattp65 @pwalsh31 @FixRM thank you for your suggestions...

I am happy to confirm that I will be introducing a tool installer in the next release (9.2.x), The extension size including all tasks has reduced from almost 25MB to under 10MB. All the task have been updated to version 10 to avoid breaking existing builds. Using this mechanism I am now able to add more tasks. @sagarhgaikwad thx for your help in refactoring the remaining tasks.

**Comment by WaelHamze** [comment]
Released to Marketplace: https://github.com/WaelHamze/dyn365-ce-vsts-tasks/releases/tag/v9.2.7
