### ISSUE TITLE
MSCRM Plugin Registration: Solutionname required

### ISSUE THREAD

**Issue by StefanKert** [WaelHamze/xrm-ci-framework#105]
Currently taking a look at the plugin registration build task. After taking a look at the code I figured out, that the Solutionname is only used if the Plugin is a Workflow Activity. If it is just an update there is no use for the solutionname. Maybe there is a reason that I am not seeing, but would it be possible to make this non required? I can make a PR for this, but I wanted to verify that I am not overlooking something :)

Oh and thanks for the awesome tasks! Really great work.

**Comment by WaelHamze** [comment]
@StefanKert thanks for the feedback. I take it you want the solution name parameter on the task to be optional?

**Comment by WaelHamze** [comment]
@StefanKert please confirm if this PR fixes your issue: https://github.com/WaelHamze/xrm-ci-framework/pull/106

@sagarhgaikwad thx for changing this

**Comment by StefanKert** [comment]
@WaelHamze Wow that was so fast, I couldn´t even respond :), but yes! Totally.  The main reason for this issue was to clarify if the solutionname is actually needed as required, to do a PR if it is not really needed. Thanks to @sagarhgaikwad for this really really fast change. Less work for me :P, but this will fix my issue. 

Thanks to both of you for the fast reaction and maybe I can contribute in another way :)
