### ISSUE TITLE
Any Task to Import CSV (data management) for configuration entities

### ISSUE THREAD

**Issue by Pathikr** [WaelHamze/xrm-ci-framework#107]
Hi Wael,

Do you have any PowerShell Script or task to import CSV files into Dynamics 365?

**Comment by WaelHamze** [comment]
@Pathikr you can create a package https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/create-packages-package-deployer

and deploy it using the Package Deployer Task
