### ISSUE TITLE
TFS Build Partially Succeeded

### ISSUE THREAD

**Issue by dwurth** [WaelHamze/xrm-ci-framework#112]
I'm using an older version of the XRM CI Framework for CRM 2015 and TFS 2015. My builds have mostly been working for a couple of years. I recently had a TFS build "partially succeed". The build is able to get the unmanaged solution packaged and imported to a test server. But when it exports and imports the managed solution to another server the import progress is 99.8355263157895% and the import result was "success". However, I'm not sure why it didn't get to 100%. TFS shows the following error:

Import Failed
At \xRMCIFramework\PowerShell\ImportSolution.ps1:78 char:9
throw "Import Failed"
CategoryInfo : OperationStopped: (Import Failed:String) [], RuntimeException
FullyQualifiedErrorId : Import Failed

**Comment by WaelHamze** [comment]
@dwurth The latest script for D365 doesn't have this issue, you could consider changing your script inline with this: https://github.com/WaelHamze/xrm-ci-framework/blob/master/CRM365/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell.Scripts/ImportSolution.ps1

or you could consider to remove the check in line 78 in your current script: https://github.com/WaelHamze/xrm-ci-framework/blob/master/CRM2015/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell/Scripts/ImportSolution.ps1

Sometimes CRM doesn't process all the components so the process doesn't reach 100.

I would suggest you take a look at the import log and then either adjust script or see why it is not reaching 100.

**Comment by dwurth** [comment]
@WaelHamze , I removed the ($importProgress -ne 100) and the import succeeded. Thank you.
