### ISSUE TITLE
Unable to Login to Dynamics CRM

### ISSUE THREAD

**Issue by dionysus33** [WaelHamze/xrm-ci-framework#113]
Hi all, I'm experiencing issues with VSTS and CRM 2016 ver 8.2.2. When I run the job on vsts it keeps getting the error unable to login to Dynamics CRM. I have tested my connection string using XRmSDKToolBox and it was successful.

My connection strings looks like this
AuthType=IFD;Url=https://CRMonPrem.XYZ.COM/CRMonPrem;HomeRealmUri=https://itafs.xyz.com/adfs/services/trust/mex/;Domain=XYZ; Username=XYZ\BigToes; Password=*****

Would appreciate some help from here. Thank you in advance.

**Comment by WaelHamze** [comment]
Make sure the agent that you are using for build/release has a line of sight (network connectivity) to your CRM environment.

**Comment by dionysus33** [comment]
@WaelHamze
