### ISSUE TITLE
Export Solution takes too long time and operation gets cancelled.

### ISSUE THREAD

**Issue by Sheringkapoting** [WaelHamze/xrm-ci-framework#114]
Sorry I'm new to CI in Visual studio online. I am currently struggling to get the MSCRM Export Solution build task working in my build definition partly. We are using Dynamics 365 and I am trying to Export an Unnamaged solution in my build task which takes too long time and then almost after running for 28 min the operation automatically gets cancelled. If I shorten the Crm Connection Timeout then it gives time out error.
If I try to Export the same solution using UI from CRM then it gets exported fine taking 4 - 5 min and is of around 5 mb in size.

My Task Configured:
![image](https://user-images.githubusercontent.com/13045584/40166709-db39fd18-59dc-11e8-96ac-48bd7fc4de31.png)

Error Log:
![image](https://user-images.githubusercontent.com/13045584/40166790-111f9e10-59dd-11e8-837b-e4d5b646bd74.png)

It may be obvious what I am getting wrong here but please help and thanks in advance.

**Comment by WaelHamze** [comment]
@Sheringkapoting this sound like a network connectivity/performance issue. I would suggest you login to the build agent (if not using hosted) and try to perform the same operation from UI.

**Comment by WaelHamze** [comment]
@Sheringkapoting I would execute the script from your machine: https://github.com/WaelHamze/xrm-ci-framework/blob/master/MSDYNV9/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell.Scripts/ImportSolution.ps1 and see what performance you get. If the above is ok, you could also temporarily install an agent on your machine.

**Comment by Sheringkapoting** [comment]
@WaelHamze  I didn't got you. Do you want me to try the Import solution and check if i get the same performance ?

**Comment by WaelHamze** [comment]
Yes try to import the solution from your desktop using the script I shared. You can download this from PowerShell Gallery: https://www.powershellgallery.com/packages/Xrm.Framework.CI.PowerShell.Cmdlets/9.0.0.17
