### ISSUE TITLE
import Solution, all plugin steps disabled after import

### ISSUE THREAD

**Issue by strwase** [WaelHamze/xrm-ci-framework#115]
When I use the Import Solution Step in my VSTS Release, after import of the solution in CRM, all the pluginsteps are Disabled.

Is there a way to avoid this behavior?

Preferably, the same state as in the original environment is used.

**Comment by WaelHamze** [comment]
@strwase you can try to tick the publish works parameter in the import task.

See this request for more information: https://msdn.microsoft.com/en-gb/library/microsoft.crm.sdk.messages.importsolutionrequest.aspx
