### ISSUE TITLE
web resource update 

### ISSUE THREAD

**Issue by sameer1995** [WaelHamze/xrm-ci-framework#116]
i wanted to know what are the steps for using the web resource update task in ms crm build tools.
If i give a regular expression with the whole file name also, its showing an error 0 web resources found matching file name. Please can someone guide me on this.

**Comment by WaelHamze** [comment]
@sameer1995  thx for reaching out

I normally have these in the extensions: *.html,*.htm,*.js,*.css,*.png,*.jpeg
Regular Expression is: $fileName

The web resource in file system would be: account_main.js
The web resources in CRM would have be called: ext_/Scripts/account_main.js

Try the above or share your specific scenario.

**Comment by sameer1995** [comment]
![web_resource](https://user-images.githubusercontent.com/17156682/40291153-b31d42ac-5ce0-11e8-9ea0-9b6ec225a932.png)
Please suggest how to implement the scenario.
i have a existing web resource named as webresource.js . i need to update this web resource with updateresource.js file. Please help me out with this scenario
Thanks In Advance

**Comment by sameer1995** [comment]
![webresource_update](https://user-images.githubusercontent.com/17156682/40293427-8457d53c-5cee-11e8-8fe8-8f49d2bade0d.png)

Please suggest how to implement the scenario.
i have a existing web resource named as webresource.js . i need to update this web resource with webresource.js(updated with few code ) file. Please help me out with this scenario
Thanks In Advance
