### ISSUE TITLE
Package Deployer Import Fails

### ISSUE THREAD

**Issue by pahansen** [WaelHamze/xrm-ci-framework#118]
When I integrate the Package Deployer task into a build process the build fails on step: "OverrideDataTimestamp Custom Setting"

The package contains a managed solution and a data file. If I use the Package Deployer tool and import the same package "manually" instead of integrating the step into the build process the package import succeeds. 

Any ideas what might cause this issue?

**Comment by WaelHamze** [comment]
which version of Dynamics are you using? Where is your agent running?

**Comment by pahansen** [comment]
Dynamics Version 9.0.2.191 and the agent is an online agent provided by VSTS

**Comment by CrmDev23** [comment]
Same issue here: Without the data import file it works on my side.

**Comment by pahansen** [comment]
@CrmDev23 can confirm that - without the data the import is successful

**Comment by WaelHamze** [comment]
I have seen this before I think. if you open data.xml, do you see timestamp tag like below?

<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" timestamp="20/01/2018 14:43:17">

If you remove the timestamp attribute it may work. This could be a bug with powershell API or compatibility with configuration migration tool.

**Comment by pahansen** [comment]
Works! Thanks a lot
