### ISSUE TITLE
Task to install additional language layer

### ISSUE THREAD

**Issue by pahansen** [WaelHamze/xrm-ci-framework#120]
Hey, thanks for the awesome work with this framework! We started using it a lot for our build processes. We are currently facing one challenge though:

We are developing our solutions in multiple languages (e.g. english + german). Currently, we are resetting a staging environment and import our solution (unmanaged) from git into that environment in the build process to check if the solution can still be installed. However, since german is not installed on the staging environment we are losing the german language layer. Is there a task that can enable an additional language? Our do you can think about a different solution on how to maintain our additional language layer?

Thanks in advance for any suggestions!

**Comment by WaelHamze** [comment]
@pahansen are you referring to these steps? https://docs.microsoft.com/en-us/dynamics365/customer-engagement/customize/enable-additional-languages

**Comment by majakubowski** [comment]
@pahansen @WaelHamze 
I have similar need.. 
I will try to add the appropriate command - I believe these request should be enough to accomplish this: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/customize-labels-support-multiple-languages

**Comment by majakubowski** [comment]
I added pull request with two new cmdlets: **Add-XrmLanguagePack** and **Get-XrmLanguagePacks..**
For **Add-XrmLanguagePack** **Language** parameter with language code is required. Also **Timeout** parameter with high value is recommended (eq. 10-15 mins - 600-900 secs.). It provision a new language pack if needed or does nothing if it's already provisioned.

**Comment by pahansen** [comment]
@majakubowski great - thank's a lot! Can't wait to see this being available as VSTS task
