### ISSUE TITLE
Version number extract from Build not handling multipe "_"

### ISSUE THREAD

**Issue by mattp65** [WaelHamze/xrm-ci-framework#123]
The script that extracts the Version number from the tail end of the BuildNumber value does not work properly when mutliple "_" are present in the BuildNumber (like Build_Process_1.2.3.4). I believe this is present in both the PackSolution & ExtractSolution tasks.

Current code:
```
if ($updateVersion)
{
    $versionNumber = $buildNumber.Substring($buildNumber.IndexOf("_") + 1)
}
```

Suggested code:
```
if ($updateVersion)
{
    $splits = $buildNumber.Split("_")
    $versionNumber = $splits[$splits.Count-1]
}
```

**Comment by WaelHamze** [comment]
Released 9.1.1
