### ISSUE TITLE
How to use the MSCRM Plugin Registration Task?

### ISSUE THREAD

**Issue by orangetoken** [WaelHamze/xrm-ci-framework#126]
We would like to use the task for all the WF steps we have. Those are bundled in a solution with separate folders for each WF step. Do we need a task per step or we can do it at once for the whole solution?

**Comment by WaelHamze** [comment]
You will need a json file and a task per assembly/project.

You can see sample here: https://github.com/WaelHamze/xrm-ci-framework/tree/master/Sample/Xrm.CI.Framework.Sample/Xrm.CI.Framework.Sample.WFActivities

More documentation on this to come...
