### ISSUE TITLE
Issue with Publish Customizations - Organization cannot be null or empty

### ISSUE THREAD

**Issue by JoanneNash09** [WaelHamze/xrm-ci-framework#129]
Hi,

I am also getting this error when using the Publish Customisations task:

image

The connection string i'm using is AuthType=Office365;Username=xxx.xxx@xxx.co.uk; Password=xxxx;Url=https://xxx.crm4.dynamics.com;

The version of D365 8.2.2.1862, is there a way to change the version within D365 Build Tools as it only has 9.* has the option? Could this be my problem?

**Comment by WaelHamze** [comment]
@JoanneNash09 The SDK should be backwards compatible for this operation including the connection string. This connection string should work: AuthType=Office365;Username=jsmith@contoso.onmicrosoft.com; Password=passcode;Url=https://contoso.crm.dynamics.com

If you want to be sure you can execute this Script from the Cmdlet line. This would also tell us whether is this something with VSTS agent or tooling. https://github.com/WaelHamze/xrm-ci-framework/blob/master/MSDYNV9/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell.Scripts/Ping.ps1
