### ISSUE TITLE
Failed to Connect to CRM 365 via XRM Toolkit

### ISSUE THREAD

**Issue by inmate060714** [WaelHamze/xrm-ci-framework#13]
**RESOLVED** 

Sharing the issue here per request WaelHamze via tweet as the issue was originally raised on codeplex, which is the repository for 2013, and our issue is related to CRM 365 Online. [Screen Cap](http://i.imgur.com/vHg2uaw.jpg) 

KhanPinewood wrote Mon at 3:24 AM

First of all thanks for sharing this really wonderful tool. Since our team has started using SDK 8.x ,i was trying to use your new 8.1 based XRM framework scripts . But i am continuosly getting this error even with Ping command 

Select-WhoAmI : Object reference not set to an instance of an object.
At C:\XXX\xRMCIFramework_8.0.17\Ping.ps1:26 char:18
... utingUser = Select-WhoAmI -ConnectionString $CrmConnectionString -Ver ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : NotSpecified: (:) [Select-WhoAmI], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException,Xrm.Framework.CI.PowerShell.Cmdlets.SelectXrmWhoAmICommand
Is there anything i am missing . I have tried different options but no change in output
.\Ping.ps1 "ServiceUri=https://XXXX.crm.dynamics.com; Username=XXXX; Password=XXX"
KhanPinewood wrote Mon at 10:54 PM

Able to fix it .Seems it was looking for OAuthType=Office365 parameter in my connection string
wrote Tue at 3:56 PM

josersm wrote Tue at 3:56 PM

@KhanPinewood, can you share a more full example? I'm running into the same issue.
KhanPinewood wrote Tue at 11:21 PM

My bad i made myself shared typo in the fix :( . For latest 8.1 dll solution provided by wael It should be 
"AuthType=Office365;ServiceUri=https://xxx.api.crm.dynamics.com; Username=xxxx@microsoft.com; Password=xxxx"
KhanPinewood wrote Tue at 11:43 PM

https://msdn.microsoft.com/en-in/library/mt608573.aspx
josersm wrote Today at 8:10 AM

thanks KhanPinewood, that worked for me for both ping and export!

**Comment by WaelHamze** [comment]
Thanks for sharing.
Here is the format of the connection string I use for CRM Online by the way : AuthType=Office365;Username=XXX@YYY.onmicrosoft.com; Password=ZZZ;Url=https://YYY.crm4.dynamics.com
