### ISSUE TITLE
Translations not reflecting 

### ISSUE THREAD

**Issue by sanjay1913** [WaelHamze/xrm-ci-framework#135]
Dear Wael,

When do the import from Import process , The translations are not reflecting on Target.
Are we missing any parameter during the import ?

Note : I have put the async call timeout parameter 3600 (1 Hr) is that because of it that it would reflect after 1 hour? Since solution import take more time during to kept it to max .

-AsyncWaitTimeout $AsyncWaitTimeout  >>>> 3600

Have commented code as well as were getting timeout when we use below code in import:-

	$solution = Get-XrmSolution -ConnectionString "$CrmConnectionString" -UniqueSolutionName $solutionInfo.UniqueName

Appreciate your input and suggestion.?

Thanks
Sanjay

**Comment by WaelHamze** [comment]
@sanjay1913 the timeout has nothing to do with the translations. There is no additional parameters for this. This post might help you: https://www.inogic.com/blog/2018/04/working-with-translation-for-managed-solution-in-dynamics-365/
