### ISSUE TITLE
MSCRM Ping Task - Unable to login after Multifactor authentication was enabled for Dynamics 365

### ISSUE THREAD

**Issue by karshikarr** [WaelHamze/xrm-ci-framework#136]
I am using below connectionstring for MSCRM ping task 

Connectionstring:
AuthType=Office365; Url=https://xdev.crm.contoso.com; UserName=username@xyzcloud.com; Password=password

Error:
Couldn't connect to CRM instance after 3 attempts: Unable to Login to Dynamics CRM

We started getting this error once Microsoft Multifactor authentication was enabled for CRM

Kindly help

**Comment by WaelHamze** [comment]
You should exclude any deployment accounts from multi-factor authentication.
