### ISSUE TITLE
Could not find file generated by MSCRM Export Solution

### ISSUE THREAD

**Issue by rakeshagarwalARRK** [WaelHamze/xrm-ci-framework#137]
My Build tool shows that file has been exported successfully to:
**UnManaged Solution Exported D:\a\1\s\POC_Solutions\Code BaseLine\CRM\Schedulars\XXXXXXXSafeSchedular\ENGINEERING_INSURANCE_1_0.zip**

but I can't find it. can you assist where I can find this .zip file?

Will it be in Local folder or TFS folder or somewhere else?

Thanks
Rakesh

**Comment by WaelHamze** [comment]
This file would be on the agent server. I suggest you publish any required files needed for releases as artifacts: https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/publish-build-artifacts?view=vsts
