### ISSUE TITLE
Unable to Login to Dynamics CRM

### ISSUE THREAD

**Issue by TclasenITVT** [WaelHamze/xrm-ci-framework#138]
I have set up a new Dynamics CRM OnPrem. When I try to import my Solutions via the TFS Build Agent I get the Error "Unable to Login to Dynamics CRM". The Build Agent is able to Ping the CRM Server. The ConnectionString I use works for Exporting Solutions. The User has the "SystemAdministrator"-Role.  Is there anything I'm missing? Before I changed the connection string to the new environment it worked fine.
The MSCRM CRM Ping Task works too.

**Comment by WaelHamze** [comment]
Ping/Import/Export use the same method to connect to Dynamics. If the ping works you should not be getting unable to login on the import if you use the same connection string. I suggest you check that you haven't missed anything in the setup.
