### ISSUE TITLE
Nuget Packaging

### ISSUE THREAD

**Issue by 89P13** [WaelHamze/xrm-ci-framework#14]
I'm preparing to create a build with VSTS Online with CRM 365 but it does not appear that nuget package is available for reference in the NuGet Installer task. Is there a work around for this or can you put this into your build process so that it's available?

**Comment by WaelHamze** [comment]
What are you looking to get packaged in Nuget? The PowerShell dlls and the scripts that I provide?
I know some users store the scripts and Dlls in source control and execute it that way.

**Comment by 89P13** [comment]
I would think that only the .DLLs would be in the packages. Currently, I'm using your code in an unlisted nuget to try to get the XRM Framework working in a PS build task to just restore and reference the DLLs. Then in my build task i could use your scripts, use my scripts or whatever to invoke the methods in the dlls.

As for the PS scripts, my feeling is that your PS scripts are excellent scaffolding where I would guess people would take those and adjust them as needed.

**Comment by 89P13** [comment]
When you do get this going, I did have an issue with restoring the XRM Framework from nuget and referencing the correct .DLLs. For example, I had to copy Xrm.Framework.CI.PowerShell.Cmdlets.dll nuget packages to the \bin\debug folder to get this to work. I'd be glad to send a more full email to you, just DM the tweet I sent you asking for your email :)

**Comment by WaelHamze** [comment]
Sounds great. I will create a nugget package for the dll.

**Comment by WaelHamze** [comment]
Hi, here is the public nugget package: https://www.nuget.org/packages/XrmCIFramework/
Would you be able to give it a try and let me know if it works for you?
I have pushed the changes too.

**Comment by 89P13** [comment]
Sure thing, will let you know in a day or so.

**Comment by WaelHamze** [comment]
Excellent take your time.

**Comment by WaelHamze** [comment]
I will close this issue for now. Please re-open if you face any issues. Would be good to know if this works for you anyway :)

**Comment by 89P13** [comment]
Sounds good and will do. We got killed last week with a CRM/Scribe prod issue so I wasn't able to validate the new nugget package. This week should be better as we've resolved it and will carve out time. Thanks for your work. 

On a similar note but different context, would you be able to create a real world demo of CI and your tooling? I work at RSM and we've discussed at length about increasing crm capacity among crm developers but have yet to be provided a real how-to from Microsoft or Sonoma Partners. I believe it's possible but I cannot connect the "process dots", if you will. If you believe you may I would love to put you in touch with my Director to further define our "ask".

Thanks,

Jose

**Comment by WaelHamze** [comment]
Hi Jose, thanks for coming back to me. Would be interested in knowing more about your "ask", please send me an email and we will take it from there :)

**Comment by 89P13** [comment]
I've been able to reference your new nuget package in my project solution
without issue and I've also sent you an email from my @rsmus.com email
account.

Thank you Wael!

Jose Quinones
