### ISSUE TITLE
Not able to select Task Version 9.*

### ISSUE THREAD

**Issue by karthikmcs** [WaelHamze/xrm-ci-framework#143]
Hi - I am not able to select the task version 9.* for any task.

I am able to connect to a CRM instance which is 8.2, however not able to connect to 9.* instances using MSCRM Ping Task.

The drop down is not showing 9.*

![image](https://user-images.githubusercontent.com/17010319/43855665-56bd994a-9b14-11e8-8bac-b17b8eb3e189.png)

**Comment by WaelHamze** [comment]
@karthikmcs are you using TFS or VSTS? Looks like your account has an older version of the extension. Might be worth re-installing.

**Comment by WaelHamze** [comment]
Please re-open if you still facing issues
