### ISSUE TITLE
Unable to install into TFS On-Premise

### ISSUE THREAD

**Issue by mikejramsey** [WaelHamze/xrm-ci-framework#144]
I am using TFS On Premise, which does not allow larger than a 20meg extension. I have downloaded your source, trimmed out the online only tasks and rebuilt the vsix (which comes in at just over 17megs now). On my manage extensions screen in TFS, when i upload the vsix file, i get an error stating "An extension with this key already exists". I verified that this extension does not exist on the server, in my browser cache or in TFS cache. I've even gone as far as repacking it with a different id to test with. In the end, i am unable to get this extension to install in TFS On Premise, no matter what attempt.  I am able to install other vsix packages and extensions without issue. 

Technically, i have two questions.... First, would you have any idea why i cannot get this to install. Second, and more importantly, will you package this extension for on premise installation?

**Comment by WaelHamze** [comment]
@mikejramsey yes unfortunately TFS has this limitation at the moment.
1. Let me email the product team to find out the plans for lifting this limitation
2. which id did you change?
3. Yes definitely need to support TFS, there is a number of options I am looking at. Any suggestions on this are welcome.

**Comment by mikejramsey** [comment]
quick update. i managed to get this extension installed on Premise by downloading the current package vsix and deleting any of the Online task folders and removing them from the extension json. This got the package down to just under 20megs and was able to upload and install into TFS.

**Comment by NetSoerfer** [comment]
Following @mikejramsey's suggestion to trim the 'Online' task folders and removing the references from the extension.**vsomanifest** JSON file, repacking the whole thing as ZIP and renaming it back to .vsix, I was able to install it on TFS 2017 on-prem.

I installed the remaining tasks in a separate extension by repeating the above steps, leaving only the 'Online' tasks. I additionally edited the extension.**vsixmanifest** XML file, changing the **PackageManifest.Metadata.Identity** node's **Id** attribute to "xrm-ci-framework-online-build-tasks", and the **PackageManifest.Metadata.DisplayName** node to "Dynamics 365 Online Build Tools". I could then install this new package too, and now have two extensions "Microsoft 365 Build Tools" and "Microsoft 365 Online Build Tools", apparently providing all functionality to the collection - in the Release tasks I can see **MSCRM Backup Online Instance** as well as **MSCRM Import Solution** (to name just one example from each extension).

**Comment by WaelHamze** [comment]
@mikejramsey @kleinarne Glad you managed a find a way to get this working.

I am happy to confirm that I will be introducing a tool installer in the next release (9.2.x), The extension size including all tasks has reduced from almost 25MB to under 10MB. All the task have been updated to version 10 to avoid breaking existing builds. Using this mechanism I am now able to add more tasks. @sagarhgaikwad thx for your help in refactoring the remaining tasks.

**Comment by WaelHamze** [comment]
Released to Marketplace: https://github.com/WaelHamze/dyn365-ce-vsts-tasks/releases/tag/v9.2.7
