### ISSUE TITLE
Issue with Export Solution

### ISSUE THREAD

**Issue by blucas2016** [WaelHamze/xrm-ci-framework#145]
Entered connection string as specified but still get this error:

"Organization cannot be null or empty.
Parameter name: Organization Name"

Shouldn't it pick the organisation name from the login or URL param found in the connection string?
If I add  a wrong password, it throw a wrong credential error. that means it is login in but failing to resolve the organisation

**Comment by blucas2016** [comment]
looked into the code, found you are using  Microsoft.Xrm.Tooling to parse the connection string. I tried  Microsoft.Xrm.Tooling and was able to notice it fails for AD synched user ids.

**Comment by WaelHamze** [comment]
@blucas2016 Yes I am using Microsoft.Xrm.Tooling and this library is not the best at giving meaningful/useful error messages.

I can see you are using an AD synced user to connect. Below are some options for you.

1. I can confirm that I have seen Microsoft.Xrm.Tooling working with SSO. In one instance WS-Trust was not enabled in the SSO module which was preventing this from working. You can run Fiddler or raise a case with MS to help resolve this.

2. SSO is normally useful for active users. For automation I see many people using Azure Active Directory (Not AD Synched) accounts to perform deployments. This would be the easiest way to resolve this.

3. You could consider using OAuth which is support by the Xrm Tooling: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/xrm-tooling/use-connection-strings-xrm-tooling-connect

4. Finally sometimes swapping the domain name with the unique org name does the trick too so it is worth a try

Hope this is helpful. Let me know how you get on.

**Comment by blucas2016** [comment]
Hi Wael,

Thanks for the reply.

Problem just disapeared. I think it could had been a firewall. the only change I remeber doing was entering the connection string without quotes.


Brilliant work. that used to be a painful task on the CCNET days.

Do you have a control to check extracted solution files back to git?

Cheers


________________________________

**Comment by WaelHamze** [comment]
@blucas2016 glad this is working for you now. Would be great if you can update the marketplace review.

Regarding checking into git, the task it self doesn't do it as I want to keep it flexible since users might want to use it differently and with other version control systems. You can take a look at this issue on how to implement this: https://github.com/WaelHamze/xrm-ci-framework/issues/95
