### ISSUE TITLE
Not able to connect to CRMONLINE version 9.0

### ISSUE THREAD

**Issue by puneet16** [WaelHamze/xrm-ci-framework#146]
Get-XrmSolution : Couldn't connect to CRM instance after 3 attempts: Unable to Login to Dynamics CRM
At C:\ImportSolution.ps1:61 char:13
+ $solution = Get-XrmSolution -ConnectionString "$crmConnectionString"  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-XrmSolution], Exception
    + FullyQualifiedErrorId : System.Exception,Xrm.Framework.CI.PowerShell.Cmdlets.GetXrmSolutionCommand

**Comment by WaelHamze** [comment]
Looks like an issue with username/password and/or permissions.

**Comment by puneet16** [comment]
No, same way I am able to connect to the CRM Online version 8.2 but not 9.0. 
Also, I am using DYN365 Project. 
Do I need to use MSDYNV9 project for 9.0

**Comment by WaelHamze** [comment]
Are you using the PowerShell Cmdlets or Marketplace Extension?

**Comment by WaelHamze** [comment]
For 9.0 I suggest you use MSDYNV9 and also take a look at this post https://waelhamze.wordpress.com/2018/01/11/dynamics-365-ce-tls-connectivity-issue-from-net-and-powershell/

**Comment by puneet16** [comment]
I have exteded the XRM-CI dll based on our requirements. 
So Just want to know, If I want to connect to V9.0 then do I need to use MSDYNV9 project ?
