### ISSUE TITLE
CRM2015 Task Versions

### ISSUE THREAD

**Issue by DavidDunn09** [WaelHamze/xrm-ci-framework#15]
Hi, great set of tools you have here, thank you! Is it possible to bundle up the CRM2015 versions that you already have the code for into the visualstudio.com marketplace tasks? Ideally, the version dropdown on the task would let you switch between 8* and 7* task versions (and future versions as well).

When I run the 8* on a CRM2015 I get this error:
##[debug]System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Unrecognized request parameter: ExportExternalApplications (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault).

So I would assume most of the 8* framework is backwards compatible, authentication etc as it gets past that. Hopefully that makes it easy!

cheers

**Comment by jenschristianschroder** [comment]
I second the request for 7* version.

Badly needing this for CRM 2015 environments

**Comment by DaveKLloyd** [comment]
Me too: Is that the only way to get ride of this error: Unrecognized request parameter: ExportExternalApplications?

**Comment by WaelHamze** [comment]
Yes I am using the latest SDK in these build and this seems to fail with the previous version of the endpoint. You can download the 2015 version and invoke the Powershell scripts directly.

**Comment by DaveKLloyd** [comment]
Thank you for the response.

I’ll go grab the 2015 version in Github and try calling them directly.



[cid:image003.jpg@01D2B84F.BA00AFA0]

Regards,
Dave Lloyd
http://www.Lloyd.ca
(905) 875-6251
