### ISSUE TITLE
Unable to connect when using a AD sync'd credential, but .onmicrosoft.com credential works fine

### ISSUE THREAD

**Issue by KitEdgecombe** [WaelHamze/xrm-ci-framework#150]
Hi Wael,

When using the MSCRM Export/Import Solution tasks, there's an error being thrown when connecting using an AD sync'd credential. However, if a .onmicrosoft.com credential is used, then there's no problem. Both credentials are users of the instance and have the system administrator role assigned.

The issue *might* be related to TLS 1.2 . What looks to be a similar issue was resolved at the bottom of this post in the Dynamics Community (https://community.dynamics.com/crm/f/117/t/235290).

Would it be possible to specify the security protocol before the call is made to the connect to CRM constructor?

Love your work!

Cheers
Kit

**Comment by WaelHamze** [comment]
Hi @KitEdgecombe,

Thanks for the feedback. The TLS 1.2 is already built into the framework.

I am using Microsoft.Xrm.Tooling library internally. You can test connectivity using a simple console App and run fiddler if needed.

Below are some options for you.

1. I can confirm that I have seen Microsoft.Xrm.Tooling working with SSO. In one instance WS-Trust was not enabled in the SSO module which was preventing this from working. You can run Fiddler or raise a case with MS to help resolve this.

2. SSO is normally useful for active users. For automation I see many people using Azure Active Directory (Not AD Synched) accounts to perform deployments. This would be the easiest way to resolve this.

3. You could consider using OAuth which is support by the Xrm Tooling: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/xrm-tooling/use-connection-strings-xrm-tooling-connect

4. Finally sometimes swapping the domain name with the unique org name does the trick too so it is worth a try

Kind regards

Wael

**Comment by KitEdgecombe** [comment]
Thanks Wael. I'll take a look at those options and will let you know the outcome.

Cheers

Kit

**Comment by WaelHamze** [comment]
@KitEdgecombe closing this issue, please re-open if you still have issues.
