### ISSUE TITLE
Unable to generate json files using GetPluginRegistrationJsonMapping.ps1

### ISSUE THREAD

**Issue by DharanidharanBalasubramaniam** [WaelHamze/xrm-ci-framework#152]
I am trying to generate json file for my existing assembly. I am unable to generate it. Can you please help me on this?

**Comment by WaelHamze** [comment]
What is the issue that you are getting?

**Comment by TNoronha** [comment]
Hey, I was trying to generate the json file, but I cannot find the ps1 for doing it... I only found the .cs class which might be the solution, is that it?

**Comment by WaelHamze** [comment]
@TNoronha The best thing is to look at the sample project here. It contains scripts to generate json file and update from json. https://github.com/WaelHamze/xrm-ci-framework/tree/master/Sample/Xrm.CI.Framework.Sample/Xrm.CI.Framework.Sample.Plugins

Make sure you update to the latest version of xRMCIFramework from Nuget

**Comment by TNoronha** [comment]
Oh gotcha, thanks!
Just one final question, if I want to run this as a step in a build definition, how would I get the powershell command from the nuget?

**Comment by WaelHamze** [comment]
Good question. If you notice in the sample I shared there is a tools project which has a nuget reference to the framework. So if you do a nuget restore on the solution in the build it will download the framework too.

There is a also a VSTS task called Plugin Registration. You can use that but you may have to wait until early next week when I release an update version compatible with your json.
