### ISSUE TITLE
Restore Online Backup failing with InternalServiceError

### ISSUE THREAD

**Issue by screenmoniker** [WaelHamze/xrm-ci-framework#153]
Hello - as described in title, I cant get the Restore CRM Instance to work. RestoreOnlineInstance.ps1 is failing when it calls the cmdlet on line 74 with non-helpful InternaServiceError. This is repeatable when running a similar code snippet (pasted below) locally on my laptop directly from powershell. Is this problem repeatable for you or do you think I am using the script/cmdlet  incorrectly? Note:
- my CRM online instance is trial and located in APAC
- I am trying to restore to the same instance as backup. 
- I have tried with 2 different backups on the instance's history with same result
- i can call other cmdlets such as "crm-getintances" and "crm-getbackups" flawlessly, so I wouldn't expect this to be an authentication issue unless restore uses a different authentication model (e.g. oAuth?)

Here is my code which reproduces the same issue is see in your script:

```
$targetInstanceId = "some instance Id that was found by running Get-CRMInstances"
$instanceBackupId = "some backup Id that was found by running Get-CrmInstanceBackups"
$secpasswd = ConvertTo-SecureString "some password" -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential ("some username", $secpasswd)
$apiUrl =  "https://admin.services.crm5.dynamics.com/" #my instance is in APAC 
$operation = Restore-CrmInstance -ApiUrl $apiUrl -Credential $mycreds -BackupId $instanceBackupId -SourceInstanceId $targetInstanceId -TargetInstanceId $targetInstanceId -Verbose
```

The error comes out as...
```
VERBOSE: Connecting to API server: https://admin.services.crm5.dynamics.com/
VERBOSE: Entering RestoreCrmInstance - ProcessRecord
VERBOSE: Executing RestoreCrmInstance
VERBOSE: Requesting Authentication - Start
VERBOSE: Requesting Authority From server - Start
VERBOSE: Requesting Authority From server - Finished : 00:00:00.4814245
VERBOSE: Requesting Authentication - Completed : 00:00:01.5081870
VERBOSE: Failed RestoreCrmInstance - ProcessRecord : 00:00:06.1808573
Restore-CrmInstance : Operation returned an invalid status code 'InternalServerError'
At C:\scripts\CRM Restore Test.ps1:43 char:15
+ ... operation = Restore-CrmInstance -ApiUrl $apiUrl -Credential $mycreds  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Restore-CrmInstance], HttpOperationException
    + FullyQualifiedErrorId : Microsoft.Rest.HttpOperationException,Microsoft.Xrm.OnlineManagementAPI.RestoreCrmInstance
```

I should also note that I do not know of any way to investigate this internal error further on my Dynamics Online instance (i.e. can't find any system error log to review), so all I have is this. 

What do you think?

**Comment by WaelHamze** [comment]
@screenmoniker 

Yes I am seeing the same behaviour on my end. This used to work in the past. I have heard of other users having same issue.

I believe this is broken at the vendor end. I will be raising a case to get some official feedback.

You could do the same things on your end.

I'll add it to known issue in the next release.

**Comment by screenmoniker** [comment]
Thanks for the confirmation. I will also raise a ticket on this. We are eager to see this work. 

FYI - on our pipeline, we find that the import solution function can generally fail (manually or programmatically) if the newly imported solution version attempts to change an entity type in an incompatible way (i.e. string to bool). Although rare, this does happen during development and our current fix approach is to either reset or restore the target instance before importing the new version. Therefore we want to add this restore step to our VSTS pipeline so that it does full install from a known point every time, and not a sort of patch from the last install.

We understand that we can use managed solutions and remove them to attempt to get a clean install every time, but for our instance we are using an unmanaged solution for 1 instance on our pipeline. For this 1 instance, we want to use the restore function.

**Comment by WaelHamze** [comment]
@screenmoniker I have a case open as well. Will let you know how it goes.
I normally use the stage for upgrade with managed solution for breaking changes and removing components. The restore can come in handy for unmanaged environments unless you provision a new instance and deploy all components again.

**Comment by morganeason** [comment]
@WaelHamze not sure if this is relevant to everyone but this is the response I got from MS on my ticket about this issue.

"I engaged technical resources to check why your snippet was failing, and unfortunately, the option to Restore Version 9.0+ Instances via PowerShell is not implement.
But it is expected that this feature is going to be implemented in future releases.
 
The snippet that you are using is going to continue working for instance version 8.2."

**Comment by WaelHamze** [comment]
@amessad not yet, i'll try to get an update from MS.

**Comment by brianstokes** [comment]
@WaelHamze any update on this? Would it help to create another MS ticket?

**Comment by aboodh95** [comment]
@WaelHamze any update regarding this issue, in case not, is there a way we can copy the production to QC instance with AzureDevOps

**Comment by HIREN-AITC** [comment]
I am getting below error
![image](https://user-images.githubusercontent.com/42240205/60669887-b2cf4f80-9e6f-11e9-84d1-588cf58b1716.png)

**Comment by WaelHamze** [comment]
This should be working now
