### ISSUE TITLE
Company Network

### ISSUE THREAD

**Issue by Criviere** [WaelHamze/xrm-ci-framework#154]
Hello,

I'm trying to use this tool on Visual Studio Team Services (hosted online) for crm2016 that is hosted on a company network ("on premise"). I'm getting this error when trying to build on the pipeline I created on VSTS: "Organization cannot be null or empty."

The url structure is: http://crmdev.companynameu.companyname.com

Any help is appreciated thank you.

**Comment by rappen** [comment]
Is your CRM machine accessible from the outside, without VPN or similar?
Otherwise VSTS cannot perform tasks on it, and you need to set up your own agent on the same network.
https://docs.microsoft.com/en-us/vsts/pipelines/agents/v2-windows?view=vsts

**Comment by Criviere** [comment]
@rappen no, our CRM application is not accessible from outside the network. Although, I'm thinking I can configure the company proxy on the self hosted build agent and perhaps that will make it accessible? In any event, I now have some confirmation of what I suspected. Thank you very much for your reply. This will help me greatly.

**Comment by rappen** [comment]
I definitely advise you to set up your own build agent and separate queue for that. It is quite easy, and you can easily test it on your local client to verify the idea before dedicating a server to it.

**Comment by iNSidemen** [comment]
Add your organization unique name at the end of your url. :-)

Norbert

**Comment by iNSidemen** [comment]
I know, that’s very confusing, but that the way the connection toolkit wants it.

Norbert

**Comment by Criviere** [comment]
@rappen I'm in the process of this now looking for some more extensive documentation on how to do this. Thanks

**Comment by Criviere** [comment]
@iNSidemen The problem is that the CRM2016 instance I'm attempting to connect to is hosted on the company network. It is not accessible from outside of the company network. Our Visual Studio Team Services is hosted on the internet which means that when I create the build agent using the UI offered by VSTS it is not able to connect to the CRM instance which is hosted on our company network.

**Comment by Criviere** [comment]
@rappen So, I was able to successfully run the build agent locally, however, I still get the organization error for the build step handled by MSCRM. Perhaps there may be a special url format for an on-premise instance of CRM2016? 

 * Also, I noticed that in order to see the progress of the build I still have to use VSTS. The build agent that runs locally is only listening for jobs...

**Comment by rappen** [comment]
True, the build agent is just an agent picking up waiting jobs from the designated queue in VSTS, so you don't have to change your pipeline in any way :)
A neat little trick you can use is to start XrmToolBox, create a connection to the org, and then click "Show connection string" from the connection manager window!
https://twitter.com/rappen/status/1006909082102530048

**Comment by Criviere** [comment]
@rappen It appears that in order to utilize the tools in this repository I would need to do this:

https://technet.microsoft.com/en-us/library/dn920266.aspx

Also, I downloaded the XrmToolBox, but was unable to connect to the crm2016 instance utilizing the tool. 

* Ironically, when I use the packagedeployer tool I'm able to connect to my crm2016 sandbox instance.

**Comment by iNSidemen** [comment]
Your organization does not need to be accessible from the internet if your are using a locally hosted build agent. Your are missing your organization unique name at the end of your url. Try it.

https://msdn.microsoft.com/en-us/library/mt608573.aspx#Examples

Norbert

**Comment by Criviere** [comment]
@iNSidemen You were absolutely right. Thank you to everyone who responded.

**Comment by WaelHamze** [comment]
Thx all for your help. Great community effort.
