### ISSUE TITLE
Plugin Register VSTS Task fails to register

### ISSUE THREAD

**Issue by tiagodenoronha** [WaelHamze/xrm-ci-framework#157]
Hey,

Was trying to register a plugin using the Preview Plugin Registration and i'm getting a rather generic error:

2018-08-30T17:47:17.1782037Z Updating Plugin Assembly: D:\a\r1\a\_CI - CustomWorkflows\drop\CustomWorkflows\(...)
2018-08-30T17:47:42.0914531Z ##[warning]Extracted id using plugin assembly name (...)
2018-08-30T17:47:51.9920975Z ##[error]Plug-in assembly does not contain the required types or assembly content cannot be updated.

Can you shed some light on it?
Thanks!

**Comment by WaelHamze** [comment]
@TNoronha You normally get this error when the DLL you compile from source has less types than the DLL that already exists in CRM.

I suggest you use the Plug-in Registration Tool to compare.

Note there is an update for the task that will work with the new json. I will release shortly to marketplace.

**Comment by TNoronha** [comment]
I used the Plug-in Registration tool but it has the same types..

I didn't attach a mapping file, since I was still trying to resolve the issue regarding the PowerShell command in the build. Could that be it? :)

**Comment by TNoronha** [comment]
Hey, I tried exporting the json manually and trying to upsert the plugin and i'm still unable to update the plugin :/

**Comment by WaelHamze** [comment]
@TNoronha please try this again with the latest versions.

Re-generate the json and then try to deploy

https://www.powershellgallery.com/packages/Xrm.Framework.CI.PowerShell.Cmdlets/9.0.0.22
https://github.com/WaelHamze/dyn365-ce-vsts-tasks/releases/tag/v9.2.7

**Comment by TNoronha** [comment]
Hey!

I tried without associating a json and it registered.
I'll do another test with a json associated to see if it updates.

**Comment by WaelHamze** [comment]
@tiagodenoronha I am closing this I have was able to do this successfully on the latest tools. Please re-open if you still have any issues.

**Comment by tiagodenoronha** [comment]
Will do.
Sorry, have been caught a bit with work and haven't been able to test it yet.
I'll open a new issue if I encounter any bugs.
Thanks,
Tiago

On Sep 20, 2018 18:44, WaelHamze <notifications@github.com> wrote:

@tiagodenoronha<https://github.com/tiagodenoronha> I am closing this I have was able to do this successfully on the latest tools. Please re-open if you still have any issues.
