### ISSUE TITLE
Stage for Upgrade Task fails

### ISSUE THREAD

**Issue by RaoulRobles** [WaelHamze/xrm-ci-framework#158]
Hi,

It appears that the stage for upgrade task fails because whilst creating the Upgrade solution it either changes the base solution to the Upgrade solution or it removes the base solution.

So the error you get, logically, reads: 
![image](https://user-images.githubusercontent.com/43003076/45094460-a2e5c280-b11b-11e8-9780-4ddb1d2adf6a.png)

here's a screenschot of the Solutions for the target (trial) environment:
![image](https://user-images.githubusercontent.com/43003076/45094501-d0cb0700-b11b-11e8-98c5-f53999edbf0c.png)

as you can see. Normally you would expect 2 solutions with the same name, one of which with the extension _upgrade or something and the other being the base solution. In this case I see just one.

I realize that this is a relatively new Task, but I am wondering whether such bugs can already be taken into consideration.

Thanks in advance!

**Comment by WaelHamze** [comment]
@RaoulRobles yes all bugs will be taken into consideration.

To use the upgrade you have to:

1. Use the MSCRM Import Solution Task (Tick holding solution). This will import the solution as a holding solution (i.e. you will have two solutions after this)
2. Use the MSCRM Apply Solution. This will do the upgrade (i.e. merge the two solutions)

Let me know if you still have issues after this.

Note the Apply Solution is a Sync solution and will sometimes timeout unfortunately.
