### ISSUE TITLE
How to download entire solution through MSCRM Export Solution?

### ISSUE THREAD

**Issue by kapsofficial** [WaelHamze/xrm-ci-framework#162]
Hey WaelHamze,

Was trying to export the entire solution which is "**default**" solution inside 365. Shall I use the same "**MSCRM Export Solution**" plugin or there is some other way.

Your help would be appreciated.

Thanks
Kapil

**Comment by WaelHamze** [comment]
Why are you trying to export the default solution? I have never tried this. You could give it a try with the task.

**Comment by kapsofficial** [comment]
thanks WaelHamze for your quick response

**Comment by WaelHamze** [comment]
The task uses this API: https://docs.microsoft.com/en-us/dotnet/api/microsoft.crm.sdk.messages.exportsolutionrequest?view=dynamics-general-ce-9

Might be worth checking with vendor on this. I am not aware that this is possible.
