### ISSUE TITLE
New task to remove/delete a solution

### ISSUE THREAD

**Issue by bguidinger** [WaelHamze/xrm-ci-framework#165]
It would be nice if there was a task to delete a solution.  This would be useful in situations where you are deploying multiple solutions (as holding solutions) and some of the solutions successfully import, but others fail.  This would allow you to delete the successfully imported holding solutions to perform a rollback.

This can be accomplished with the DeleteRequest on the solution ([link](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/create-patches-simplify-solution-updates#delete-a-patch)).

I would propose that the task take the solution name as an input parameter, perform a lookup to get the GUID of the solution, and then execute the DeleteRequest.

**Comment by WaelHamze** [comment]
@bguidinger Thx for the suggestion, I have tried to do this in PS. The only issue I faced is that delete is a Sync call so in many cases it does fail. Do you think the task should trap the error and continue checking in the background?

Please raise this issue on this repo as this build tasks have moved: https://github.com/WaelHamze/dyn365-ce-vsts-tasks
