### ISSUE TITLE
SolutionPackager bug - fixed in v9.0.2.5 of CoreTools

### ISSUE THREAD

**Issue by mattp65** [WaelHamze/xrm-ci-framework#166]
There is a bug in SolutionPackager that was fixed in v9.0.2.5 of the CoreTools. This causes errors when packaging as it adds an invalid node to the Customization.XML file resulting in errors when importing the packed solution.

**Comment by jordimontana82** [comment]
Is that the savedqueries in Visualizations  nor or the Version node issue? :)

**Comment by mattp65** [comment]
Visualizations/SavedQuery node issue.

**Comment by jordimontana82** [comment]
right indeed, that was fixed in that release.

**Comment by mattp65** [comment]
Just to be clear, the issue is the most recent deployed version of the ci-framework is using the bad version of Solution Packager. Needs to be rebuilt with the fixed tools.

**Comment by WaelHamze** [comment]
I take it you are referring to the Build Tools Solution Packager Tasks, You want these to use the latest version of the SDK right?

**Comment by mattp65** [comment]
Yes. Currently the tasks are using v9.0.2.4 of CoreTools and that has a known bug. They have resolved a few issues and are currently on v9.0.2.6. 

See release notes here: [https://www.nuget.org/packages/Microsoft.CrmSdk.CoreTools ](https://www.nuget.org/packages/Microsoft.CrmSdk.CoreTools )

**Comment by WaelHamze** [comment]
Updated to v9.0.2.6
