### ISSUE TITLE
Export solution to branch directory

### ISSUE THREAD

**Issue by MarcusAurelio** [WaelHamze/xrm-ci-framework#170]
Not sure if I have understood the export function. The export function completes and I read in the log that the directory path is: D:../../..solution.zip - however, where is the solution located? Is it uploaded to the specified branch directory, in this case Azure DevOps online? If that is true, I am not seeing it  uploaded to my specified directory.

**Comment by stephenacrown** [comment]
Hi @MarcusAurelio 

This directory is on the build agent VM, not as I suspect you think: into a repo.


This file (which in the screenshot below shows the Solution is being exported at the start of the set of tasks) can then be copied to a directory which in turn can be published as an artifact:

![image](https://user-images.githubusercontent.com/38353501/48478661-d66c5980-e7fc-11e8-948f-45b894ce6608.png)


Publish the artifact that includes the solution .zip file:

![image](https://user-images.githubusercontent.com/38353501/48478724-fc91f980-e7fc-11e8-8c2e-e98abded7dcc.png)


The artifact can then be used as part of a release, and the deployment task in our case as below is using PackageDeployer as we are deploying both solution and also data:

![image](https://user-images.githubusercontent.com/38353501/48478825-54306500-e7fd-11e8-9a63-eadf0bb88370.png)

Hope this helps.

Stephen

**Comment by WaelHamze** [comment]
@stephenacrown thanks for the clarification :)

**Comment by MarcusAurelio** [comment]
> Hi @MarcusAurelio
> 
> This directory is on the build agent VM, not as I suspect you think: into a repo.
> 
> This file (which in the screenshot below shows the Solution is being exported at the start of the set of tasks) can then be copied to a directory which in turn can be published as an artifact:
> 
> ![image](https://user-images.githubusercontent.com/38353501/48478661-d66c5980-e7fc-11e8-948f-45b894ce6608.png)
> 
> Publish the artifact that includes the solution .zip file:
> 
> ![image](https://user-images.githubusercontent.com/38353501/48478724-fc91f980-e7fc-11e8-8c2e-e98abded7dcc.png)
> 
> The artifact can then be used as part of a release, and the deployment task in our case as below is using PackageDeployer as we are deploying both solution and also data:
> 
> ![image](https://user-images.githubusercontent.com/38353501/48478825-54306500-e7fd-11e8-9a63-eadf0bb88370.png)
> 
> Hope this helps.
> 
> Stephen

Do you mind explaining how you are moving Portal data? There isn't much documentation on the tools.

**Comment by stephenacrown** [comment]
Hi @MarcusAurelio 

We have two elements to promoting to production via a sort of "clone" phase:

1. Solutions (to support the portal data)
   1. fully automated for export and deployment
1. Config and data 
   1. [manually driven for export only via](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/portals/migrate-portal-configuration#export-portal-configuration-data):
      1. _\<driveletter>\:\ConfigurationMigrationTool\ConfigurationMigration\DataMigrationUtility.exe - yes a manual GUI driven tool in 2018!_
   1. [automated deployment via ](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/deploy-packages-using-package-deployer-windows-powershell)_\<driveletter>\:\ConfigurationMigrationTool\PackageDeployment\PackageDeployer.exe_

My advice is to get this all working via the GUI tools (export and deploy) in early days to validate the data/config etc. is all working before moving onto this Azure DevOps extension for full pipeline automation.

We are moving data through the (simplified and summarised) phases:

1. lab environment (experimental/high risk working out how to do things - manually driven)
1. integration environment (where understood work gets integrated into an environment ready to be "cloned" and Continuous Integration and the partially automated "clone" of the two elements is kicked off)
1. Test environment(s) (this is the Continuous Delivery part - and covers automated deployment of a new test environment(s), manually (no API yet!) connecting the portal add-on to this new env., and then deploying the solution and data exported from phase 2 (integration) to this environment)
1. Sign-off/Acceptance environment (fully automated deployment covers automated deployment of a new test environment(s), manually (no API yet!) connecting the portal add-on to this new env., and then deploying the solution and data exported from phase 2 (integration) to this environment assuming earlier testing was successful)
1. Ring based production deployments with a pause between each customer to understand if the release should proceed

See here for portal data migration:
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/portals/migrate-portal-configuration

Does this help/answer your question?
