### ISSUE TITLE
MS CRM Package deployer is failing

### ISSUE THREAD

**Issue by CrmDev23** [WaelHamze/xrm-ci-framework#173]
Hi
First of all, thank you for this awesome work!
I use the "MS CRM Package deployer" vsts task and run all the time in this error message. The task fails and the release build stops executing subsequent tasks. In CRM everything looks fine and no upgrade solution is left.
![image](https://user-images.githubusercontent.com/13016624/48611989-e9f7fb80-e987-11e8-9df7-7614d7a8b68e.png)
If I run solution packager locally (using the UI), everything works fine:
[log.txt](https://github.com/WaelHamze/xrm-ci-framework/files/2589890/log.txt)

**Comment by CrmDev23** [comment]
I guess, it's an error in the package deployer powershell module. If I try to run it in powershell locally, I get:
![image](https://user-images.githubusercontent.com/13016624/48693516-fbd0dd00-ebd9-11e8-9508-4c91569bae3a.png)

**Comment by WaelHamze** [comment]
@CrmDev23 looks like some issues the module. You can consider using the Import Solution Task alternatively to import the solution and use the package deployer for anything else. You may need to add a dummy solution in package deployer.
