### ISSUE TITLE
Timeout when using „Apply Solution Upgrade“

### ISSUE THREAD

**Issue by pahansen** [WaelHamze/xrm-ci-framework#174]
From time to time the „Apply Solution Upgrade“ task times out even though the timeout is already set to 15 minutes. However, by the time the tasks times out the upgrade is already finished. So the apply solution upgrade task could have finished succesfull already. Any ideas what might cause this? Thanks in advance!

**Comment by WaelHamze** [comment]
@pahansen are you running this in Sync or Async mode? I suggest you run this in Async mode to avoid the timeout. Otherwise I suggest you increase the timeout.
