### ISSUE TITLE
Dynamics 365 connectivity

### ISSUE THREAD

**Issue by sanjay1913** [WaelHamze/xrm-ci-framework#175]
Hello Wael,
I am trying to connect Dynamics 365 Sanbox instance with a user single sign on from one of the Azure AD User. But did not succeed. but with @onmicrosoft account it works . Is that possible to share the connection string with a Single Sign on user? Example user : userSks@abc.xyz.com and password : userSks@1223. 
Thank you in advance !
Sanjay

**Comment by WaelHamze** [comment]
@sanjay1913 the framework uses xrm tooling: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/xrm-tooling/use-connection-strings-xrm-tooling-connect

SSO should work if you have this configured correctly to work with services. If any issues you can always open a ticket with MS to see why it is not working. Best to try this with a simple console app for debugging purposes.
