### ISSUE TITLE
MSCRM Plugin Registration task had some dead links.

### ISSUE THREAD

**Issue by sgpark888** [WaelHamze/xrm-ci-framework#178]
Copied from the Mapping File Path info on the MSCRM Plugin Registration task.
Broken links are in **bold**

Plugin registration json/xml mapping used to register assembly/types/steps.

Mapping json(PluginRegistrationMappingExample.json)/xml file sample can be found here: https://github.com/WaelHamze/xrm-ci-framework/blob/master/MSDYNV9/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell.Cmdlets/PluginRegistration. 

JSON schema which will help you to generate plugin registration mapping can be found here: **### https://github.com/WaelHamze/xrm-ci-framework/blob/master/MSDYNV9/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell.Cmdlets/PluginRegistration/PluginRegistrationMappingSchema.json**. 
How to use schema can be found here: https://blogs.msdn.microsoft.com/webdev/2014/04/10/intellisense-for-json-schema-in-the-json-editor/. 

To generate plugin registration JSON mapping from existing assembly/type/steps from a specific solution, please use cmdlet: **### https://github.com/WaelHamze/xrm-ci-framework/blob/master/MSDYNV9/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell.Scripts/GetPluginRegistrationJsonMapping.ps1**

**Comment by WaelHamze** [comment]
Thanks for spotting. This has been fixed and will be deployed in the next release

**Comment by WaelHamze** [comment]
Fixed.
