### ISSUE TITLE
Trying to Connect to CRM 365

### ISSUE THREAD

**Issue by emiliocampa-hoyos** [WaelHamze/xrm-ci-framework#18]
Hi guys, first of all this framework sounds amazing. I definitively will use this to automate our continuous integration environment. I am having trouble executing any of the cmdlets since the program is not liking my CrmConnectionString (at least that is what I believe since it is returning null every single time). Below is the error I am getting as well as the command I am executing, thanks for this amazing tool!

Command in PS:
.\ExportSolution.ps1 -CrmConnectionString "Url=https://organizationName.crm.dynamics.com; Username=myName@organizationName.onmicrosoft.com; Password=myPassword;" -SolutionName "Default" -ExportSolutionOutputPath C:\Users\User1\Documents

Error : 
 Export-XrmSolution : Object reference not set to an instance of an object.
At C:\xRMCIFramework_8.0.17\ExportSolution.ps1:84 char:32
+ ... nagedFile = Export-XrmSolution -ConnectionString "$CrmConnectionStrin ...
    + CategoryInfo          : NotSpecified: (:) [Export-XrmSolution], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Xrm.Framework.CI.PowerShell.Cmdlets.ExportXrmSolutionCommand

Ps : I am trying to export the Default Solution to use it as our code version base template.

**Comment by eNeRGy164** [comment]
Do you have the right region in your URL? (.crm3. or .crm4., etc..)

**Comment by phuocle** [comment]
Are you running on PROXY ?

**Comment by WaelHamze** [comment]
You are missing the AuthType in your connection string:
https://msdn.microsoft.com/en-us/library/mt608573.aspx

AuthenticationType or AuthType
Specifies the authentication type to connect to Dynamics 365 instance. Valid values are: AD, IFD (AD FS enabled), OAuth, or Office365.
AD and IFD are permitted for Dynamics 365 on-premises instances only.
OAuth is permitted for Dynamics 365 (online) and on-premises instances.
Office365 is permitted for Dynamics 365 (online) instances only.

Have fun with the automation :)
