### ISSUE TITLE
AppModules not processed correctly for PackageType:Both

### ISSUE THREAD

**Issue by mattp65** [WaelHamze/xrm-ci-framework#181]
Just rainsing awareness to a bug in Solutionpackager.

When Extracting a solution containing an AppModule using PackageType:Both, the same filename is used for the resulting extracted XML. As a result, the Unmanaged solution when Packed will not work as the AppModule XML is not complete.

This has been reported to Microsoft.

**Comment by WaelHamze** [comment]
@mattp65 thanks for flagging, I guess the only work around for now is to push managed/unmanaged into separate folders

**Comment by WaelHamze** [comment]
I believe this has been fixed with latest SDK. This has been released to marketplace
