### ISSUE TITLE
CI/CD and solution patches

### ISSUE THREAD

**Issue by FixRM** [WaelHamze/xrm-ci-framework#185]
Hello @WaelHamze,

Do you have any ideas on how can we (or should we?) integrate solution patches feature in CI/CD pipeline? For now we use monolithic solution and it works well. It is also clear how to build a "hot fix" branch to deliver some urgent fixes to production. But as for now, our hot fix is just another version of the same monolithic solution so it requires several dozens of minutes to install (our async service is on fire).

The main question is how to have complete "main" version on one hand and be able to produce (and store somewhere in repo I guess?) the patches we want to build on the other hand?

**Comment by bwmodular** [comment]
I'd be really interested in this as well - we've been trying to work out how to integrate solution patches into CI, but we've not found a way of doing this. The MS tooling (Solution Packager) doesn't really seem to support this.

**Comment by Bakanych** [comment]
We eventually came up with idea to split solutions into smaller ones. Import time was the one of the main reasons to do that.

**Comment by jordimontana82** [comment]
Same, we splitted solutions per area / sprint and then per subcomponent type to keep releases small.

**Comment by phuocle** [comment]
and the solution is unmanaged ?

**Comment by WaelHamze** [comment]
@FixRM @bwmodular if you use managed solutions, you could have an alternative route to live for hotfixes, that is deploying  small patches solution, these then get merged back into the main solution in the subsequent bigger release, I have been thinking of adding additional option in the import task, this would allow you to specify a list of solution/patches using a json file.

@bwmodular did you try to run solution packager on the patch itself? Eventually these will be merged into one solution and can be deleted from source.

**Comment by WaelHamze** [comment]
@FixRM 

I think any branches should be short lived. You can spin up a branch off master to work on your patches, Ideally you would want to merge these changes back into master as soon they go into prod. I can see the patch branch ending when the next release is happening and you clone the solution into the next version.

But agree the patches should be with the main CRM repo.

Also not sure you can assume every patch will contain the plug-ins and web resources, sometimes it only be some minor configuration changes.

How many patches do you expect to do between major releases?

**Comment by bwmodular** [comment]
Thanks all for interesting replies. 

Main issue for us, I think, is the lack of support in the Software Developer toolkit. We use this to manage import/unpack of solutions from Dynamics into Visual Studio and from what we've been able to work out it can only support one main solution and it doesn't really allow you to work with patches. 

We have a good CI workflow established using the Software Developer Toolkit but there's not really any official support for it and it's been in public beta since it's re-release a couple of years back, so not expecting any changes there unfortunately.

**Comment by jordimontana82** [comment]
@bwmodular we've been using powershell scripts (that use Wael's export and unpack PS scripts behind the scenes really) to unpack solutions from a CRM environment into our local machines, that we then push into the appropiate branch in source control using VS / git (we basically have only 2 long lived branches: master and dev, any other branch (hotfix or parallel dev stream) are deleted as soon as they're merged into master / dev.

To be honest, I agree with you Ben, given there hasn't been much maintenance going on in the dev toolkit for so long..., that was the easiest option that worked really nice for us.

**Comment by FixRM** [comment]
@bwmodular, @jordimontana82 
we now use Scott Durow's https://github.com/scottdurow/SparkleXrm/wiki/spkl to automate dev process. It's not ideal but it free, open, works well and support solution packager as well.

**Comment by jordimontana82** [comment]
I've been using Wael's Xrm CI framework to unpack stuff into source control with mapping files (in .xml as opposed to .json) it's also open and free so essentially the same thing in terms of unpacking stuff.

I think with one of the latest versions you can also use configuration in .json too @WaelHamze  ?

**Comment by FixRM** [comment]
First of all, I appreciate the work @WaelHamze is doing! I just found myself too weak in PowerShell to automate dev side of packing/unpacking/publishing changes using this toolkit. I provided other solution only because @bwmodular is talking about Dev Toolkit, so I believe he is looking for most simple solution. Sorry if I hurt someone.

**Comment by jordimontana82** [comment]
No worries! Was just curious :)

**Comment by mattp65** [comment]
We have been moving to a hybrid approach as well that leverages SPKL to support some the dev side work that directly faciliates the day to day dev workflow with the CI Framework focusing on the "build" process. Basically using each tool where it fits our process best. 

Each tool has it's strong point and we try to focus our use on which is the best choice for what we need to do. The 2 tools definitely have some overlap, but they grew from different perspectives and thus each does some things the other doesn't. 

I think the key with adopting Open Source tools like these is to try to minimize how many you use, but knowing that you probably won't find 1 tool that does everything you want. Even if you were to try some of the "commercial" dev tools out there you would find they have gaps and you end up looking to other tools to fill those gaps. These 2 really seem to complement each other though.

**Comment by FixRM** [comment]
@mattp65, that's for sure! We use same tool chain. But, after all the original question was about workflow, not the tools.

@WaelHamze, this make sense to me, thanks. I figured out that it looks impossible to have patch and corresponding main solution in the same commit as they share their code base. If I want to build some particular "v8 + update 2", I have to sequentially checkout and build "v8", "update 1 for v8" and "update 1 for v8". This is so for any branch model, I guess.

**Comment by michsob** [comment]
We are using similar approach. We have config file in main folder of repository that contains list of CRM solutions. This can be updated in feature branches. Build triggered on merge to master is using this file to export solutions with Xrm.CI.Framework.
