### ISSUE TITLE
[REQUEST] Need VSTS Tasks

### ISSUE THREAD

**Issue by phuocle** [WaelHamze/xrm-ci-framework#19]
Please support these tasks
- Update Plugins
- Update WebResources

**Comment by phuocle** [comment]
I have done with 2 powershell script

[Uploading Request.VSTS.Tasks.zip…]()

**Comment by WaelHamze** [comment]
@phuocle thanks for suggesting these tasks.

Do you use the developer toolkit by any chance? I mean are you looking to perform the deploy action from the developer toolkit or you want to update specific web resources and plug-ins?

**Comment by rappen** [comment]
I guess this request might possibly be inspired by my recent articles on the subject...?

**Comment by phuocle** [comment]
@rappen YES. Thanks for a great posts. I'm looking on VSTS 2 days and now you can see my build here.

![2017-04-26_15h37_58](https://cloud.githubusercontent.com/assets/479729/25440116/a50a4746-2ac8-11e7-8c8e-eea65bc1645e.png)

Everything now with 1 click from **DEV** to **QA** then **UAT** then **PRO**

For Update Plugins, and WebResources I can archived it by PowerShell scripts. (attached files)

So I request this because I think maybe another developer can use it later. (or I can use it later for a feature projects)

For me, everything now ok with my PowerShell scripts

**Note:** Set-WebResources.ps1 use **CRMDeveloperExtensions.config** mapping file from @jlattimer **CRMDeveloperExtensions** tool

[PowerShell.zip](https://github.com/WaelHamze/xrm-ci-framework/files/958848/PowerShell.zip)

**Comment by jordimontana82** [comment]
Well done @phuocle  ! :)

**Comment by WaelHamze** [comment]
@phuocle thanks for sharing, will take a look and make a task out of it :)

**Comment by devkeydet** [comment]
Any progress?  I was looking for a way to automate the Secure Configuration of a plugin as part of a release.  It sounds like this task you are considering building might do the trick.

**Comment by WaelHamze** [comment]
You could also consider using this: https://github.com/scottdurow/SparkleXrm/wiki/spkl

**Comment by devkeydet** [comment]
I do :)  Love it.

**Comment by WaelHamze** [comment]
@phuocle I am looking at the PowerShell Scripts you shared. For updating plug-in assembly. I take it you are just updating assembly, but where do you keep track of the steps etc...? I take it that is managed in the development environment?

**Comment by phuocle** [comment]
@WaelHamze I changed the PowerShell script above to #spkl with some changes from the original #spkl

**Comment by scottdurow** [comment]
@WaelHamze Maybe we could integrate #spkl into the xrm-ci-framework for some tasks?
@phuocle What did you need to change - pull request?

**Comment by WaelHamze** [comment]
@scottdurow I am keen to add some more capabilities around CI into the tasks. Publishing plug-ins and web resources is one of them. Do you think spkl can support generating steps/images into a json file as an alternative to tagging classes at design time? (I am thinking would be useful if you have a re-usable plug-in like auditing you want to use across many projects and you may want to register on different entities depending on the project/target)

**Comment by scottdurow** [comment]
For sure - it would be in the spkl.json, the same as the web resources - but I'd expect the more usual route would be to use the plugin assembly to define the steps.

**Comment by WaelHamze** [comment]
@scottdurow sounds good. Will take a look. It should be easy to wrap this up in a task.

**Comment by WaelHamze** [comment]
@phuocle @scottdurow 

After some consideration, seems like the tasks to update plug-ins and web resources will always have some dependency on how developers manage these things in source control and visual studio IDE.

There are many options like Developer Toolkit, SPKL, Developer Extensions, PowerShell. Each of these will manage definition of plug-in types, steps, images and web resource mapping differently.

I am trying to create some tasks that are generic enough to be used independent of development tool (as much as possible).
I normally use the solution packager so don't require these tasks in the build.

For Plug-ins I could easily just update the assembly. Anything on top of that would require some agreed contract/file for types/steps/images.
For Web Resources I would need a mapping which will be dependent on the developer tool.
I could wrap SPKL in task but it is easy enough to use on its own and would require the developer to use that too.

Let me know your thoughts :)

**Comment by Bakanych** [comment]
It will be nice to start with simple ones, like just to update plugin dll and its version. Please also take a look at these tasks:
https://marketplace.visualstudio.com/items?itemName=InnofactorSE.cinteros-devutils-ci-build-tasks

**Comment by jordimontana82** [comment]
I'd be in line with what @scottdurow was suggesting. I think it's handy to manage the plugin registration settings directly from within the plugin source code. 

One of the things we could add also to FakeXrmEasy would be the ability to automatically mock the fake plugin / code activity context based on those parameters really. It would make unit testing even more easier.

**Comment by WaelHamze** [comment]
@Bakanych  Thanks I am familiar with that project.

There is now a task to update the plug-in assembly and web resources. If anyone is interested in taking a look at the preview please get in touch and let me know your VSTS account and I will share with you the preview.

**Comment by Bakanych** [comment]
Hi @WaelHamze , having json for plugin registration settings also as reference to FakeXrmEasy would be dream solution!
I would try and test preview versions of update tasks with pleasure, but we use TFS 2018 onprem. How can we manage it?

**Comment by Bakanych** [comment]
Btw can we keep this issue opened? It's the most wanted enhancement at least for me :)

**Comment by WaelHamze** [comment]
@Bakanych if you create a VSO online account I can share it with you. You should be able to download it from there.

**Comment by WaelHamze** [comment]
This is now live on the marketplace. I will close this task. Let's open a specific new issue for any enhancements or issues required.
