### ISSUE TITLE
Getting "Exit code 5 returned from process" when packing solution in TFS onpremise

### ISSUE THREAD

**Issue by scubaracer** [WaelHamze/xrm-ci-framework#197]
When packing our solutions i get "Exit code 5 returned from process" and the task failes, but i see the info message of the package tool that de solution is packaged "Managed Pack complete.". This occures with v10 of the task, v9 gives no errors. As far as i know v10 was fine a week before.

**Comment by WaelHamze** [comment]
@scubaracer I think this is same as this issue https://github.com/WaelHamze/dyn365-ce-vsts-tasks/issues/49

Try on latest update from marketplace: https://marketplace.visualstudio.com/items?itemName=WaelHamze.xrm-ci-framework-build-tasks

**Comment by scubaracer** [comment]
Sorry i did not see that one, your correct!
