### ISSUE TITLE
tfx extension create --manifest-globs vss-extension.json path problem

### ISSUE THREAD

**Issue by clc136** [WaelHamze/xrm-ci-framework#2]
This looks to be a great toolkit. However I do have a problem creating the vsix unless the tasks are below the extension folder, unless you have a workaround? Thanks

**Comment by WaelHamze** [comment]
I am moved the files around actually. I need to do a bit more testing before I push. I am also in the process of publishing this on the market place so you can get it from there.

**Comment by WaelHamze** [comment]
Take a look at the latest push. You just compile the solution in Release mode and then run this PowerShell Script: xrm-ci-framework/CRM365/Xrm.Framework.CI/PackageFramework.ps1

Everything you need should be created in the bin folder :)

xrm-ci-framework/CRM365/Xrm.Framework.CI/bin (this folder is only available locally)

**Comment by clc136** [comment]
Hi, as per your suggestions I have used the latest push to successfully release build and after unblocking PackageFramework.ps1 run this to create the VSIX. I was surprised to see this was nearly 6Mb and after changing the extension to ZIP was able to see that the ps_modules folder and contained xRMCIFramework and VstsTaskSdk folders are replicated for each build task - is this what you would expect? Eventually I'd like to extend with more build tasks like updating solution version etc. I also have a big PS that copies databases between environments, updates settings entity records, obfuscates data etc. but I'd like to componentise this using build tasks. Thanks, Chris

**Comment by WaelHamze** [comment]
Hi Chris, Glad you are able to build this. Here are my thoughts.
1- Size: I guess if you want to make the tasks very portable and not have a dependency on having to pre-configure the build server especially with hosted then I can't see how we could optimise this without adding much complexity. I would assume the build service is/will cache the tasks locally and load any new versions if available. Also gives the flexibility to have two tasks using different versions as needed.
2- Solution version: You are currently able to do with as part of the export or pack task. Do you see other scenarios where you would need to do that independently?
3- Other tasks: If you think any of your future tasks can be generic and would benefit other I suggest you create a fork and then we can pull this back into the main branch and make it available to others.  Would be great to see others contributing into this.

**Comment by clc136** [comment]
Hi Wael, I wonder if you can shed any light on this build error please. Here we have 2 build servers and each has a pool of a few agents. If we RDP into each build server we can see the tasks deployed to the agent but it seems like either there's a timing issue or TFS is trying to run the build on the 'other' server???

The term 'C:\TFSBuild\agentB\tasks\MSCRMPing\8.0.0\ps_modules\xRMCIFrameworkCI\Ping.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by WaelHamze** [comment]
I think you are using an old version of the task. Please get the latest. I fixed this issue. the path was incorrect in the task

**Comment by clc136** [comment]
Thanks, I thought I had updated it. I have Ping working now :-)

**Comment by clc136** [comment]
N00b question: Making some progress but find I need a MSCRMUnPackSolution task that maybe could be cascaded on the MSCRMExportSolution. Guess this would not be hard to do? Looked at your ExtractCustomizations.ps1 but would need to figure passing in full path to the SolutionPackager.exe in the repo bin I guess? Thanks

**Comment by WaelHamze** [comment]
That depends on your process. I have decided not to include the UnPack task for the below reasons.
-I believe unpack should be done locally by the developer who is working on the user story locally after completing the work. Then these changes can be checked-in to source
-There may be conflicts and error arising from unpack that have to be handled manually
-Build automation should be about taking source and producing packages. Unpacking seem to be more like generating source.
-Checking in during a build could lead to other complexity and manual resolutions due to locked files etc...

**Comment by clc136** [comment]
Hi Wael, there are a diversity of valid methodologies for development processes that require flexible approaches, including using CRM solutions as source snapshots (excluding compiled code). We have a number of situations using only unmanaged solutions where UnPack is valuable like differencing and (partial) rollback and it is convenient to be able to trigger from TFS and store on the server in a special repo.
