### ISSUE TITLE
Connection to multiple CRM organizations from single script

### ISSUE THREAD

**Issue by michsob** [WaelHamze/xrm-ci-framework#200]
Hi,

In powershell script triggered from ADO I'm trying to connect to two different organizations - DEV and UAT. Based on my tests Xrm.CI.Framework connects only to the first organization. When running i.e. Get-XrmSolution with connection to second organization, cmdlet connects to first organization. Tested with Dynamisc 365 v9.

When I connect to single organization there is no issue with connection. Example connection strings:
"AuthType=Office365;Username=username;Password=pwd;Url=https://companydev.crm11.dynamics.com"
"AuthType=Office365;Username=username;Password=pwd;Url=https://companyuat.crm11.dynamics.com"

Is there a way to reset connection to CRM organization? Or should Xrm.CI.Framework reset connection when new connection string provided automatically in the first place?

Thanks for all your work!

**Comment by bwmodular** [comment]
Hi @michsob, there's a parameter you need to add to the connection sting which prevents the connection being retained between calls.
Add this to your connection string: _RequireNewInstance=True;_

Hope that helps,
Ben

**Comment by michsob** [comment]
@bwmodular Thanks a lot. This resolved my issue!
