### ISSUE TITLE
Does Xrm.Framework.CI.PowerShell.Cmdlets work on Ubuntu ?

### ISSUE THREAD

**Issue by nobspulsar** [WaelHamze/xrm-ci-framework#202]
Hi,
I have created a deployment script which works perfectly fine on Windows server. But the same doesn't work on Ubuntu server (Azure VM). Wonder whether the XRm framework is compatible on Linux or not ? As well in the tag, the supported OS are not shown either

Ubuntu Version :  16.04.5
PSVersion        :       6.1.0

Errors
-------

PS >Get-XrmSolution -ConnectionString $Connection -UniqueSolutionName Base_Solution

Get-XrmSolution : Could not load file or assembly 'System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
At line:1 char:1
+ Get-XrmSolution -ConnectionString  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-XrmSolution], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Xrm.Framework.CI.PowerShell.Cmdlets.GetXrmSolutionCommand

PS >  Get-XrmSolutionImportLog -ImportJobId 65418a20-2366-43ee-8a9d-8207a4348523 -ConnectionString $Connection 

Get-XrmSolutionImportLog : Could not load file or assembly 'System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
At line:1 char:1
+ Get-XrmSolutionImportLog -ImportJobId 65418a20-2366-43ee-8a9d-8207a43 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-XrmSolutionImportLog], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Xrm.Framework.CI.PowerShell.Cmdlets.GetXrmSolutionImportLogCommand

**Comment by WaelHamze** [comment]
@nobspulsar it is not compatible as the libraries it depends on can only be used on windows

**Comment by nobspulsar** [comment]
Thanks, @WaelHamze
