### ISSUE TITLE
Export-XrmSolution : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Nou8** [WaelHamze/xrm-ci-framework#203]
I am getting this error when I try to export a CRM solution..

Any help?

Thanks

**Comment by WaelHamze** [comment]
@Nou8 check your connecting string format: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/xrm-tooling/use-connection-strings-xrm-tooling-connect

Ensure machine where powershell is running has a network line of site to your CRM instance. I would try the ping cmdlet first
