### ISSUE TITLE
9.0.0.37/38 MissingMethodException (MaxConnectionTimeout)

### ISSUE THREAD

**Issue by TheBrandt** [WaelHamze/xrm-ci-framework#206]
I'm not sure if this is an issue on my end or not, but I'm receiving a MissingMethodException ever since 9.0.0.37 release:

````
Method not found: Void Microsoft.Xrm.Tooling.Connector.CrmServiceClient.set_MaxConnectionTimeout(System.TimeSpan).
At
+                 Get-XrmPluginRegistration `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-XrmPluginRegistration], MissingMethodException
    + FullyQualifiedErrorId : System.MissingMethodException,Xrm.Framework.CI.PowerShell.Cmdlets.GetXrmPluginRegistrationCommand
````
Is there a configuration I should be doing? Or the package somehow missing an updated assembly?

**Comment by majakubowski** [comment]
@WaelHamze @TheBrandt this regards PR #204 .. this exception occurs when I was using Microsoft.Xrm.Tooling.Connector in version older than 9.0.2.7.. i.e. mixing different versions in projects Xrm.Framework.CI.Common & Xrm.Framework.CI.PowerShell.Cmdlets. Make sure you have this assembly in this version or higher (the latest version is 9.0.2.12).

**Comment by TheBrandt** [comment]
I tried fixing this by installing https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.CoreAssembly/ , but I'm still getting the same error.  I might have to double check my working paths, though.

**Comment by WaelHamze** [comment]
@TheBrandt @majakubowski both of the projects are using the latest version of the SDK, do you think any changes are required in code?

**Comment by ThinkAboutGitHub** [comment]
Did this ever get resolved?

**Comment by TheBrandt** [comment]
Unfortunately, after fiddling around with paths and packages for a few hours, I was still staring at the same error messages. So in the end I just decided to revert to version 36 for the time being. I haven't had the time to look into this issue since then.

**Comment by ThinkAboutGitHub** [comment]
Maybe i'll try that, i can't get my build server past this error

**Comment by ThinkAboutGitHub** [comment]
This error still occurs for me for version 9.0.0.39

**Comment by WaelHamze** [comment]
This should be working now, please re-open if any issues
