### ISSUE TITLE
Provision an CDS instance using a service account with P2 license

### ISSUE THREAD

**Issue by lheng18** [WaelHamze/xrm-ci-framework#207]
@WaelHamze Does your Provision Instance Task work with creating a CDS environment? I got 
"Operation returned an invalid status code 'Forbidden'" error. Thanks a lot.

**Comment by WaelHamze** [comment]
@lheng18 do you have "Dynamics 365 Service Admin" role?

**Comment by lheng18** [comment]
@WaelHamze I don't have but we can use a service account to do so but we don't want the credentials to be stored in the pipeline in masked variable as other project members could clone the pipeline and reuse the variable to do other things as  the user has very high permission and it can reset production. Is there anyway we can prevent user from reusing the service account credentials? If not  we would have to either put provision environment build task in a centralize project pipeline or create a flow to Rest API to wrap the MS admin API with stored credentials then have the pipeline to call it and we would need to think about how to secure the Rest API and Flow to only allow certain pipelines to invoke it.

Any suggestions?

Thanks!
Henry Luo

**Comment by WaelHamze** [comment]
@lheng18 

There are permissions you can apply to libraries and pipelines to either grant/deny access to users as required. You could also store credentials in the Azure KeyVault.

Please check this but as far as I know cloning doesn't clone secrets.
