### ISSUE TITLE
Question about permissions [help]

### ISSUE THREAD

**Issue by DineshNanayakkara** [WaelHamze/xrm-ci-framework#208]
Hi @WaelHamze ,
First of all, thank you for your time for creating this tool. I am trying to setup the CI/CD pipeline for my organisation. To give some background about my working environment. We are using: 

- Dynamics 365 CE online 
- Azure AD for user management (MFA is enabled)
- Using BitBucket as our source control repository

I got a couple of questions since I ran into issues with connectivity.

1. 
What permission is requrired on my account (e.g. Global admin rights/ service  #administrator,...etc)

2.
Does this tool support MFA or should I use a service account (non interactive) ?

Thanks in advance.

### PS.
I am getting the following error when I tried "Get online instance by name"
##[section]Starting: MSCRM Get Online Instance By Name
==============================================================================
Task         : MSCRM Get Online Instance By Name
Description  : Gets an Online instance ID based on the name of the instance.
Version      : 10.0.1
Author       : Wael Hamze
Help         : This task uses the Microsoft.Xrm.OnlineManagementAPI: https://www.powershellgallery.com/packages/Microsoft.Xrm.OnlineManagementAPI
==============================================================================
##[error]Operation returned an invalid status code 'Forbidden'
##[section]Finishing: MSCRM Get Online Instance By Name

**Comment by WaelHamze** [comment]
@DineshNanayakkara 

For managing the instances you will need "Dynamics 365 Service Admin"

MFA is not supported

**Comment by DineshNanayakkara** [comment]
@WaelHamze,
Thank you for the response.
Is there a future plan to implement MFA as part of this tool?

Thanks.
