### ISSUE TITLE
Provision is not updating the status

### ISSUE THREAD

**Issue by aboodh95** [WaelHamze/xrm-ci-framework#209]
Hi,

I'm trying to use the Provision task, it's returning as Succeeded and the instance is being created, but it's not existing the task, it will be stuck in it and it will not go to the next one 
![image](https://user-images.githubusercontent.com/12459798/56273389-b293a380-610d-11e9-95f3-017301593df7.png)

**Comment by WaelHamze** [comment]
@aboodh95 once the operation returns, the task queries the API to try to retrieve the instance and check the state again. Was your instance created with the same name as requested? Sometimes if name is already take an instance is created with '0' in the end. Also did you check in portal if instance was ready?

**Comment by aboodh95** [comment]
@WaelHamze, yes, the instance was created with the same name i tried and it was ready

**Comment by aboodh95** [comment]
I make a quick fix by unchecking the Wait For Completion and then added a wait task for 10 min, the operation for sure will be completed as I'm creating an empty instance and then I will restore a backup to it

**Comment by WaelHamze** [comment]
@aboodh95 I will add some additional logging in the next release so you can see what is going on while it hangs, once you check we can make any adjustments if neeeded

**Comment by aboodh95** [comment]
Okay, Thank you so much

**Comment by WaelHamze** [comment]
This should be working now, please re-open if any issues
