### ISSUE TITLE
Support for Images on ServiceEndpoint steps?

### ISSUE THREAD

**Issue by ryanmichaeljames** [WaelHamze/xrm-ci-framework#210]
Hey

Are you planning supporting the registration of images against service endpoint steps?

Thanks,

**Comment by ryanmichaeljames** [comment]
I've created pull request #213 to support this.

**Comment by WaelHamze** [comment]
This has been released

**Comment by ryanmichaeljames** [comment]
Awesome. Thanks mate! 😎
