### ISSUE TITLE
Import-XrmSolution -ConvertToManaged parameter not converting Unmanaged solution to Managed

### ISSUE THREAD

**Issue by mpavlino** [WaelHamze/xrm-ci-framework#215]
Hi @WaelHamze,

When I import crm solution via Imort-XrmSolution command in PowerShell and set ConvertToManaged parameter to $true, it doesn't convert my solution to managed. I am importing unmanaged solution and as it says in documentation, it should convert solution to managed. Am I missing something?

Thank You
Mirko

**Comment by WaelHamze** [comment]
@mpavlino I don't believe this would convert the solution to managed, I think this is used when importing a managed solution and certain unmanaged customizations are present in the system. In certain cases these should be converted to managed. I would recommend you try this out on different components and I believe most of them are not supported for this action.

**Comment by fowl2** [comment]
I imagine this corresponds to the [ImportSolutionRequest.ConvertToManaged Property](https://learn.microsoft.com/dotnet/api/microsoft.crm.sdk.messages.importsolutionrequest.converttomanaged).

> Direct the system to convert any matching unmanaged customizations into your managed solution. Optional.

Important part there is *matching* customizations.

see also: [Moving from unmanaged to managed solutions in your organization](https://learn.microsoft.com/power-platform/alm/move-from-unmanaged-managed-alm).
