### ISSUE TITLE
Error using ExportSolution.ps1

### ISSUE THREAD

**Issue by DaveKLloyd** [WaelHamze/xrm-ci-framework#22]
I am trying to use the 2015 version of your Powershell scripts to create a build and Deploy for our CRM implementation. 

I am getting an error and I can’t seem to work out what is causing it. 

I am trying to call the Powershell script ExportSolution.ps1

Here is the output:
CrmConnectionString: Username=<ACCOUNT>;Password=<PSWD>;Domain=<DOMAIN>;Url=https://<Server>/NBCRMDEV;
SolutionName: COMPASSDevelopment
ExportManaged: 0
ExportUnmanaged: 1
ExportSolutionOutputPath: C:\temp
ExportIncludeVersionInSolutionName: 1
ExportAutoNumberingSettings: 0
ExportCalendarSettings: 0
ExportCustomizationSettings: 0
ExportEmailTrackingSettings: 0
ExportGeneralSettings: 0
ExportIsvConfig: 0
ExportMarketingSettings: 0
ExportOutlookSynchronizationSettings: 0
ExportRelationshipRoles: 0
Script Path: D:\Dlloyd\CRM\CRM2015\Xrm.Framework.CI\Releases\xRMCIFramework_7.1.0.0\PowerShell
Importing CIToolkit: D:\Dlloyd\CRM\CRM2015\Xrm.Framework.CI\Releases\xRMCIFramework_7.1.0.0\PowerShell.\Xrm.Framework.CI.PowerShell.dll
Imported CIToolkit
Select-WhoAmI : Object reference not set to an instance of an object.
At D:\Dlloyd\CRM\CRM2015\Xrm.Framework.CI\Releases\xRMCIFramework_7.1.0.0\PowerShell\DeployExportSolution.ps1:58 char:18
+ $executingUser = Select-WhoAmI -ConnectionString $CrmConnectionString
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Select-WhoAmI], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Xrm.Framework.CI.PowerShell.Command.SelectXrmWhoAmICommand 

Any help appreciated thank you.

**Comment by eNeRGy164** [comment]
Don't forget the organization name in the url and probably also the AuthType

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DaveKLloyd** [comment]
Great thanks for the help. That certainly got us further along. I already had organization name but was missing AuthType. We added **AuthType=IFD**; to the connection string and got past the last error. However now we get the message:  Select-WhoAmI : The user authentication failed!

The credentials in the connection string is a sysadmin in CRM.

**Comment by DaveKLloyd** [comment]
IN case this helps, We have used the connection string with the same credentials in the XRMToolbox and it works fine. 
We also tried the powershell script with the Developers credentials and we get the same error.

**Comment by eNeRGy164** [comment]
Besides explicitly stating the domain name, make sure the user is in the form of user@domain
It's stupid, but makes it work for me.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DaveKLloyd** [comment]
Going back to the original script from GIT without my changes to try and get this working. We are getting this error.:

Select-WhoAmI : The specified user credentials are invalid. 

_At D:\agentServices\BuildAgent01\_work\104\s\ExportSolution.ps1:55 char:18 
+ $executingUser = Select-WhoAmI -ConnectionString $CrmConnectionString 

+ CategoryInfo : NotSpecified: (:) [Select-WhoAmI], ConfigurationErrorsException 
+ FullyQualifiedErrorId : System.Configuration.ConfigurationErrorsException,Xrm.Framework.CI.PowerShell.Command.SelectXrmWhoAmICommand_

**Comment by DaveKLloyd** [comment]
Michael... I really appreciate this help. Thank you. 

I tried putting the Domain after the user id and still get the same error.

**Comment by DaveKLloyd** [comment]
I am not a CRM expert so I am a bit confused. Our connection string looks like this. 
"Username=User@company.com;Password=Password;Domain=NBCRMDEV;AuthType=IFD;Url=https://machine.company.com/NBCRMDEV;"

The Domain attribute in this case refers to an instance of CRM on the machine right? When you say add the domain to the user you do mean the AD domain?

I just want to be clear and make sure I am not missing some CRM thing I don't know about. 

Mind you as I mentioned before the connection string works fine when we use it in XrmToolKit

**Comment by eNeRGy164** [comment]
Domain is the user accounts domain, as far as I know. All IFD machines I use have the same domain for the server as for the user, so I'm not sure.

In my case it is "Username=User@company.com;Password=Password;Domain=company.com;AuthType=IFD;Url=https://organization.company.com/organization"
We create a DNS record for every organization, and have multiple organization per machine.

Because it works in the XrmToolkit it can be that they take the domain part from the userstring, or that they ignore or autofill other parts.
An other option is that your password contains special characters like a ` (backtick), $ or &? These are special characters in PowerShell and might be problematic.

**Comment by DaveKLloyd** [comment]
I changed my Connection String to be the same as you described above. The only thing I'm not sure about is the URL I have "**https://MachineName.company.com/Organization**" Is it just a coincidence that your machine name is the same as the Organization? 

I am still getting this error:  **Select-WhoAmI : The specified user credentials are invalid.**

**Comment by WaelHamze** [comment]
If you are using the 2015 version the connecting string follows the format described here: https://msdn.microsoft.com/en-us/library/gg695810(v=crm.7).aspx

**Comment by DaveKLloyd** [comment]
Thanks for the help. I have checked and double checked my connection string, it seems fine. It works in other situations. However I can't get past the call to **Select-WhoAmI** at the moment I am getting this error: _**An unsecured or incorrectly secured fault was received from the other party**._ 

This is the PowerShell I am running. 

[string]$CrmConnectionString = "Url=https://CRMserver.company.com/instance; Domain=company.com; Username=user@company.com; Password=password;"
$scriptPath = split-path -parent $MyInvocation.MyCommand.Definition
Write-Host "Script Path: $scriptPath"
$xrmCIToolkit = $scriptPath + "\Xrm.Framework.CI.PowerShell.dll"
Write-Host "Importing CIToolkit: $xrmCIToolkit" 
Import-Module $xrmCIToolkit
Write-Host "Imported CIToolkit"
write-host $CrmConnectionString
$executingUser = Select-WhoAmI -ConnectionString $CrmConnectionString
Write-Host "Executing User Id" $executingUser.ToString()

**Comment by WaelHamze** [comment]
Are you using a valid certificate on your CRM instance? you may need to add the root certificate to the trusted store on the machine you are running the scripts.

**Comment by DaveKLloyd** [comment]
I have asked about the certificate, waiting to hear. I have talked to our CRM experts (I am the DevOps/ALM resource. So I am relying on their CRM expertise.) 
I am told the connection string I am using works for other tools used to connect. And the user has the correct rights in CRM. At the moment I am just trying to get past calling Select-WhoAmI. See above post.
Currently we are getting this error message: **Select-WhoAmI : The user authentication failed!**

**Comment by WaelHamze** [comment]
Any luck with this? The framework is calling the standard SDK assemblies that other tools would be using too.

**Comment by DaveKLloyd** [comment]
No not yet. :( 
I have one of the network guys coming around when he gets a chance to check into it for me. I assume it's the setup or configuration of the network or CRM here. If we come up with a solution I will be sure to post it here.

**Comment by DaveKLloyd** [comment]
I have discovered something however I am not sure what to do with the information. 

At the moment when I run this:
``[string]$crmConnectionString = "Url=https://server.domain.com/DEV; Domain=domain; Username=domain\userid; Password=password; AuthType=IFD; RequireNewInstance=True;"
$scriptPath = split-path -parent $MyInvocation.MyCommand.Definition
$xrmCIToolkit = $scriptPath + "\Xrm.Framework.CI.PowerShell.dll"
Import-Module $xrmCIToolkit
$executingUser = Select-WhoAmI -ConnectionString $CrmConnectionString``
I get the error: **The user authentication failed!**

I wrote a C# app that makes the same call, and got the same error. 
Upon inspection of the connection object we noticed **connection.ClientCredentials.UserName.UserName** and **connection.ClientCredentials.UserName.Password** were null. 
We filled them in with the same credentials as in the connection string and the SelectWhoAmI worked. 

If these are required why does the Parse method on the CRMConnection not pull them out and set the UserName object on ClientCredentials. or what do I have to set in the connection string to get these this to work. 

Dave

**Comment by DaveKLloyd** [comment]
The problem was the Domain. There is code in CRMConnection

**Comment by WaelHamze** [comment]
I was about to respond. What is the final connection string that works?

**Comment by DaveKLloyd** [comment]
The working connection string is:
``"Url=https://server.domain.com/DEV; Username=domain\user; Password=password; AuthType=IFD; RequireNewInstance=True;"

**Comment by WaelHamze** [comment]
Excellent. Thx for sharing and really glad you got it working in the end.
