### ISSUE TITLE
MSCRM Import Solution Task

### ISSUE THREAD

**Issue by missdynamicscrm** [WaelHamze/xrm-ci-framework#225]
Hi, 

The MSCRM Import Solution is stuck on this status for 3 hours:
Waiting for console output from an agent...

But the Solution has been imported succesfully.
It then makes me cannot continue the another task.

Any idea?

Thanks

**Comment by WaelHamze** [comment]
@missdynamicscrm not sure why it is stuck will need to see the logs,

You can always cancel and re-run the pipeline, if you don't have the override option set, it should skip the import as version will be same.
