### ISSUE TITLE
Terms of build in Dynamics 365

### ISSUE THREAD

**Issue by aboodh95** [WaelHamze/xrm-ci-framework#226]
Hi,

I have some questions, for the Dynamics 365 build logic, I will prepare the dev environment, update the Web Resource, make sure the plugin updated, and everything is good, now I will export the solutions, now the step of importing them in the Test environment is this should be done in the Build, and to production in the Release, another question, on the XrmToolCast you mentation number of Testing tools that can assist you in testing your work, UI, logic, etc., can you provide the names.
Thanks

**Comment by WaelHamze** [comment]
@aboodh95 I would always package/export solutions in build and deploy them in releases (including any test env).

as for testing...

Below are a few links

https://dynamicsvalue.com/home

https://github.com/microsoft/EasyRepro
