### ISSUE TITLE
How to set localize flag for packaging?

### ISSUE THREAD

**Issue by ygizhitsa** [WaelHamze/xrm-ci-framework#229]

**Comment by WaelHamze** [comment]
@ygizhitsa can you please provide more details on what you are trying to do?

**Comment by WaelHamze** [comment]
@ygizhitsa will the above commit fix your issue?

Do you need the localize flag on the pack?

**Comment by ygizhitsa** [comment]
Yes, the current ps line I'm running is following
& $packagerPath  /action:Pack /PackageType:$PackageType /folder:$folder  /zipfile:$FileName  /map:$MappingFileName  /localize /sourceLoc:1033.

The packegerPath I'm extracting from Tools installer 

$packagerDirectory = (Join-Path -Path ($env:MSCRM_Tools_Path)  -ChildPath "CoreTools\9.0.0" )
$packagerPath = (Join-Path -Path ($packagerDirectory)  -ChildPath "SolutionPackager.exe" )

Thank you for responding 
Yuriy

**Comment by WaelHamze** [comment]
@ygizhitsa ok added that too should be available in next release

**Comment by ygizhitsa** [comment]
I just was able to build a package with localize flag on and source 1033. The package is built. There are some worming messages I would need to research and make sure that package has been successfully deployed and tested. Will keep you updated. If it works, I will start to clean pipelines with custom PS script
![image](https://user-images.githubusercontent.com/16059989/63965216-aa0d8b00-ca66-11e9-811b-1e063c9f6a4e.png)

![image](https://user-images.githubusercontent.com/16059989/63965400-0e304f00-ca67-11e9-86f1-7bd3c0c164dc.png)
