### ISSUE TITLE
Unable to Pack when dll mapping is specified

### ISSUE THREAD

**Issue by namurdock** [WaelHamze/xrm-ci-framework#23]
I have a VSTS task to pack the solution files using a mapping files to include dll's and webresources.

When i run the command locally using the solution packager and the same mapping xml file it packs with no errors.

However when i pack on VSTS the solution packager build task cannot find a mapping matching my dll.

I must be doing something wrong in my mapping file but cannot tell what. The packager works fine if i remove the dll file to file mapping:

```
<?xml version="1.0" encoding="utf-8"?>
<Mapping>
  <FileToPath map="*.jpg" to="..\WebResources\img\" />
  <FileToPath map="*.png" to="..\WebResources\img\" />
  <FileToPath map="*.gif" to="..\WebResources\img\" />
  <FileToPath map="*.js" to="..\WebResources\js\" />
  <FileToPath map="*.html" to="..\WebResources\html\" />
  <FileToPath map="*.css" to="..\WebResources\css\" />
  <FileToFile map="xxxxCMCRM2016.dll" to="..\..\xxxx.CM.CRM2016\bin\**\xxxx.CM.CRM2016.dll" />
</Mapping>
```

Output from the build on VSTS:

> 2017-05-16T13:45:49.9621209Z Processing Component: SolutionPluginAssemblies
> 2017-05-16T13:45:49.9621209Z  - xxxx.CM.CRM2016, Version=1.0.0.0, Culture=neutral, PublicKeyToken=4139be68fb23a728
> 2017-05-16T13:45:49.9621209Z Matched file 'd:\a\1\s\xxxx.CharityManagement\SolutionFiles\PluginAssemblies/xxxxCMCRM2016-23E903C6-6AAC-4739-A4DE-FA2D3C51503F/CHORUSCMCRM2016.dll' was not found in any mapping. Pack operation is aborted.
> 2017-05-16T13:45:49.9631206Z Cannot find required file 'd:\a\1\s\xxxx.CharityManagement\SolutionFiles\PluginAssemblies\xxxxCMCRM2016-23E903C6-6AAC-4739-A4DE-FA2D3C51503F\xxxxCMCRM2016.dll'.
> 2017-05-16T13:45:50.1251207Z ##[error]Solution Pack operation failed with exit code: 1
> 2017-05-16T13:45:50.1391198Z ##[section]Finishing: MSCRM Pack Solution

Also there are no errors reporting when unpacking using the same script and the dll is not extracted from the customizations zip file.

**Comment by WaelHamze** [comment]
Did you try to map directly to the release folder?

**Comment by namurdock** [comment]
Thanks @WaelHamze, total NOOB reason!

I had not put a build task into by build definition and so the binaries were never created on the build server.

Problem solved!
