### ISSUE TITLE
Connectionstring issue for MSCRM CRM ping vsts build task

### ISSUE THREAD

**Issue by rupalibolke** [WaelHamze/xrm-ci-framework#24]
I am using below connectionstring for MSCRM ping task which is basic one but getting error.

Connectionstring:
AuthType=Office365; Url=https://xdev.crm.contoso.com; UserName=username@xyzcloud.com; Password=password

Error: 
Object reference not set to an instance of an object.

Version: Dynamics 365 (online)

I have tried n number of combinations searching on internet but nothing works. its either above error or "Organization cannot be null or empty. Parameter name: Organization Name".

Kindly help.

**Comment by namurdock** [comment]
Is the url you have used the same as the url you see once you are connected to CRM?

The object reference not set to an instance of an object usually means that the connection did not find the organisation you were looking for.

**Comment by rupalibolke** [comment]
https://xdev.crm.contoso.com/main.aspx
This is the URL I see once i login.

**Comment by namurdock** [comment]
All Dynamics 365 environments i have seen have always been in the format 

> https://Orgname.**crm.dynamics.com**

Out of interest what do you see in the Developer Resources area within Dynamics?

Check the Service Root field.

I have successfully connected to other Dynamics 365 online instances with no problems.

**Comment by rupalibolke** [comment]
The service root URL is https://xdev.api.crm.dynamics.com/api/data/v8.2/

PS: I was purposely putting Contoso instead of dynamics in the URL. putting xdev for privacy purpose. Is this the one you are referring to?

**Comment by rupalibolke** [comment]
@namurdock  maybe you can confirm if the connectionstring value which i mentioned is correct or if any changes needs to be done for successful connection?

Connectionstring:
AuthType=Office365; Url=https://xdev.crm.dynamics.com; UserName=username@xyzcloud.com; Password=password

**Comment by namurdock** [comment]
yep that's the one.

Exactly the same format as I have.

Are you a system customizer in your target?

**Comment by rupalibolke** [comment]
I have System Administrator role. Maybe I will check if there are any proxy related issues as this is newly created instances. if so, i will wait till it gets resolved and try to check again.
I am able to connect to on-premise version instance and able to at least reach till publish step
For export, I have raised another issue.
Thanks @namurdock

**Comment by WaelHamze** [comment]
You could try to run a build on the hosted agent if you are using VSTS and see if that works.

**Comment by rupalibolke** [comment]
I do not have Hosted agents as the vsts I am using is version 2015 and on-premise. We currently do not have the project on tfs-online.

**Comment by WaelHamze** [comment]
The underlining Cmdlets and Scripts use the XRM Tooling. Do you have any other code using that which is working? https://msdn.microsoft.com/en-us/library/mt608573.aspx

**Comment by WaelHamze** [comment]
Just wanted to add that I have noticed that same build definition throws this error and then works later with no changes. Seems like something with the environment but can't figure out what it is yet.

**Comment by comacosy** [comment]
I am encountering the same issue.  I know the login I am using is an admin account.
connectionString="AuthType=AD; Url=https://$(CRM_Site)/DevCrm; Username=$(CRMUsername); Password=$(CRMPassword);"

Getting:
Error:
Organization cannot be null or empty.

**Comment by mattp65** [comment]
Try including the OrganizationName parm on the connection string. Even though it is implicit in the URL, the XRMtooling connection requires this.

**Comment by comacosy** [comment]
Tried adding OrganizationName=DevCrm;
Same error.
Tried adding Organization=DevCrm;
Same error.

**Comment by comacosy** [comment]
I tracked it back in the source code to the Ping.ps1 file, specifically the call to Select-WhoAmI.  I cant figure out past that though.  I think that tracks back into SelectXrmWhoAmICommand.cs file into this method:
public class SelectXrmWhoAmICommand : XrmCommandBase
{
    protected override void ProcessRecord()
    {
        base.ProcessRecord();
        base.WriteVerbose(string.Format("Invoking Organization Service"));

        var response = (OrganizationService.Execute(new WhoAmIRequest()) as WhoAmIResponse);

        base.WriteObject(response);
        base.WriteVerbose(string.Format("OrganizationId: {0}", response.OrganizationId));
        base.WriteVerbose(string.Format("BusinessUnitId: {0}", response.BusinessUnitId));
        base.WriteVerbose(string.Format("UserId: {0}", response.UserId));
    }
}

I can't see past that.

**Comment by WaelHamze** [comment]
The error is coming from the CRM SDK. I had this error even in console app. Then everything started to work with no changes in code. Must be something in the environment. It has worked since then so currently not able to reproduce it and debug it.

**Comment by jynxeh** [comment]
I just started using this tool set and I seem to be getting 'Object reference not set to an instance of an object.' exceptions for any task I try, every time I try, with the following connection string (redacted):

AuthType=Office365; Username=user.name@mycompany.co.uk; Password=usersPassword; Url=https://<myinstance>.crm11.dynamics.com

I'm using a Dynamics 365 sandbox instance and VSTS with a hosted build agent.

Is there anything useful I can do to get more information on this issue?

**Comment by jynxeh** [comment]
I've managed to track this down to an issue with the discovery servers. The current code base is using version 8.2.0.2 of Microsoft.CrmSdk.CoreTools nuget package. Using a test console app and trace logs I was able to see that version 8.2.0.2 queries the following discovery servers:

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (North America) URI is = https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (Europe, Middle East and Africa) URI is = https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (Asia Pacific Area) URI is = https://disco.crm5.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (South America) URI is = https://disco.crm2.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (Oceania) URI is = https://disco.crm6.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (Japan) URI is = https://disco.crm7.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (North America 2) URI is = https://disco.crm9.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (Canada) URI is = https://disco.crm3.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (India) URI is = https://disco.crm8.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (Germany) URI is = https://disco.crm.microsoftdynamics.de/XRMServices/2011/Discovery.svc

My instance is based in the UK and when checking I could see that my discovery server was not being queried. After a number of tests, I can see that the following server was added in version 8.2.0.4:

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (United Kingdom) URI is = https://disco.crm11.dynamics.com/XRMServices/2011/Discovery.svc

I've tried to see if there is a way to specify the discovery service in the connection string but so far have drawn a blank, so I believe the only fix is to update the version of Microsoft.CrmSdk.CoreTools that is referenced to 8.2.0.4 or the latest 8.2.0.5.

Happy to do a pull request but given how simple this is it is probably not worth it. Let me know if you need any further info @WaelHamze

**Comment by msterusky** [comment]
Hi,
the issue with "Organization cannot be null or empty." or "Object reference not set to an instance of an object." is in TokenCache, which uses as a default location %USERPROFILE%\AppData\... but sometimes a user of build agent has no write privilege for this location.
This is exactly a case of a Hosted Agent in VSTS which doesn't have a write permission for this path. I also tried to use a build agent in Azure VM, but it was running under 'NT AUTHORITY\NetworkService' user which had same issue, so I have to user a different user.
I found that everything what you need to do is that **you have to add a parameter "TokenCacheStorePath" to your connection string with a location which is accessible for a user of a build agent.**

`Url=https://ORG_NAME.crm4.dynamics.com; Username=dynamics365ci@DOMAIN.onmicrosoft.com; Password=*********; AuthType=Office365; TokenCacheStorePath=$(Build.Repository.LocalPath)\.cache;`

**Comment by rupalibolke** [comment]
the proxy error issue is still not solved the one I mentioned. not sure if for tfs to connect to azure we need any special permissions or firewalls open. I am still giving try with all the suggestions, people sending here, but so far none of them seems to be working.

**Comment by msterusky** [comment]
@rupalibolke 
 - what exactly are you trying to do?
 - I understood that you have TFS 2015 onpremise and you cannot join from TFS Build to CRM Online, right?
 - did you try my solution? It works also for on-premise build agents.

**Comment by WaelHamze** [comment]
Just to let you know I was facing this issue even with my local machine with full admin rights and I had this successfully running on the hosted agent in Azure. I have updated the framework to the latest SDK DLLs. Hopefully that will resolve some of the issues at least.

**Comment by GKawinski** [comment]
I was also getting the object reference error.  Explicitly adding the 'Domain' parameter to the connection string resolved it.  However this was only occurring for our IFD environment (no surprise there).  But what was surprising was that it depended on which machine I was running the script from.  The version of windows may have been the delta.  When I ran the script from a Windows Server 2008 machine, it ran fine.  But on our Windows Server 2012 machines I started getting the object reference error.  Again, explicitly adding the Domain parameter to the connection string resolved it.  

Hope this helps someone who's also been pulling their hair out.  -Greg

**Comment by WaelHamze** [comment]
Interesting. Although the domain didn't seem to fixed the current issue I am facing on one of the machines. I had it working on the same server version with no changes to code. Something in the environment must be changing. I even ran PerfMon but nothing stood out in the logs.

**Comment by rupalibolke** [comment]
**As mentioned earlier, the proxy issue got resolved and then I tried to run the build and it works. Thanks everyone for help and suggestions.**
