### ISSUE TITLE
ExtractSolution broken in 9.0.0.41

### ISSUE THREAD

**Issue by iggsn** [WaelHamze/xrm-ci-framework#243]
Hi Wael,

I am using your tools through command line, expecially to get the solutions under source controll and compile a managed solution in DevOps. Great work!
However from version 9.0.0.39 to 9.0.0.41 it seems, the ExtractSolution.ps1 is broken.

After upgrading the package I am getting this: 
Die Benennung
"Expand-XrmSolution" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren
Programms erkannt.

Looks like he can't find the "Expand-XrmSolution" command. For now I stick to the previous version (39).

Kind regards,
Lars

**Comment by WaelHamze** [comment]
@iggsn strange as it works for me. Can you try version 9.0.0.42?

**Comment by iggsn** [comment]
Hi Wael,
I just updated the nuget packge to x.42 but the error still remains.
I wrote an own small PowerShell script to combine 2 of the available Scripts.
First I get the path to the tools and also store the connection string and the solution name. Than I download the solutions using the ExportSolution.ps1-script. Which works fine.

`& "$scriptPath$relativeScriptPath\ExportSolution.ps1" -CrmConnectionString "$CrmConnection" -SolutionName "$SolutionName" -ExportManaged $True -ExportUnmanaged $True -ExportSolutionOutputPath "$ExportPath" -Timeout $TimeOut -UpdateVersion $False -Verbose`

After that I try to call the ExtractSolution.ps-script, which was working fine till version x.39 but returns an error after that.
`& "$scriptPath$relativeScriptPath\ExtractSolution.ps1" -CoreToolsPath "$CoreSolutionPath" -Verbose -solutionFile "$ExportPath\$SolutionName.zip" -UnpackedFilesFolder "$TargetPath" -PackageType "$PackageType"`

Now I get: 
```
Die Benennung "Expand-XrmSolution"
wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt
```
Which mean's the name was not found in a Cmdlet. But the call is inside the "ExtractSolution.ps1". Do I miss a parameter? I could see, that this call was added in version x.41 in the "ExtractSolution.ps1"-script.

Or is there a smarter way to get this done locally? On DevOps of cause I use the tasks ;-)

Kind regards,
Lars

**Comment by WaelHamze** [comment]
@iggsn I suspect somewhere you are loading the old cmdlet DLL instead of the new one.

I have this working using this script with both .41/42. Take a look maybe you are missing something.

https://github.com/WaelHamze/dyn365-ce-devops-sample/blob/master/Sample/Xrm.CI.Framework.Sample/Scripts/Extract.ps1

**Comment by iggsn** [comment]
@WaelHamze,

thank you for the hint. I finally found, what I was missing.
I checked, that your PowerShell-Scripts are related to the CoreTools (of cause). My holding project was still on Framework 4.5.2 and so I didn't got the latest CoreTools.

Means, if you want to use the XrmCIFramework starting v x.41, you have to make sure, you have the latest Tools installed, depending on Framework 4.6.2.

This is solved for me. Thanks a lot!

Kind Regards,
Lars

**Comment by WaelHamze** [comment]
@iggsn excellent glad this is working again
