### ISSUE TITLE
Apply solution upgrade using config file

### ISSUE THREAD

**Issue by sindhuraalle** [WaelHamze/xrm-ci-framework#244]
I am trying to use Task 'MSCRM Import Solutions Using Config (Preview)' to do solution upgrade with below config and it fails with solution file does not exist. Is there any way to do only 'Apply solution upgrade' ??

I am looking for steps where 1 imports the upgrade solution(Holding solution: true) and other to only upgarde

{
  "Solutions": [
    {
      "SolutionFilePath": "aaaaa.zip",
      "PublishWorkflows": true,
      "ConvertToManaged": false,
      "OverwriteUnmanagedCustomizations": true,
      "SkipProductUpdateDependencies": false,
      "HoldingSolution": false,
      "OverrideSameVersion": true,
      "ImportAsync": false,
      "ApplySolution": true,
      "ApplyAsync": true,
      "SleepInterval": 15,
      "AsyncWaitTimeout": 2400
    }
  ]
}

**Comment by WaelHamze** [comment]
@sindhuraalle at the moment you can't apply an upgrade without a solution, you can use apply solution task if that is what you are after
