### ISSUE TITLE
Trying to Connect to Onprem CRM

### ISSUE THREAD

**Issue by daakaram** [WaelHamze/xrm-ci-framework#246]
Hi guys, first of all this framework sounds amazing. I definitively will use this to automate our continuous integration environment. I am having trouble executing any of the cmdlets since the program is not liking my CrmConnectionString (at least that is what I believe since it is returning null every single time). Below is the error I am getting as well as the command I am executing, thanks for this amazing tool!

Command in PS:
[string]$CrmConnectionString = 'AuthType=Office365;Url=https://OrganizationName.crm.com/main.aspx;Username=username;Password=password;'

Error :
Set-XrmSolutionVersion : Object reference not set to an instance of an object.
At C:\Users\Username\Desktop\BuildAutomationScripts\BuildAutomationScripts\ExportSolution.ps1:71 char:2
+     Set-XrmSolutionVersion -ConnectionString "$CrmConnectionString" - ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-XrmSolutionVersion], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Xrm.Framework.CI.PowerShell.Cmdlets.SetXrmSolutionVersionCommand

Ps : I am trying to export the Unmanaged Solution to use it as our code version base template.

**Comment by mattp65** [comment]
Your URL looks wrong, it should be similar to https://orgname.crm.dynamics.com

**Comment by daakaram** [comment]
Even i tried with my CRM online Instance and receiving the error as below 

Command in PS:
[string]$CrmConnectionString = 'AuthType=Office365;Url=https://logix365demo.api.crm.dynamics.com;Username=deeaak7646@logix365demo.onmicrosoft.com;Password=password'

Error: 
![image](https://user-images.githubusercontent.com/55767288/69167561-c8f64900-0aba-11ea-89e1-bc542f44e9e0.png)

**Comment by mattp65** [comment]
For D365, you don't include .api. in the URL. just logix363demo.crm.dynamics.com. See https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect for details on the connection string.

**Comment by WaelHamze** [comment]
@mattp65 thx for responding to this
