### ISSUE TITLE
ExportSolution from Onpremise CRM failure

### ISSUE THREAD

**Issue by daakaram** [WaelHamze/xrm-ci-framework#249]
Hi, i am working on a powershell script to export the solution from On-premise Dynamics CRM which is giving me a different error every time when i execute the script. i am receiving multiple issues as below 

1. sometimes it executes fine and connects to Dynamics CRM and gives error as 
*"Export-XrmSolution : Solution LookupFiltering could not be found"*
![image](https://user-images.githubusercontent.com/55767288/69359798-e2c89500-0c4e-11ea-8e00-c463f64cc5fb.png)

2. sometimes it gives error as Object reference not set to an instance 
Set-XrmSolutionVersion : Object reference not set to an instance of an object.
![image](https://user-images.githubusercontent.com/55767288/69359929-31762f00-0c4f-11ea-8a1a-1a3d87f357ec.png)

3. sometimes it gives error as unable to login to CRM
![image](https://user-images.githubusercontent.com/55767288/69359999-59fe2900-0c4f-11ea-865d-73b149bd78ff.png)

Could you let me know what exactly i am missing in the script

Kindly help,
Thanks!!!

**Comment by WaelHamze** [comment]
@daakaram there could be a number of things that are contributing to this. I suggest you check the below...

1. Your connection string looks wrong as you are using office 365 for on premise.
https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/xrm-tooling/use-connection-strings-xrm-tooling-connect
2. Ensure there is no proxy interfering with your connection, you may need to add some PS script to work with proxy if needed
