### ISSUE TITLE
MSCRM Export Solution vsts build task error

### ISSUE THREAD

**Issue by rupalibolke** [WaelHamze/xrm-ci-framework#25]
Receiving error while exporting solution with basic settings in task. (Managed/Unmanaged or if both are checked, receiving same error)

Error:
_Exporting Managed Solution
Unrecognized request parameter: ExportSales_

PS: I am not checking the checkbox for "Export Sales" from Additional Export Options.
Since I am not able to connect to online version, I am trying to connect to on-premises and continuing my build definition as of now. Referring to the previous query I had put.

**Comment by WaelHamze** [comment]
Hi, I take it you are using a version that is lower than 365?

**Comment by rupalibolke** [comment]
I realized when you responded. Thanks, I shall check once the connection issue is solved if Export works fine or not. Thanks :)

**Comment by WaelHamze** [comment]
Any luck?

**Comment by WaelHamze** [comment]
Please re-open the issue if you are still facing the problem. This is normally if you have an earlier version of Dynamics prior to 365.

**Comment by rupalibolke** [comment]
The proxy issue has been resolved and i am able to Export solution successfully. Thanks :+1:

**Comment by WaelHamze** [comment]
Excellent news glad to hear that.
