### ISSUE TITLE
Export-XrmSolution : Cannot bind argument to parameter 'OutputFolder' because it is an empty string.

### ISSUE THREAD

**Issue by ravikatrenikona** [WaelHamze/xrm-ci-framework#257]
Hi Wael,
I am getting below error at exportsolution.ps1.
i have declared variables in my Azure DevOps pipelines and given below arguments in the powershell script.

Arguments:
-crmConnectionString $(crmConnectionString) -SolutionName $(SolutionName) -OutputFolder $ExportSolutionOutPutpath

Variable declaration in variable section:
CrmConnectionString
"ServiceUri=https://xxxx.api.crm.dynamics.com/XRMServices/2011/Organization.svc; Username=xxxxxxx@xxxxxx.onmicrosoft.com;Password=xxxxxx"

ExportManaged
"1"
ExportSolutionOutputPath
Build.ArtifactStagingDirectory

But getting below error:
Exporting Unmanaged Solution
Export-XrmSolution : Cannot bind argument to parameter 'OutputFolder' because it is an empty string.
At C:\Users\Ravi.k\agent\_work\14\a\drop\packages\XrmCIFramework.9.0.0.42\tools\ExportSolution.ps1:84 char:136
+ ... nName $SolutionName -OutputFolder "$ExportSolutionOutputPath" -Manage ...
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Export-XrmSolution], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Xrm.Framework.CI.PowerShell.Cmdlet 
   s.ExportXrmSolutionCommand

**Comment by WaelHamze** [comment]
Looks like you are either not passing the right parameter or it doesn't have the correct value.

The parameter is ExportSolutionOutputPath

**Comment by ravikatrenikona** [comment]
I have given variables in Build pipeline

crmConnectionString:
 "AuthType=Office365;ServiceUri=https://xxxxxx/XRMServices/2011/Organization.svc?wsdl;Username=username@xxxxx.onmicrosoft.com;Password=xxxxxxx;Organization=organization name"

SolutionName : xxxxxx

ExportSolutionOutputPath: $(Build.ArtifactStagingDirectory)


but still throwing same error

**Comment by ravikatrenikona** [comment]
<img width="751" alt="powershell(Exportsolution ps1)" src="https://user-images.githubusercontent.com/57341266/74304231-5ed00600-4d82-11ea-9159-fc8aec2e69eb.PNG">

**Comment by ravikatrenikona** [comment]
<img width="740" alt="variable declaration" src="https://user-images.githubusercontent.com/57341266/74304313-9939a300-4d82-11ea-9d88-afd7c625c42d.PNG">

**Comment by ravikatrenikona** [comment]
But getting below error:
Exporting Unmanaged Solution
Export-XrmSolution : Cannot bind argument to parameter 'OutputFolder' because it is an empty string.
At C:\Users\Ravi.k\agent_work\14\a\drop\packages\XrmCIFramework.9.0.0.42\tools\ExportSolution.ps1:84 char:136

... nName $SolutionName -OutputFolder "$ExportSolutionOutputPath" -Manage ...
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : InvalidData: (:) [Export-XrmSolution], ParentContainsErrorRecordException
FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Xrm.Framework.CI.PowerShell.Cmdlet
s.ExportXrmSolutionCommand

**Comment by WaelHamze** [comment]
@ravikatrenikona I am not sure you can do the below

ExportSolutionOutputPath: $(Build.ArtifactStagingDirectory)

Have you tried setting doing this in the script? -OutputPath "$(Build.ArtifactStagingDirectory)"

I just suggest you add another powershell script (in-line) and print these values to the console to see what they contain if you have issues.

also out of interest how comes you prefer using PS to export solution instead of the task?

**Comment by ravikatrenikona** [comment]
@WaelHamze :
As per your guidelines, i have given ExportSolutionOutputPath: $(Build.ArtifactStagingDirectory) in my pipelines, but no hopes. 
Also tried setting in the export solution script  -OutputPath "$(Build.ArtifactStagingDirectory)" , but unable to update inline script in powershell script in Azure devOps pipelines

getting below error whenever try to save the pipeline "powershell": task

TF20507: The string argument contains a character that is not valid:'u0009'. Correct the argument, and then try the operation again.
Parameter name: definition.Steps.script

**Comment by ravikatrenikona** [comment]
@WaelHamze 
I have run the below script then it is working fine.
#
# ExportSolution.ps1
#

param(
[string]$CrmConnectionString,
[string]$SolutionName,
[bool]$ExportManaged,
[bool]$ExportUnmanaged = $true,

[string]$ExportSolutionOutputPath,

[int]$Timeout
)

$ErrorActionPreference = "Stop"
$InformationPreference = "Continue"

Write-Verbose 'Entering ExportSolution.ps1'

#Parameters
Write-Verbose "CrmConnectionString = $CrmConnectionString"
Write-Verbose "SolutionName = $SolutionName"
Write-Verbose "ExportManaged = $ExportManaged"
Write-Verbose "ExportUnmanaged = $ExportUnmanaged"

Write-Verbose "ExportSolutionOutputPath = $ExportSolutionOutputPath"

Write-Verbose "Timeout = $Timeout"


#Script Location
$scriptPath = split-path -parent $MyInvocation.MyCommand.Definition
Write-Verbose "Script Path: $scriptPath"

#Load XrmCIFramework
$xrmCIToolkit = $scriptPath + "\Xrm.Framework.CI.PowerShell.Cmdlets.dll"
Write-Verbose "Importing CIToolkit: $xrmCIToolkit" 
Import-Module $xrmCIToolkit
Write-Verbose "Imported CIToolkit"


$CrmConnectionString= "AuthType=Office365;ServiceUri=https://xxxxxx.crm8.dynamics.com/XRMServices/2011/Organization.svc?wsdl;Username=xxxxxx@xxxx.com;Password=xxxxxxx"

$SolutionName="VeriTouch_AllGlobalOptionsets"

#Update Version
if ($UpdateVersion)
{
	Set-XrmSolutionVersion -ConnectionString "$CrmConnectionString" -SolutionName $SolutionName -Version $RequiredVersion
	Write-Host "Solution Version Updated"
}

#Solution Export

$exportManagedFile
$exportUnmanagedFile
$ExportSolutionOutputPath="C:\Users\Ravi.k"

if ($ExportUnmanaged)
{
    Write-Host "Exporting Unmanaged Solution"
        
    $exportUnmanagedFile = Export-XrmSolution -ConnectionString "$CrmConnectionString" -UniqueSolutionName $SolutionName -OutputFolder $ExportSolutionOutputPath -Managed $false 
    Write-Host "UnManaged Solution Exported $ExportSolutionOutputPath\$exportUnmanagedFile"
}

if ($ExportManaged)
{
    Write-Host "Exporting Managed Solution"
        
    $exportmanagedFile = Export-XrmSolution -ConnectionString "$CrmConnectionString" -UniqueSolutionName $SolutionName -OutputFolder "$ExportSolutionOutputPath" -Managed $true 
    
    Write-Host "Managed Solution Exported $ExportSolutionOutputPath\$exportmanagedFile"
}

**Comment by ravikatrenikona** [comment]
@WaelHamze , I need more than one CRM solutions should be export into output folder by using CRM powershell script? can you give me suggestions or help me on this

**Comment by WaelHamze** [comment]
@ravikatrenikona you will need to call the powershell script mutiple times.

Or use this script which takes a json config.

**Comment by ravikatrenikona** [comment]
Thanks WaelHamze,
 I have used this sample ExportSolutions using json script
{
  "Solutions": [
    {
      "SolutionName": "SolutionName-1",
      "Managed": false,
      "TargetVersion": null,
      "ExportAutoNumberingSettings": false,
      "ExportCalendarSettings": false,
      "ExportCustomizationSettings": false,
      "ExportEmailTrackingSettings": false,
      "ExportExternalApplications": false,
      "ExportGeneralSettings": false,
      "ExportIsvConfig": false,
      "ExportMarketingSettings": false,
      "ExportOutlookSynchronizationSettings": false,
      "ExportRelationshipRoles": false,
      "ExportSales": false,
      "IncludeVersionInName": true
    },
    {
        "SolutionName": "SolutionName-2",
      "Managed": false,
      "TargetVersion": null,
      "ExportAutoNumberingSettings": false,
      "ExportCalendarSettings": false,
      "ExportCustomizationSettings": false,
      "ExportEmailTrackingSettings": false,
      "ExportExternalApplications": false,
      "ExportGeneralSettings": false,
      "ExportIsvConfig": false,
      "ExportMarketingSettings": false,
      "ExportOutlookSynchronizationSettings": false,
      "ExportRelationshipRoles": false,
      "ExportSales": false,
      "IncludeVersionInName": true
  ]
 }
Note: we can export only unmanged solutions from CRM org. site


Similarliy i have prepared Importsolutions in this pipeline by using importconfig json script:
{
  "Solutions": [
    {
      "SolutionName": "SolutionName_1",
      "SolutionFilePath": "SolutionName_1.zip",
      "PublishWorkflows": true,
      "ConvertToManaged": false,
      "OverwriteUnmanagedCustomizations": true,
      "SkipProductUpdateDependencies": false,
      "HoldingSolution": false,
      "OverrideSameVersion": true,
      "ImportAsync": true,
      "ApplySolution": false,
      "ApplyAsync": false,
      "SleepInterval": 15,
      "AsyncWaitTimeout": 900
    },
    {
       "SolutionName": "SolutionName_2",
      "SolutionFilePath": "SolutionName_2.zip",
      "PublishWorkflows": true,
      "ConvertToManaged": false,
      "OverwriteUnmanagedCustomizations": true,
      "SkipProductUpdateDependencies": false,
      "HoldingSolution": true,
      "OverrideSameVersion": false,
      "ImportAsync": true,
      "ApplySolution": true,
      "ApplyAsync": true,
      "SleepInterval": 15,
      "AsyncWaitTimeout": 900
    }
  ]
}

Now i successfully export and import multiple solutions by using this ..


Thanks 
Ravikumar .K
Release Manager, DevOps team
