### ISSUE TITLE
Error while importing cmdlets module

### ISSUE THREAD

**Issue by Bakanych** [WaelHamze/xrm-ci-framework#26]
1. Add nuget package id="XrmCIFramework" version="8.0.13" to class library
2. Build library
3. Open library bin/debug folder
4. Run command: Import-Module .\Xrm.Framework.CI.PowerShell.Cmdlets.dll

The following error occurred:

Import-Module : Could not load file or assembly 'Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its
dependencies. The system cannot find the file specified.
At line:1 char:1
+ Import-Module .\Xrm.Framework.CI.PowerShell.Cmdlets.dll
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by WaelHamze** [comment]
Have the dependent Nuget packages been downloaded too?

**Comment by Bakanych** [comment]
@WaelHamze  hi, sorry for the late reply.
I found an issue. I had to modify powershell config to support 4.6 CLI:
`    <startup useLegacyV2RuntimeActivationPolicy="true"> 
        <supportedRuntime version="v4.0" />
	<supportedRuntime version="v4.6" />      
    </startup>
`
Now it works.

**Comment by WaelHamze** [comment]
Excellent. Glad to hear that this work now. I am sure it will be useful for others to know.
