### ISSUE TITLE
Unzip SARIF file produced by solution checker to be used in SARIF Viewer Build Tab

### ISSUE THREAD

**Issue by filcole** [WaelHamze/xrm-ci-framework#263]
It would be convenient if the results (zip) file exported by the PowerApps checker was unzipped and made available in an output variable, ideally with filename PowerAppsCheckerResults.sarif.  I think this is currently possible because the PowerApps checker only returns one file in the contents of its zip file.

Having the unzipped SARIF file available allows the use of the MS SARIF Viewer tab marketplace addin directly in the pipeline.
https://marketplace.visualstudio.com/items?itemName=sariftools.sarif-viewer-build-tab

See Scott Durows recent blog: http://develop1.net/public/post/2020/02/06/solution-checker-in-azure-devops-pipeline

Currently I'm using the following (suboptimal ;) ) powershell as a workaround after the powerapps checker steps.

```powershell
# The zipped solution checker results file with a random name is passed in an environment variable
$resultszip = $Env:SOLUTIONCHECKER_SOLUTION_CHECK_RESULT_FILE
Write-Host "resultszip=$resultszip"

#
# Determine the filename and path of the SARIF file
#
$Dest = "$Env:BUILD_SOURCESDIRECTORY"
$filename = Split-Path -Path $resultszip -Leaf
$sarifFile = "$Dest/$filename" -replace ".zip", ".sarif"

# Unzip 
Expand-Archive -LiteralPath "$resultszip" -DestinationPath $Dest

# Rename SARIF file  
Rename-Item -Path "$sarifFile" -NewName "PowerAppsCheckerResults.sarif"

**Comment by WaelHamze** [comment]
@filcole 

Yes at the moment you need a bit of PowerShell to use the sarif viewer.

I am expecting more useful information could be available in the zip file in future so thought of returning the zip would be future proof and the consume has the option to do what they want with it (i.e. like above).

At some point I thought I could even automatically upload the sarif as an artifact (optional switch in the task)

Let me know your thoughts

**Comment by filcole** [comment]
No problems. Thanks for reviewing the request. I agree it makes sense to let the user process the zip as required if the zip file might contain extra information in the future.
