### ISSUE TITLE
Check in the Managed Solution in TFS

### ISSUE THREAD

**Issue by Pathikr** [WaelHamze/xrm-ci-framework#27]
Hi ,

I am using your Export solution task from market place. I see an Output Path and when I configure Output Path as TFS folder, it throws error saying Path not found. Is it possible to check in the solution to TFS

**Comment by WaelHamze** [comment]
In the scope of the task, the output path would be the path on the agent machine to the folder where the solution is to be placed. If you wish to store the output of the build in TFS then you will need to do that after the task.

**Comment by Pathikr** [comment]
You can also use PowerShell Script for that as well

cd $env:BUILD_SOURCESDIRECTORY\Development
write-host $env:BUILD_SOURCESDIRECTORY\Development
write-host "CD Done"
#$TFFile = 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\TF.exe'
$TFFile = 'TF.exe'
write-host "TF done"
$tfOutput = & $TFFile add /loginType:OAuth /login:.,$(System.AccessToken) /noprompt
$tfOutput = & $TFFile checkin /noprompt /comment:"NO_CI" /loginType:OAuth /login:.,$(System.AccessToken)
write-host "check in done"

**Comment by Pathikr** [comment]
![image](https://user-images.githubusercontent.com/28738932/32278883-618ad40c-bf17-11e7-836d-448a1f7fea71.png)
