### ISSUE TITLE
Components do not get removed

### ISSUE THREAD

**Issue by Kato88** [WaelHamze/xrm-ci-framework#276]
Hi there.
I am using this framework for a while now and after some some month I had to realize that using the import solution task does not remove components on the target system that are no longer part of the managed solution.

You can check an option when you do a manual import to remove all components that are no longer in the solution, but you can't in the import task.

Am I missing something or is it simply not possible?
![image](https://user-images.githubusercontent.com/4804015/82883470-bc0f5200-9f42-11ea-9b47-45c061d8ede1.png)

**Comment by mattp65** [comment]
With the API, you need to Import using the Holding Solution and then run an Apply changes step. This is an API limitation, not the toolset.

**Comment by WaelHamze** [comment]
@Kato88 as @mattp65 suggested, You need the tick the "Holding Solution" on the Import task. Then you need to add another task to the pipeline "Apply Solution Upgrade"

The two step process will allow you to delete components.

**Comment by BehbudShikhaliyev** [comment]
Thanks for the solution! It works as expected!
