### ISSUE TITLE
Import canvas app error

### ISSUE THREAD

**Issue by koener1985** [WaelHamze/xrm-ci-framework#277]
Hi,

When we import a solution with a canvas app we get the error:

Microsoft.Crm.CrmException: Code: GraphUserDetailNotFound Message: Could not find user .... in Graph.

A manual import succeeds with no errors.

Any thoughts?

**Comment by WaelHamze** [comment]
@koener1985 I have not seen this. There are slight differences between both import types.

I presume you are using import using async mode?

**Comment by koener1985** [comment]
Yes, i am using async mode. I will try sync mode and see if there is any difference.

**Comment by koener1985** [comment]
Same problem in sync mode. Could it have something to do with the connection? I am using now ClientSecret instead of Office365.

**Comment by WaelHamze** [comment]
@koener1985 are you still having this issue? I would try the connection using ping task. if it works fine then it is not the connection.

**Comment by koener1985** [comment]
@WaelHamze issue seems to be solved. But we made no changes. Maybe a temporary issue on Microsofts side.
Thanks!
