### ISSUE TITLE
does it work with VSTS online?

### ISSUE THREAD

**Issue by manishkk81** [WaelHamze/xrm-ci-framework#29]
Want to know if the tool work with VSTS online? Where to install the tool in case of VSTS online?

**Comment by WaelHamze** [comment]
Just click install from this link: https://marketplace.visualstudio.com/items?itemName=WaelHamze.xrm-ci-framework-build-tasks
Make sure you login to the right VSTS account with the right permissions to install the extension

**Comment by manishkk81** [comment]
I am getting below error:
Searching for applicable products...
6/21/2017 4:47:28 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
6/21/2017 4:47:28 PM - Found installed product - Microsoft Visual Studio Professional 2015
6/21/2017 4:47:28 PM - Found installed product - Microsoft Visual Studio Community 2015
6/21/2017 4:47:28 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
6/21/2017 4:47:28 PM - Found installed product - Global Location
6/21/2017 4:47:28 PM - Found installed product - Visual Studio Community 2017 (2)
6/21/2017 4:47:28 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

**Comment by WaelHamze** [comment]
Here are some instructions on how to install extensions: https://www.visualstudio.com/en-us/docs/marketplace/get-vsts-extensions
