### ISSUE TITLE
Export CRM Solution error

### ISSUE THREAD

**Issue by khanarshan2000** [WaelHamze/xrm-ci-framework#33]
Hi Wael,

First of all thanks again for this tool.It really makes life simple
Here is a new issue. We are getting for one solution which is exporting fine in CRM manually with version 8.2 selection but the same solution is throwing error when exporting using CRM scripts.
How to get exact error as we are not able to get hold of this issue

017-07-10T12:57:57.8474132Z ##[error]Export-XrmSolution : An unexpected error occurred.
At D:\a\1\s\Main\Source\BuildDeployAutomation\CRMSolution\ExportSolution.ps1:83 char:28
+ ... nagedFile = Export-XrmSolution -ConnectionString "$CrmConnectionStrin ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Export-XrmSolution], FaultException`1
    + FullyQualifiedErrorId : System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Micros 
   oft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Xrm.Framework.CI.PowerShell.Cmdle  
  ts.ExportXrmSolutionCommand

**Comment by WaelHamze** [comment]
@khanarshan2000 What CRM version you are targeting and where it is hosted? You could look to run fiddler on the same machine where the script is running to see that exact http response/traffic from the CRM service.

**Comment by khanarshan2000** [comment]
Thanks for the reply.I am not good in setting up this.This is happening on my local system as well as on Visual Studio hosted premise as well. Also,i want to share that error is not coming as i was trying out a different toolkit you might be aware of (https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell) and export is working fine for that solution.The export is failing only from your script. In the meantime,i will check how i can get you out  http response/traffic from CRM Service when this error is occurring

**Comment by khanarshan2000** [comment]
Ok,i got the issue and fix but i am not sure logically what has got changed,perhaps we caught this after CRM version change from 8.1 to 8.2
There are 2 arguments which we were passing 
-TargetVersion 8.2 -RequiredVersion x.x.x
So now if developer has a solution with version 8.2 and using 8.2 features there then it seems powershell script is not liking us to pass argument explicitely -TargetVersion 8.2 and this is resulting into "Unexpected Error".
If we remove -TargetVersion parameter and just keep -RequiredVersion x.x.x then script is working fine  and it is capturing default SolutionPackageVersion="8.2" by itself in the solution.xml.
If we want to capture with 8.1 version saying [-TargetVersion 8.1 -RequiredVersion x.x.x] then the same solution export is working fine with the script.

I don't remember this issue happening earlier with 8.1 version previously or you can correct me here but no one reported this issue till now
