### ISSUE TITLE
Problem connecting to CRM11

### ISSUE THREAD

**Issue by JonBroadley** [WaelHamze/xrm-ci-framework#34]
The extensions you have created are incredibly handy, and have worked perfectly in the past, but I am having trouble deploying to CRM11. From reading around the subject it seems to be due to the Xrm Tooling Connector being out of date. I have tried uninstalling and re-adding the tool from the marketplace in case that would solve the issue, without any success. Have you any suggestions?

**Comment by JonBroadley** [comment]
Ah just realised I am still on 8.0.3 so the update to 8.0.19 hasn't happened...

2017-07-14T12:56:48.4976352Z ==============================================================================
2017-07-14T12:56:48.4976352Z Task         : MSCRM Ping
2017-07-14T12:56:48.4976352Z Description  : A sample task that checks connectivity to a Dynamics CRM environment
2017-07-14T12:56:48.4976352Z Version      : 8.0.3
2017-07-14T12:56:48.4976352Z Author       : Wael Hamze
2017-07-14T12:56:48.4976352Z Help         : Performs a WhoAmIRequest against the target CRM environment
2017-07-14T12:56:48.4976352Z ==============================================================================

**Comment by WaelHamze** [comment]
I am using the latest tooling from the CRM SDK. The latest version of the ping task that contains this update is 8.0.3, What is the error that you are getting?

**Comment by JonBroadley** [comment]
******************************************************************************
Starting: MSCRM CRM Ping
******************************************************************************
==============================================================================
Task         : MSCRM Ping
Description  : A sample task that checks connectivity to a Dynamics CRM environment
Version      : 8.0.3
Author       : Wael Hamze
Help         : Performs a WhoAmIRequest against the target CRM environment
==============================================================================
Object reference not set to an instance of an object.
******************************************************************************

It all works fine for CRM4, but errors on CRM11

**Comment by WaelHamze** [comment]
Does this sound like this issue? https://github.com/WaelHamze/xrm-ci-framework/issues/24

**Comment by JonBroadley** [comment]
Ok, it looks like I might have been a muppet and had a typo or a bad character in the connection string, I just manually retyped the connection string and it connected... I'd had problems with CRM11 previously and made an assumption too swiftly. Thanks for the fast response :)

**Comment by WaelHamze** [comment]
Excellent. Glad this is working
