### ISSUE TITLE
Can't use Tasks in Release only in Build

### ISSUE THREAD

**Issue by JoostVeldhuis** [WaelHamze/xrm-ci-framework#35]
I'm using the same task, Publish Customizations, in both Build and Release with the same connectionstring and it is working in the Build pipeline but in the Release Pipeline I'm getting an error: ##[error]Object reference not set to an instance of an object.

I'm getting this error with all tasks in Release.

**Comment by WaelHamze** [comment]
Are you running the release on the same agent as the build?

**Comment by JoostVeldhuis** [comment]
Yes everything is the same. Even the same Dynamics 365 environment, Same connectionstring,

**Comment by JoostVeldhuis** [comment]
oke, miraculously it started working this morning. I haven't changed anything to either environment or connectionstring.

**Comment by JoostVeldhuis** [comment]
I now know what the issue was. We automatically generate our passwords for the service user in dynamics that we use in CI/CD for release. And this password contained a ";" which is not good when using this in a connectionstring. That's why it wasn't working.

**Comment by WaelHamze** [comment]
Glad you got it working. Will close this issue now.
