### ISSUE TITLE
MSCRM Pack Solution - Allow Extract

### ISSUE THREAD

**Issue by sporens** [WaelHamze/xrm-ci-framework#36]
When automating the build package process it's required that the solution be extracted with the solutionpackager.exe app prior to packing it with MSCRM Pack Solution. It would be better if we were able to do the extraction as part of the build process prior to the pack in order to align versioning from the DEV instance of CRM.

I have a build job which does the following:
-Pulls the solution nightly from DEV
-Stores that in VSTS
Followed by a Release process that does the following:
-Builds a package based on the source
-Stores that in VSTS

Between these I'm unable to run solutionpackager.exe with the extract in order to close the loop between the processes.

Thanks

**Comment by WaelHamze** [comment]
@sporens thx for sharing your experience. As per current design principals, the unpack is best executed by the developer who is making the changes and is able to look at any conflicts and confirm what really needs to be checked-in. This is based on that source control should be golden source or all code and customisations.

What I normally do is trigger a build on every check-in that packs and promotes the changes to a stage environment.

In your current design, how do you ensure that unfinished changes are not checked-in and promoted as part of the release at night?

**Comment by sporens** [comment]
We have a development environment where we’re focused on adding functionality against the core entities. Thus we’re clear on the conflicts and I’m more interested in moving the code out of CRM into a package and have an easy deployment for the testing team.

**Comment by WaelHamze** [comment]
I am currently not planning to build an extract task for the below reasons:
-CRM Solution customisations are considered as part of source
-It is not recommended to check-in source as part of a build. Especially if you have a CI build.
-Ideally the pack should be run by developer upon completion of work with full control over what gets check-in and how conflicts are managed.
