### ISSUE TITLE
Question - Special setting for error Logs Import solution

### ISSUE THREAD

**Issue by Antos2310** [WaelHamze/xrm-ci-framework#37]
Hello,

This is more of a query, looking at the script it looks like it logs into the directory if there is an error. But if there is an error it actually does not push the xml to the drop folder. Any help on this is appreciated.

Thanks

**Comment by WaelHamze** [comment]
If the initial sync call that uploads the solution and kicks off the import succeeds, then the code will get into a loop trying to find the status of the import job. If the import job fails on the CRM side, the status call would return fail and this would stop the loop and download the logs. If the call to get the status keeps on failing or there is a crash or the loop times out, then you will not get the logs. However you can always do this later using the PowerShell Cmdlets using the import job id. Hope this helps.
