### ISSUE TITLE
Cannot build Xrm.Framework.CI.PowerShell.Cmdlets - VS 2015

### ISSUE THREAD

**Issue by Stanzarectah** [WaelHamze/xrm-ci-framework#38]
When I build this project from the source coder I get:

The command "NuGet.exe pack -sym C:\Users\lais\Downloads\xrm-ci-framework-master\CRM365\Xrm.Framework.CI\Xrm.Framework.CI.PowerShell.Cmdlets\Xrm.Framework.CI.PowerShell.Cmdlets.csproj -Prop Configuration=Debug" exited with code 9009.	Xrm.Framework.CI.PowerShell.Cmdlets			

From the output console I get:

'NuGet.exe' is not recognized as an internal or external command, operable program or batch file.

I am using VS 2015.

Any ideas?

**Comment by Stanzarectah** [comment]
All good, realised that my path for the post build event command line had to include nuget.exe !

**Comment by WaelHamze** [comment]
Glad you got it working. Thx.
