### ISSUE TITLE
Ping build task gets Object reference error

### ISSUE THREAD

**Issue by rappen** [WaelHamze/xrm-ci-framework#4]
Tried teh simplest Ping task in my build, and it returned ``Object reference not set to an instance of an object.``

Connection string used:
``AuthType=AD;Url=https://blablabla.se/blabla;`` (but with correct url, of course)

Using VSTS hosted build agent.

Are there any ways of getting more info about the problem?

```
******************************************************************************
Starting: MSCRM CRM Ping
******************************************************************************
==============================================================================
Task         : MSCRM Ping
Description  : A sample task that checks connectivity to a Dynamics CRM environment
Version      : 8.0.2
Author       : Wael Hamze
Help         : Performs a WhoAmIRequest against the target CRM environment
==============================================================================
Object reference not set to an instance of an object.
******************************************************************************
Finishing: MSCRM CRM Ping
******************************************************************************
```

**Comment by clc136** [comment]
I have these build tasks working. Suggest check credentials in connection string. Chris

**Comment by rappen** [comment]
I hoped default credentials would work. Either way, null reference exception is a bit unexpected.

**Comment by WaelHamze** [comment]
It is a bit difficult to debug with the hosted agent. You could try setting the variable system.debug in the build definition to true. If you are using the hosted agent, this would run under some generic account that would not have access to your CRM. You will need to pass in the username and password and ensure your CRM is accessible from the hosted agent. I am not doing anything clever in this task, this error is most probably being generated from the Xrm Tooling Connection Library.

**Comment by rappen** [comment]
The ``ping`` works when adding username, domain and password in the connectionstring.
So I guess this issue should be rephrased to "Please implement error handling to provide relevant error messages for connection strings" :)

**Comment by WaelHamze** [comment]
All my code is doing is the using the SDK constructor `ServiceClient = new CrmServiceClient(ConnectionString);` So it seems there is no validation in this function. I am not able to put validation logic in my code as the initial string you supplied is perfectly valid if you are using SSO using AD on-premise. The SDK code seems to be missing some validation.

**Comment by rappen** [comment]
👍

**Comment by clc136** [comment]
I think the constructor for the client is returning a null with inadequate credentials

**Comment by rappen** [comment]
If that is the case, it should probably be handled in the cmdlet...

**Comment by alphonso77** [comment]
Hey all: I know this is an old thread but I'm having an issue with this. I have two accounts, my personal account and a service account. When I put my personal account in the connection string, I can Select-WhoAmI, and Export-XrmSolution just fine. But when I try the service account, I get the 'Object reference not set' exception. @WaelHamze I'm guessing you're exactly right that the CrmServiceClient constructor is not validating the connection string before trying to parse it. 

I've asked our ops department to generate several different passwords for the service account (thinking that maybe a special character like equals (=) or semi-colon (;) was disrupting the parsing of the connection string. But now, they have generated a password with only alpha-numeric characters and I'm still getting the error. 

Here is a sample of the two connection strings (with sensitive information removed). This is for a D365 online login using an account. 

# working connection string
$connectionString = "server=https://xxx.dynamics.com/xxxorg; Username=xxxMyUser@clientdomain.com; Password=xxxMyPWord; authtype=Office365;"
# broken connection string
$connectionString = "server=https://xxx.dynamics.com/xxxorg; Username=xxxSvcAcct@clientdomain.com; Password=xxxSvcAcctPword; authtype=Office365;"

Any ideas on a workaround? Do you think using client secret is a possible solution?

**Comment by majakubowski** [comment]
@alphonso77 
Check this article to see how to handle special characters in connection strings:
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms722656(v=vs.85)#setting-values-that-use-reserved-characters

**Comment by WaelHamze** [comment]
@alphonso77 do you have any restrictions applied on the service account in AAD? I suspect this is the case or some other difference.

Have you managed to get these connection strings to work using another Tool like XrmToolBox?
