### ISSUE TITLE
[REQUEST] Publish cmdlets to powershell gallery

### ISSUE THREAD

**Issue by devkeydet** [WaelHamze/xrm-ci-framework#41]
It would be really convenient to have the cmdlets on PowerShell Gallery:
https://www.powershellgallery.com/

...so we can Install-Module from the gallery similar to:
https://www.powershellgallery.com/packages/Microsoft.Xrm.Data.Powershell/

**Comment by WaelHamze** [comment]
Good suggestion, this is already in progress. Will let you know once it is there.

**Comment by WaelHamze** [comment]
https://www.powershellgallery.com/packages/Xrm.Framework.CI.PowerShell.Cmdlets
