### ISSUE TITLE
[REQUEST] Task to Programatically Updating the Secure Configuration of a Plug-in Step

### ISSUE THREAD

**Issue by devkeydet** [WaelHamze/xrm-ci-framework#42]
Would you consider adding a task that encapsulates the following?
http://www.tomasschulkes.com/index.php/programatically-updating-the-secure-configuration-of-a-plug-in-step-after-deploying-a-solution/

The goal would be to use it to update dev/test/prod with appropriate values through automation.

**Comment by devkeydet** [comment]
Any feedback on this one?  I have a sample console application that does what I would love to see embodied as a VSTS task from this project here:
https://github.com/devkeydet/UpdateSecureConfiguration

**Comment by devkeydet** [comment]
Do you take contributions?  I'd be happy to take a crack at porting my console application to a task.  I can fork, give it a shot based on your other tasks, and submit a pull request.  Thoughts?

**Comment by WaelHamze** [comment]
Hi, the online management  tasks has been consuming most of my time dedicated to this framework recently. Contributions are always welcome. Let me know if you need any guidance.
Have you considered storing the configuration in a custom entity in CRM which you can secure using roles and deploy/manage using configuration migration/package deployer if needed. The plug-ins could retrieve this at runtime and cache if needed.

**Comment by devkeydet** [comment]
I have, but prefer to use secure config.  I'll look at your other tasks and try building this out and submit a pull request.  If it meets your bar, let me know and I can help with others.

**Comment by WaelHamze** [comment]
Published in 8.2.1
