### ISSUE TITLE
Debug powershell scripts in VS 2015

### ISSUE THREAD

**Issue by Stanzarectah** [WaelHamze/xrm-ci-framework#45]
Hi all,

I can successfully debug the C# code using VS 2015 debugger by attaching process but how do I achieve the same experience when debugging Powershell scripts?

Ideally I would like to execute a script and have the abilitiy to step through the code and then see my flow transfer to the C# code for debugging. Is this possible with your solution?

**Comment by WaelHamze** [comment]
One way to do it would be to open the script in the Powershell ISE and setup some breakpoints in there.
