### ISSUE TITLE
[REQUEST] Tasks for Online Management API for Dynamics 365 Customer Engagement

### ISSUE THREAD

**Issue by devkeydet** [WaelHamze/xrm-ci-framework#46]
A set of tasks which allow one to make calls to the new API:
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/online-management-api

**Comment by WaelHamze** [comment]
Thanks for the suggestion. The backup task is already live. A few more to go.

**Comment by devkeydet** [comment]
Now that you've accepted my PR for MSCRMUpdateSecureConfiguration, I'd be happy to contribute to helping with the Online Management API tasks.  I see that you are already working on MSCRMProvisionOnlineInstance in addition to the backup task.  If nobody is working on MSCRMDeleteOnlineInstance, then I would be happy to work on that one asap.  I need MSCRMProvisionOnlineInstance and MSCRMDeleteOnlineInstance to effectively "reset" an instance (since reset isn't a feature of the API yet).  Let me know if you'd like me to start that work.

**Comment by WaelHamze** [comment]
The Delete is the one I am about to finish. Any other ideas?

**Comment by devkeydet** [comment]
Restore Online Instance?

**Comment by devkeydet** [comment]
Are you working on one to get an online instance id by domain name?  If not, it will probably be necessary.  I had to do that in my script here: 
https://github.com/devkeydet/dyn365-ce-mgmt-api-devops-scripts/blob/master/ResetInstanceByDomainName.ps1

**Comment by WaelHamze** [comment]
Hi, You have a go at this task https://docs.microsoft.com/en-us/rest/api/admin.services.crm.dynamics.com/updateinstanceadminmode
What do you think?

The thing with tasks is you can't pass output parameters from the task I believe? I was planning on passing either an instanceId or Name to all the tasks so the user can select the option required.

**Comment by devkeydet** [comment]
This task accomplishes an output parameter:
https://marketplace.visualstudio.com/items?itemName=keesschollaart.arm-outputs

**Comment by WaelHamze** [comment]
Aha in this case you could try putting one together. The code is already there in the Delete instance PowerShell script

**Comment by WaelHamze** [comment]
Added the scripts for Backup/Delete/Restore. Just need to check-in the tasks. I'll do this once I fix the issue with the restore which is still failing.

**Comment by devkeydet** [comment]
Ok, I went ahead and added the script to get the instance id by domain name here:
https://github.com/devkeydet/xrm-ci-framework/blob/MSCRMGetOnlineInstanceId/CRM365/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell.Scripts/GetOnlineInstanceId.ps1

Do you want me to wait until I create and test the tasks before submitting a pull request or should I go ahead an submit just for the script?

**Comment by devkeydet** [comment]
Disregard.  I just realize you created a Get-XrmInstanceByName function.  I will use that for the task and remove my script.

**Comment by WaelHamze** [comment]
Ah yes was just going to tell you that. Just go ahead with creating task. I thought I’ll do some refactoring and build some reusable code

**Comment by devkeydet** [comment]
pull request waiting

**Comment by devkeydet** [comment]
Still want me to tackle updateinstanceadminmode next?

**Comment by WaelHamze** [comment]
I am looking forward to that too. If you have time that would be great.
Are you able to try the RestoreOnlineInstance.ps1 script. It is failing for me but I think it is due to a problem with my tenant. I have logged a ticket to resolve this.

**Comment by devkeydet** [comment]
I will try it out

**Comment by devkeydet** [comment]
I got RestoreOnlineInstance.ps1 to work, but I had to fix some issues in the code.  See this pull request:
https://github.com/WaelHamze/xrm-ci-framework/pull/52

**Comment by WaelHamze** [comment]
Published in version 8.2.1
Please create a new issues for any new tasks relating to this API
