### ISSUE TITLE
Behavior of processes during export and then import operation

### ISSUE THREAD

**Issue by rupalibolke** [WaelHamze/xrm-ci-framework#48]
When we are exporting solutions from D365 (DEV environment), the behavior which we are seeing around processes is different time to time. sometimes it gets deactivated in the QA environment where its imported or sometimes the state of processes remains same (as per DEV environment) when imported to QA environment.

Kindly advise if the behavior is expected or if its an issue.

**Comment by WaelHamze** [comment]
I presume you set the parameter publish workflows to true on the task?

**Comment by WaelHamze** [comment]
Managed or unmanaged solution?

**Comment by rupalibolke** [comment]
Managed solutions.

**Comment by WaelHamze** [comment]
I think this is expected. All the parameters for import are already provided for you in the task and not much more we can do as part of import solution. You could consider adding some post import steps in your deployment if you want to do more things.

**Comment by rupalibolke** [comment]
We will try to uncheck the publish workflow checkbox and see if we can retain the state of processes from DEV to QA post export and import.
