### ISSUE TITLE
Unable to find "PostBuild.ps1" File.

### ISSUE THREAD

**Issue by SachinRChavan** [WaelHamze/xrm-ci-framework#5]
Hi,

I recently downloaded the "xRM CI Framework" Project. I was trying to peek into the "PostBuild.ps1" script to view the Post-Build actions, but was unable to find the Build Folder itself (including the PostBuild.ps1).
Kindly, let me know where do I find it.

**Comment by WaelHamze** [comment]
This file was present by mistake in the solution. Use the Package.ps1 file instead
