### ISSUE TITLE
Package Solution Fails to add assembly

### ISSUE THREAD

**Issue by alex-ries** [WaelHamze/xrm-ci-framework#54]
Hi,

I'm currently working on automating a large Dynamics deployment. We are manually unpacking multiple solutions and housing them in VSTS. I've added the VSTS tooling and we're trying to leverage it to package the solution up and publish it to a nuget feed.

The issue comes up when I try to have the solution be packaged. I created a project that has a structure similar to this

ProjectSolution.csproj
-> SolutionMapping.xml
->solutionfolder\
---> [all the solution contents/xml/etc]

When I use the packager I point it to solutionfolder as the location of the solution definition. I do this by referencing the $(build.source)\ProjectSolution\solutionfolder as the input for the Pack command. It seems to run fine until it gets to the RootValidation bit during the packaging where I get the following error:

Following objects, required by the solution, are not present. /n/r  Type='PluginAssembly', Id (or schema name)='PluginAssembly-Crm.Solution.Plugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=be6b1fd5164e4b48'.
/n/r Please do a dependency check on your solution prior to exporting, add the missing objects to your solution and re-export/n/r
Error occurred during execution of plugin 'RootComponentValidation': RootComponent validation failed.

Now I have seen (through publishing the entire folder structure and contents) that all the files are in place, including the plugin assembly. And the SDK's solutionpackager works fine even when I download the artifacts and reference that structure.

So what is the VSTS package doing differently from the solutionpackager.exe, and how can I troubleshoot this further?

**Comment by WaelHamze** [comment]
@alex-ries  The VSTS task is using the solutionpackager.exe internally. Do you pass a mapping file? If so ensure the mappings are linking the plug-in files correctly (i.e. to correct bin directory release/debug) depending configuration. 

This is the main powershell [script ](https://github.com/WaelHamze/xrm-ci-framework/blob/master/CRM365/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell.Scripts/PackSolution.ps1 )that gets executed. I would suggest to pull the latest version of source locally into a different folder, build your plug-ins using same configuration as build and then run the script. You can debug the script if needed.

**Comment by alex-ries** [comment]
I think I know what the issue is here: it looks like the 8.2 solutionpackager does not work on a 9.0 solution :)

So I guess my request/question is: what is the timeline on getting a 9.0 (maybe a preview version???) up? It looks like this particular SDK tool behaves in the same way in terms of parameters and simply replacing the executable "works on my machine." 

Alternatively I guess I could leverage the scripts as they are and package them up and publish it internally to be used. If you have some steps for how to integrate that in to VSTS that'd speed things up, otherwise I can figure that out myself as well. Preferably I'd just use the VSTS tools :)

**Comment by WaelHamze** [comment]
@alex-ries Yes version 9 is on the plan. Good to already see interest in DevOps on V9. The V9 exe should work with V8 so that would have been simple change but it is still in preview so may break existing functionality for some users. I am currently considering whether to release another extension for V9 or provide another version of the tasks inside the existing extension.
If you need something urgently I would suggest you use the script I shared, otherwise would be good to have someone using V9 that can provide feedback on the updates :)

**Comment by alex-ries** [comment]
I forked the solution and upgraded the nuget packages to the 9.0.0.4 preview package, I also updated to nuget 4.3.0 (and updated the project file). Everything compiled OK and ping.ps1 works on the 9.0 and 8.2 environment that I tried it on. I didn't get to execute all the scripts/cmdlets.

FYI this did fix my problem :)

**Comment by WaelHamze** [comment]
Excellent thanks. Will try to get this on the marketplace soon.
