### ISSUE TITLE
Dynamics CRM 369 version 9.0

### ISSUE THREAD

**Issue by dirkr1** [WaelHamze/xrm-ci-framework#57]
Does the xrm-ci-framework also support version 9.0? Or when will this support be available?

**Comment by WaelHamze** [comment]
I am working on the support for 9.0? After you after the tasks of the PowerShell module?

**Comment by WaelHamze** [comment]
I have a preview for v9. If anyone is interested in trying let me know

**Comment by arifhs** [comment]
can i get hold of the preview of V9 ?

**Comment by arifhs** [comment]
my email is arifhs@gmail.com

**Comment by WaelHamze** [comment]
Live on Marketplace. You will need to change the task version to 9 for existing builds/releases. No new features added in this release (just lots of refactoring in the source)

**Comment by WaelHamze** [comment]
Let me know if you have any issues. You should be able to switch back to version 8 of the task if needed.
