### ISSUE TITLE
MSCRM Export Solution Task gives: Unrecognized request parameter: ExportExternalApplications

### ISSUE THREAD

**Issue by bwmodular** [WaelHamze/xrm-ci-framework#6]
Hi Wael,
after succesfully pinging our CRM Organisation, I've added a CRM Export Solution task to my build definition in VSTS.

It fails almost immediately with this error:
Unrecognized request parameter: ExportExternalApplications

CRM 2015 On Prem IFD.

Any ideas?
Thanks,
Ben

******************************************************************************
Finishing: MSCRM CRM Ping
******************************************************************************
******************************************************************************
Starting: MSCRM Export Solution: AdssNewToolkit
******************************************************************************
Task         : MSCRM Export Solution
Description  : Exports a CRM Solution from the source CRM environment
Version      : 8.1.1
Author       : Wael Hamze
Help         : More information here: https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.exportsolutionrequest.aspx

Exporting Unmanaged Solution
Unrecognized request parameter: ExportExternalApplications

**Comment by bwmodular** [comment]
So ExportExternalApplications is a 2016+ parameter, not recognised by CRM 2015. I tried setting the Target Version to 7.0.0.0 but that didn't help.
Is there anything to be done, or should I just revert to powershell scripts? Thanks.

**Comment by WaelHamze** [comment]
The tasks work with Dynamics 365 so I have added all the latest parameters from the SDK which may not be present in earlier version. If you not planning to upgrade soon and you have it working with PS I would suggest you carry on doing that. You could also look to download the source and replace the PS scripts with the earlier version and package your own version of the tasks. Its shame the SDK is not backwards compatible by ignoring the extra parameters as this would work nicely with all versions.

**Comment by bwmodular** [comment]
Ok, thanks for the update Wael. We may be migrating to 365 later in the year and we'll go the powershell route until then.
