### ISSUE TITLE
Unpack Zip file (Exported Solution)

### ISSUE THREAD

**Issue by Pathikr** [WaelHamze/xrm-ci-framework#60]
Hi Wael,

I want to Unpack the Solution and check in to VSTS. is it possible

Below are the steps for my development 
•Step 1: Define the Solution structure **(Using CRM UI)** (1 time activity)
•Step 2: Create the Solution structure in CRM and TFS/VSO **(Using VSTO)** (1 time activity)
•Step 3: Customize the Solutions (Manual STep)
•Step 4: Export the Solution (Using MSCRM Export Solution)
•Step 5: Unpack the Solution using solutinpackger,exe 
•Step 6: Check in the unpacked Solution in VSTS

is Unpack Solution using your task possible?

**Comment by WaelHamze** [comment]
Did you take a look at the Developer Toolkit Customisations Project. It allow you to unpack your solution into source with one click?

**Comment by WaelHamze** [comment]
You can take a look at this script too: https://github.com/WaelHamze/xrm-ci-framework/blob/master/CRM365/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell.Scripts/ExtractCustomizations.ps1

**Comment by WaelHamze** [comment]
Do you use Git or TFVC by the way?

**Comment by WaelHamze** [comment]
I am currently not planning to build an extract task for the below reasons:
-CRM Solution customisations are considered as part of source
-It is not recommended to check-in source as part of a build. Especially if you have a CI build.
-Ideally the pack should be run by developer upon completion of work with full control over what gets check-in and how conflicts are managed.
