### ISSUE TITLE
Dynamics 365 SP 2.1 Multi-tenant

### ISSUE THREAD

**Issue by petelemay** [WaelHamze/xrm-ci-framework#62]
I'm having an issue when looping through multiple orgs on a single 365 server. I don't have this problem with CRM 2016 SP1 instances. Whichever org I connect to first updates normally. I see the import jobs under system jobs and the results come back as expected. When it starts to update the second org, the async import job ends up under org 1 and once complete, Attempting to get the results goes to org 2 and gives a job does not exist error. I've replicated this on a couple servers.  

I'm defining the connection string: 

$targetCrmConnectionUrl = “Username=$crmuser;Password=password;Domain=domain.com;AuthType=IFD;Url=https://org1.domain.com/org1"
 
and doing an async import

$asyncOperationId = Import-XrmSolution -ConnectionString $targetCrmConnectionUrl -SolutionFilePath $ImportPath -publishWorkflows $true -overwriteUnmanagedCustomizations $true -SkipProductUpdateDependencies $false -ImportAsync $true -WaitForCompletion $true -ImportJobId $importJobId -AsyncWaitTimeout 3600 -ConvertToManaged $true

Then repeating for org2. 

Is there a way to force the connection closed between loops? Defining a new connection doesn't seem to have any effect, the first connection remains open.

**Comment by WaelHamze** [comment]
I believe the connection is opened and closed on each Cmdlet. Are you able to share the full script?

**Comment by petelemay** [comment]
In testing I removed most of the logic in my script and am able to reproduce running this directly in the powershell ise.

Import-Module “c:\Powershell\Modules\Xrm.Framework.CI.PowerShell.Cmdlets\Xrm.Framework.CI.PowerShell.Cmdlets.dll”
$365ifdcrmuser = "user@domain.com"
$targetCrmConnectionUrl = “Username=$365ifdcrmuser;Password=Password;Domain=domain.com;AuthType=IFD;Url=https://org1.domain.com/org1"
$ImportPath = "C:\Octopus\Applications\solution.zip"
write-output $targetCrmConnectionUrl
$importJobId = [guid]::NewGuid()
$asyncOperationId = Import-XrmSolution -ConnectionString $targetCrmConnectionUrl -SolutionFilePath $ImportPath -publishWorkflows $true -overwriteUnmanagedCustomizations $true -SkipProductUpdateDependencies $false -ImportAsync $true -WaitForCompletion $true -ImportJobId $importJobId -AsyncWaitTimeout 3600 -ConvertToManaged $true
Write-Output "Solution Import Completed. Import Job Id: $importJobId"
$importJob = Get-XrmSolutionImportLog -ImportJobId $importJobId -ConnectionString $targetCrmConnectionUrl -OutputFile $importLogFile
$importProgress = $importJob.Progress
$importResult = (Select-Xml -Content $importJob.Data -XPath "//solutionManifest/result/@result").Node.Value
$importErrorText = (Select-Xml -Content $importJob.Data -XPath "//solutionManifest/result/@errortext").Node.Value
Write-Output "Import Progress: $importProgress"
Write-Output "Import Result: $importResult"
Write-Output "Import Error Text: $importErrorText"



$365ifdcrmuser = "user@domain.com"
$targetCrmConnectionUrl = “Username=$365ifdcrmuser;Password=Password;Domain=domain.com;AuthType=IFD;Url=https://org2.domain.com/org2"
$ImportPath = $SrcRoot + "C:\solution.zip"
write-output $targetCrmConnectionUrl
$importJobId = [guid]::NewGuid()
$asyncOperationId = Import-XrmSolution -ConnectionString $targetCrmConnectionUrl -SolutionFilePath $ImportPath -publishWorkflows $true -overwriteUnmanagedCustomizations $true -SkipProductUpdateDependencies $false -ImportAsync $true -WaitForCompletion $true -ImportJobId $importJobId -AsyncWaitTimeout 3600 -ConvertToManaged $true
Write-Output "Solution Import Completed. Import Job Id: $importJobId"
write-output $targetCrmConnectionUrl
$importJob = Get-XrmSolutionImportLog -ImportJobId $importJobId -ConnectionString $targetCrmConnectionUrl -OutputFile $importLogFile
$importProgress = $importJob.Progress
$importResult = (Select-Xml -Content $importJob.Data -XPath "//solutionManifest/result/@result").Node.Value
$importErrorText = (Select-Xml -Content $importJob.Data -XPath "//solutionManifest/result/@errortext").Node.Value
Write-Output "Import Progress: $importProgress"
Write-Output "Import Result: $importResult"
Write-Output "Import Error Text: $importErrorText"

**Comment by WaelHamze** [comment]
I take it if you change the variable names it works fine?

**Comment by petelemay** [comment]
If you set $365ifdcrmuser, $targetCrmConnectionUrl,$ImportPath to actual values, the import will run normally against the first org. When it starts the second org, the async job ends up under org1 and the check for job status goes against org 2 which returns job does not exist. 

I'm testing against two orgs on a single server in IFD. I haven't tested against two orgs on separate servers.

**Comment by petelemay** [comment]
I've tested this against 365 update 2.2 and get the same results. I've attempted iisresets as well as restarting each of the crm services in between orgs and get the same result. I've tried using different variable names to ensure I wasn't getting old results as well as running the the .net garbage collector to cleanup powershell memory space between attempts with no change. 

I've also got the same result with the framework from https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell. My next step will be to open a ticket with MS as it's possibly a CRM issue. 

Has anyone else experienced this or able to replicate what I'm seeing?

**Comment by WaelHamze** [comment]
@petelemay I haven't seen this before and I have been using online for a while now so not able to replicate it. Does the second solution import fine though?

**Comment by petelemay** [comment]
The second solution does import, but it imports to the first org. Thanks for taking a look at it. I'll open a case with MS and post back if I find anything. I can consistently produce this with on premise IFD installations on server 2012 R2 and 2016 fully patched. 

The only way I've found to get it to work as expected is to introduce a 5 minute delay between orgs. Then the second org gets the solution as expected. I've tried 30 seconds but that is not enough. Haven't experimented with a value between there.

**Comment by WaelHamze** [comment]
Thx for the update. Keen to know what is going on here. Let me know once you have an update.

**Comment by WaelHamze** [comment]
I am closing this issue as it seems like a problem in the SDK. Please share feedback once you hear from MS.

**Comment by petelemay** [comment]
For anyone else that may encounter this. Apparently using the already open connection instead of the new one is default behavior. To get around it, add RequireNewInstance=True; to your CRM connection string. This will force the new connection.

**Comment by WaelHamze** [comment]
Perfect. Good to know. Thanks for sharing.
