### ISSUE TITLE
Need Timeout settings on the VSTS tasks

### ISSUE THREAD

**Issue by BinaryMike** [WaelHamze/xrm-ci-framework#64]
I'm using your PS cmdlets, scripts and VSTS build tasks to automate the build and deployment of a very large CRM-based solution.  Everything works great until I get to the Publish Customizations step, which times out.  For our solution, since we have so many custom entities, I need to be able to control the timeout of the Publish Customizations build task, since the default 2 minute timeout isn't sufficient.

I've used the cmdlets to write scripts for developers where we can pass in this timeout to the cmdlet components, and that works great.

For all of the VSTS tasks, can you add a Timeout parameter that we can set in the build definition that then gets passed into the cmdlets?

**Comment by WaelHamze** [comment]
@BinaryMike thanks for the feedback. I have added the timeout to the Publish Customisations Task. Which other Tasks you think this will be useful? Many of them are quick operations or run in Async mode.

**Comment by BinaryMike** [comment]
Awesome!  Thanks for the quick response.  Even when the operation is async, I have seen some of the operations time out.  For example, Import Solution may timeout because my solution ZIP file is over 20 MB, and sometimes it's slow to upload and process before the async operation begins.  Import Solution would definitely be useful.  That's the only other one that I use in the build process for now.

Export Customizations I have a script based on your scripts where I've augmented it with the timeout, since we need it there for developers, but that doesn't require you to update it.  It might be useful for other folks if you included a timeout parameter in the example script.

When will the changes show up in the Visual Studio Marketplace, so my build definition will pick it up?

**Comment by WaelHamze** [comment]
Export already had timeout settings. I added this to the import task as well. Version 8.3.1 Live
