### ISSUE TITLE
Is there any rollback plan in case of Solution Import failure

### ISSUE THREAD

**Issue by rupalibolke** [WaelHamze/xrm-ci-framework#66]
Hi,

We are utilizing this extension for solution import in dynamics 365 and we have come to a point where there were some import failures and we wanted to revert the instance to the previous healthy state.

Is there any rollback plan available in such scenarios?

**Comment by WaelHamze** [comment]
@rupalibolke  normally if the solution imports fail the import operation rolls back. It is a good practice to backup your CRM environment anyway before releases, you can use the tasks provided by this framework to backup/restore CRM Online Environments.
