### ISSUE TITLE
Create instance fails

### ISSUE THREAD

**Issue by andrehe001** [WaelHamze/xrm-ci-framework#68]
with the latest release, when trying to create instance it fails with message: 
2017-12-15T13:35:36.7990583Z OperationId = 00000000-0000-0000-0000-000000000000
2017-12-15T13:35:36.8028992Z Status = Failed
2017-12-15T13:35:37.3705454Z ##[error]Errors encountered : InitialUserPrincipalName cannot be null or empty.

I set the initial user email to the login user but still get the above error.

**Comment by WaelHamze** [comment]
@andrehe001 If you login to the admin portal using the same user I presume you are able to provision a new instance using the UI?

I would also check if all the main fields for that user are populated in office 365 (i.e. firstname etc...)

**Comment by andrehe001** [comment]
It’s working fine via the UI. Can you send me the version where I can switch between 8.x and 9.x? With the actual version I see only version 9.x?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by WaelHamze** [comment]
This is separate API so there is no difference between 8 and 9. Can you share the parameter supplied to the task? Might be worth running the build/release with system.debug = true and see if there is any helpful info in the log too.

**Comment by WaelHamze** [comment]
I just tried to re-run one of my existing builds that was working before and it fails now with the same error. There maybe have been a change on the vendor side but I can't see any new API being released. Has this ever worked for you?

**Comment by WaelHamze** [comment]
@andrehe001 @devkeydet is this working for you? If not I will open a case with MS.

**Comment by andrehe001** [comment]
No, still the same problems with creating an instance. Would be great, if you could open up a case and point to your Add-in

**Comment by WaelHamze** [comment]
Opened the case. Will let you know how it goes.

**Comment by WaelHamze** [comment]
This seems to be working again now.
