### ISSUE TITLE
Connection string format

### ISSUE THREAD

**Issue by tharinstar** [WaelHamze/xrm-ci-framework#69]
Hi,

I keep getting the error: 
Organization cannot be null or empty.
Cannot bind argument to parameter 'CrmConnection' because it is null.

Can someone please let me know how to format the Connection string. 

I am on Dynamics 365 Online.

Cheers
Tharindu

**Comment by GuySimcox** [comment]
Hi This is an example online 365 connection using onmicrosoft user account:

Url=https://XXXXXXX.crm4.dynamics.com; Username=XXXXXX@XXXXXX.onmicrosoft.com; Password=XXXXX; authtype=Office365;

Replace XXXXX's appropriately. Also the Url region etc.

Regards
Guy

**Comment by WaelHamze** [comment]
Take a look at this Url for more information: https://msdn.microsoft.com/en-gb/library/mt608573.aspx
