### ISSUE TITLE
Host Agent VSTFS Online Access Denied

### ISSUE THREAD

**Issue by GuySimcox** [WaelHamze/xrm-ci-framework#70]
Hi Folks, I have an unpacked solution within source control and is part of the deployment artifacts for release. I've configured the MSCRM Solution Package to pack this in a release however I get a Access Denied when the packer attempts to pack to the DeploymentArtifacts folder. I've tried other folders with the same error:

Access to the path 'd:\a\r1\a' is denied.
SolutionPackager: Exception thrown: System.UnauthorizedAccessException

Can anyone help please?
Thanks
Guy

**Comment by GuySimcox** [comment]
Interestingly Copy files to System.DefaultWorkingDirectory works

**Comment by WaelHamze** [comment]
@GuySimcox 

The best practice is to pack the solution in the build definition and publish the solution zip as an artifact.

In your release definition you can then deploy the solution from the artifact.

Artifacts are generated in builds and consumed in releases.
