### ISSUE TITLE
Connection String is not working for Single Sign On CRM

### ISSUE THREAD

**Issue by achatare** [WaelHamze/xrm-ci-framework#77]
Hi Wael,Thanks for XRM-CI framework.We have implemented this in our VSTS...But In setting connection string we are facing problem as Our CRM is Single Sign on...And whenever I am trying to use ... suppose a PING task  without providing password in my connection string ...am getting...Object is set to Null...Can u please help me in this regard

**Comment by WaelHamze** [comment]
If you are connecting to CRM online, did you try to set auto to O365 and username as it appears in CRM user record and windows password?

**Comment by achatare** [comment]
Our connection is like this for dynamic 365 MSD CRM online v9.0
AuthType=OAuth; Url=https://abc.crm4.dynamics.com,Username=****; 
;AppId=GUID;RedirectUri=https://abc.crm4.dynamics.com;TokenCacheStorePath=c:\MyTokenCache;LoginPrompt=Auto;

We are having our Authentication in Microsoft Azure AD....

**Comment by WaelHamze** [comment]
The Framework is based on XRM Tooling described in this link: https://msdn.microsoft.com/en-gb/library/mt608573.aspx

So as long as your connection string conforms to the above it should work.

What is the error you are getting? And where is your hosted agent.

You need to ensure the agent has a line of sight (network) to all the Urls specified and access to the C:\MyTokenCache.

**Comment by achatare** [comment]
Sorry Wael ,not able to provide you full fledged information about the
issue...
