### ISSUE TITLE
Error in MSCRM Package Deployer Step - 'Microsoft.Xrm.Tooling.Connector' is not installed on this computer

### ISSUE THREAD

**Issue by ikurtev** [WaelHamze/xrm-ci-framework#8]
Hello Wael,

I'm getting the following error from a VSTS Build Definition running in the Hosted Controller:
2017-02-09T19:38:28.5815610Z ##[error]The Windows PowerShell snap-in 'Microsoft.Xrm.Tooling.Connector' is not installed on this computer.

I had an account administrator install the Build Tasks from the marketplace and I added the MSCRM Package Deployer task to an existing Release definition. Am I missing something?

I do see that Microsoft.Xrm.Tooling.Connector.dll is included in the framework in the same folder as DeployPackage.ps1 so I am not sure why it is not visible. A Solution Pack step in a build definition that uses the Solution Packager worked for me, so the Solution Packager was available as a resource to the Pack Solution task. Any insight would be appreciated.

**Comment by ikurtev** [comment]
Wael,

I am seeing a difference in DeployPackage.ps1 between the latest version of the script and one that I am using elsewhere that works with VSTS (I have a PowerShell step calling DeployPackage.ps1 directly). I am not sure if I have modified the script or if you have, it has been a while. But to cut to the chase, instead of attempting to import the Tooling modules by name, the script I have is importing them from the DLL's since we can't expect that these modules would be installed on the hosted build server:
![image](https://cloud.githubusercontent.com/assets/16546265/22802800/40e3c87e-eee0-11e6-9f56-5154ea00620f.png)

In addition, this may not be necessary anymore, but I also had to include a lot more DLL's from the SDK\Tools\PackageDeployer\PowerShell folder in the SDK because of dependencies. Here is the full list that I have in case you start getting errors:
![image](https://cloud.githubusercontent.com/assets/16546265/22802899/ac12eb70-eee0-11e6-831c-532a8b839d5f.png)

Hope this helps.

**Comment by WaelHamze** [comment]
Thanks for sharing this is really helpful. I am using the approach described: https://technet.microsoft.com/en-us/library/dn647420.aspx#register which suggests you register these first on the server which off course would not work in the hosted controller. Let me try to alter this based on the above so it can work with the hosted controller too.

**Comment by WaelHamze** [comment]
Hi, I have managed to include all the dependencies in the task in version 8.0.16. However I am getting this error now in the hosted agent. Any thoughts?
2017-02-24T22:45:51.6787358Z ##[warning]Failed to connect to CRM: BadConnect
2017-02-24T22:45:51.6787358Z ##[warning]Failed to connect to CRM: Object reference not set to an instance of an object.DeviceAlreadyExists: 0x80041132

**Comment by ikurtev** [comment]
@WaelHamze - I did run into this error for a short time and I have no recollection of how I resolved it, this was almost 9 months ago. Let me see if I can find anything in old logs and build definitions. Alternatively, it may be helpful to compare our calls to DeployPackage.ps1 with actual parameters to see if something stands out. I'll also get latest on the project and compare with the script I'm using as well and get back to you.

**Comment by ikurtev** [comment]
@WaelHamze - can you try to pass AuthType and the Url of the org, i.e https://orgname.crm.dynamics.com when you connect:
![image](https://cloud.githubusercontent.com/assets/16546265/23326243/e3f55024-fac9-11e6-8d29-6d87a7dbc9ad.png)

This is the only difference I see between the script I am using and the latest version in the repository.  Let me know if this helps.

**Comment by WaelHamze** [comment]
Aha. Changed the task/script to use the connection string instead of the endless number of parameters. Didn't know this was possible as I didn't see it in SDK. This seems to work now with the hosted controller. Version 8.0.17

**Comment by ikurtev** [comment]
@WaelHamze - thank you, it seems to work now. I need a bit of time/insight to set up an environment where I can troubleshoot the tool myself. Any insight would be appreciated. The process now works but I'm seeing a couple of issues: 1) I do not get verbose logging from the step, both from the PowerShell scripts and from the Package Deployer, we need to figure this out because it can be very helpful and 2) I'm getting some errors from post-deployment tasks, but that could be because you are using a newer version of the Package Deployment DLL's that my package is using, I'll look into that. Thanks again!

**Comment by WaelHamze** [comment]
I normally set the "system.debug" = true variable on the environment to get the full logs during a release. Hope this helps.
