### ISSUE TITLE
I get an error 

### ISSUE THREAD

**Issue by aobubo856** [WaelHamze/xrm-ci-framework#81]
Hi Wael,

I need some help please. I get the following error: **Invalid number of components in version** when I try to do a Build in Visual Studio Online following the instructions the build automation instructions. I have setup a build definition. It is failing on the Export solution step but the Publish customisation step seems to have passed using the same connectionString. 

![image](https://user-images.githubusercontent.com/35798134/35380123-43265dde-01b0-11e8-9241-ac8442e5e492.png)

The Target solution version in Dynamics 365 is 8.2 and I used the VS2017 Hosted Agent for the build.

![image](https://user-images.githubusercontent.com/35798134/35381017-d67d87b8-01b2-11e8-82ed-ad8629cc59e1.png)

Any help with this will be much appreciated please. Thanks.

**Comment by WaelHamze** [comment]
I think you have choose to update the version in the export task and your build number is not matching the required format.

Either untick that option of change your build to something like Name_1.0.0.0

**Comment by aobubo856** [comment]
Many thanks for the prompt response Wael. I was able to get past that stage/error but now getting a "An unexpected error occurred" I don't know if this may be down to the publish artefact task which I may need help configuring. Any pointers please?

![image](https://user-images.githubusercontent.com/35798134/35419017-9c66f1c4-022d-11e8-83b8-6977a6434d18.png)
