### ISSUE TITLE
Question: How to Dynamically get the Solution name (and version)

### ISSUE THREAD

**Issue by demianrasko** [WaelHamze/xrm-ci-framework#84]
Hi, I'm creating a new build, where I export the solution as zip file, and Publish Artifact in a folder.
This Build triggers a release, where I whant to use this artifact. It works fine if I use the name of the solution zip file, but this file will change because it contains the version of the solution like "Dynamics365WorkflowTools_1_0_48_1.zip", "Dynamics365WorkflowTools_1_0_48_2.zip", "Dynamics365WorkflowTools_1_0_48_3.zip"...

Can you tell me how can use this dynamically? there is any way to get the Artifact file dynamically generated by the build?

Thanks!!

**Comment by demianrasko** [comment]
I just saw how to do it...forget it. I'm just starting with th CI....
Thanks and great job Wael!!!

**Comment by sanjay1913** [comment]
Hi, could you share connection string with parameters for export solution ,?

**Comment by WaelHamze** [comment]
I normally don't include the version in the file name to make things easier. If you really wanted to do that. If you could generate the solution name using the build artifact version or place file with solution names as part of the artifacts.
