### ISSUE TITLE
An unexpected error occurred: MSCRM Export Solution task

### ISSUE THREAD

**Issue by aobubo856** [WaelHamze/xrm-ci-framework#85]
Sorry I'm new to CI in Visual studio online (I have managed to get a database project configured with build definition and released to an on premise server using a hosted agent). I am currently struggling to get the MSCRM Export Solution build task working in my build definition partly. I created a folder path in my Parent directory expecting the exported solution to be sent there but the export is failing (even though the publish using the same connectionstring passes). I am also using a hosted agent as well as the on premise agent cannot authenticate to CRM online. I'm not sure if this is because of the Output Path selected. I also tried using $(build.binariesdirectory) and $(Build.StagingDirectory) for my output directory values with no success. I just get "An Unexpected error occured".

![image](https://user-images.githubusercontent.com/35798134/35561425-2c4c0f4a-05a8-11e8-988a-c1ba95cff05c.png)

Here is the task I configured. It may be obvious what I am getting wrong here but please help and thanks in advance.

![image](https://user-images.githubusercontent.com/35798134/35561218-81b66e36-05a7-11e8-8aed-56d1e5f77eff.png)

**Comment by aobubo856** [comment]
I also tried using $(build.binariesdirectory) and $(Build.StagingDirectory) for my output directory values with no success.

**Comment by WaelHamze** [comment]
Hi, can you set system.debug to true and run again. Let me know if see anything useful in the logs.

**Comment by aobubo856** [comment]
Hi, The logs produced the following: 

![image](https://user-images.githubusercontent.com/35798134/35674391-75d844a4-073c-11e8-9c45-c78b692003cf.png)

Exporting Unmanaged Solution
Current Security Protocol: Ssl3, Tls
Modified Security Protocol: Ssl3, Tls, Tls11, Tls12
Connecting to CRM [attempt 1]
Exporting Solution: SolutionName201880117
Caught exception from task script.
Error record:
Export-XrmSolution : An unexpected error occurred.
At D:\a\_tasks\MSCRMExportSolution_015e2e58-9c77-4cbc-a9c1-a28158165365\9.0.3\Lib\xRMCIFramework\9.0.0\ExportSolution.ps1:83 char:28
+ ... nagedFile = Export-XrmSolution -ConnectionString "$CrmConnectionStrin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Export-XrmSolution], FaultException`1
+ FullyQualifiedErrorId : System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Micros oft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Xrm.Framework.CI.PowerShell.Cmdle ts.ExportXrmSolutionCommand
Script stack trace:
at <ScriptBlock>, D:\a\_tasks\MSCRMExportSolution_015e2e58-9c77-4cbc-a9c1-a28158165365\9.0.3\Lib\xRMCIFramework\9.0.0\ExportSolution.ps1: line 83
at <ScriptBlock>, D:\a\_tasks\MSCRMExportSolution_015e2e58-9c77-4cbc-a9c1-a28158165365\9.0.3\MSCRMExportSolution.ps1: line 73
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 22
at <ScriptBlock>, <No file>: line 18
at <ScriptBlock>, <No file>: line 1
Exception:
System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: An unexpected error occurred. (Fault Detail is equal to Exception details:
ErrorCode: 0x80040216
Message: An unexpected error occurred.
TimeStamp: 2018-02-01T10:24:23.6664301Z
--
Exception details:
ErrorCode: 0x80040216
Message: System.NullReferenceException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #BBAFD24F
TimeStamp: 2018-02-01T10:24:23.6664301Z
--
).
An unexpected error occurred.
Processed: ##vso[task.logissue type=error]An unexpected error occurred.
Processed: ##vso[task.complete result=Failed]

**Comment by bo-stig-christensen** [comment]
As @WaelHamze is suggesting, please try the UI export as the first thing and see if you get a more detailed error message.

If the above does not give you anything, I can see that you are on CRM 365 Online and would recommend that you contact Microsoft Support and give them the Administrator Reference Number that CRM throws.
If you were On-Premise, you could enter the server trace logs yourself and find the exact issue, but with CRM Online, you are dependent on Microsoft Administrators for that :-(

Please also try checking if the export actually is taking more than 2 minutes.

@WaelHamze: I am actually experiencing similar issues, but I am directly getting a timeout issue. The funny part is that it is happening from our DevOps (via this CI framework), but not via the UI (there it simply just takes forever, but it exports.
Are you having a hard 2-minute timeout somewhere in code? Like a cancellation token of something? - Or should I hit Microsoft Support regarding this you think? - It could be the same issue as faced in this issue.

**Comment by bo-stig-christensen** [comment]
@WaelHamze I actually wrote a couple of integration tests and I was able to reproduce the issue on CRM Online using a simple ExportSolutionRequest execution. - Our CRM Online instance for a customer is just timing out after 2 minutes 3 out of 4 times. - Microsoft Support ticket created.

**Comment by aobubo856** [comment]
Thank you very much @WaelHamze and @bo-stig-christensen. I got the export to work by removing the target version. Manually exporting the solution from the UI works without any issues/error messages as well.

**Comment by aobubo856** [comment]
@bo-stig-christensen Did you try increasing the connection timeout parameter? The default is 120 
![image](https://user-images.githubusercontent.com/35798134/35851046-ae9934e8-0b1e-11e8-9838-2f509b697afd.png)
