### ISSUE TITLE
How to restore backup database from Azure

### ISSUE THREAD

**Issue by demianrasko** [WaelHamze/xrm-ci-framework#86]
Hi Wael, 
I made a backup with your tools in Azure Blob storage.  I have there all the files,  and I downloaded to a local server.  When I tried to restore the backup on my local sql server,  I cannot do it because I don't have the certified of the sql encryption. 
I opened a case support with Microsoft to request it,  but they don't understand what I need...  Do you know if there is any other way to do it? 

Thanks!!

**Comment by WaelHamze** [comment]
Hi Damian,

Not sure whether this backup was designed in mind to be able to restore to on-premises. I know you can use the API to restore a backup made using the API to CRM online.

Did you try setting your own encryption on the instance and then checking whether you can restore backup using same keys? https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/manage-encryption-keys-instance

**Comment by demianrasko** [comment]
Thanks Wael, I'll see what can I get with this and with my case support!
