### ISSUE TITLE
Using xRMCIFramework_7.1.0.0 - Getting Select-WhoAmI : Metadata contains a reference that cannot be resolved

### ISSUE THREAD

**Issue by sanjay1913** [WaelHamze/xrm-ci-framework#87]
Dear Experts,
I am using xRMCIFramework_7.1.0.0 to call Dynamics 2016 through VSTS , Getting following error,
xRMCIFramework_7.1.0.0\PowerShell\Xrm.Framework.CI.PowerShell.dll
Imported CIToolkit
Select-WhoAmI : Metadata contains a reference that cannot be resolved:
Process completed with exit code 1 and had 1 error(s) written to the error stream.**

parameter for exportSolution.ps1
------------------------------------------------
-CrmConnectionString  "ServiceUri=https://myurl.com:5555/myorg;Domain=MyDomain;Username=SKS;Password=$(MSDPass);Timeout=1:0:0" -SolutionName "GenericInstanceEntities.zip"

**Comment by WaelHamze** [comment]
Seems like an issue with connectivity or connection string. Below is the format for 7.1. https://msdn.microsoft.com/pt-pt/library/gg695810(v=crm.7).aspx

Also does your solution name have .zip in the end?

**Comment by sanjay1913** [comment]
Dear Wael,

Thank you for the response. I am able to do the connection with name .

But have issue with package deploy.


Import-CrmPackage –CrmConnection $CRMConn –PackageDirectory $PackageDirectory –PackageName $PackageName -Verbose

**Comment by sanjay1913** [comment]
I am trying to use DeployPackager.ps1 and trying to get the connection object to 

execute 


Import-CrmPackage –CrmConnection $CRMConn –PackageDirectory $PackageDirectory –PackageName $PackageName -Verbose


Case 1 Connection : Through VSTS facing error
-----------------------

#Create Credentials
$SecPassword = ConvertTo-SecureString $Password -AsPlainText -Force
$Cred = New-Object System.Management.Automation.PSCredential ($Username, $SecPassword)


$CRMConn = Get-CrmConnection –ServerUrl 'https://myDyndmics.com:5555/MyOrg' -Credential $Cred -OrganizationName 'MyOrg' -Verbose


-----------------------
Erorr :



PackageDirectory: C:\Agent\_work\18
CommandType     Name                                               Version    Source                                   
-----------     ----                                               -------    ------                                   
Cmdlet          Get-CrmConnection                                  1.0.0.0    Microsoft.Xrm.Tooling.CrmConnector.Pow...
Cmdlet          Get-CrmOrganizations                               1.0.0.0    Microsoft.Xrm.Tooling.CrmConnector.Pow...
WARNING: Failed to connect to CRM: BadConnect
WARNING: Failed to connect to CRM: Metadata contains a reference that cannot be resolved: 
'https://myDyndmics.com:5555/XRMServices/2011/Discovery.svc?wsdl&sdkversion=7.1'. => The underlying 
connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. => The remote certificate
 is invalid according to the validation procedure.
Get-CrmConnection : Failed to connect to CRM: Metadata contains a reference that cannot be resolved:
Process completed with exit code 1 and had 1 error(s) written to the error stream.


--------------------------------------

Case 2 connection - Works fine 
-------------
$CRMConn = Get-CrmConnection –ServerUrl 'https://myDyndmics.com:5555' -Credential $Cred -OrganizationName 'MyOrg -Verbose

Write-Verbose "Cnnections : $CRMConn" 
Write-Output $CRMConn.ConnectedOrgVersion.ToString()

**Comment by WaelHamze** [comment]
Can you try connection string in this format for the package deployer? https://msdn.microsoft.com/en-gb/library/mt608573.aspx

Also ensure all the required DLLs for the specific version of the package deployer you are using are in the same directory.

**Comment by sanjay1913** [comment]
Dear Wael,

Thank you for your response . Certificate was missing , After Importing certificate issue connection issue resolved.,

Thank you in advance !

But I am facing issue while import , I am using DeployPackage.ps1 

Where commands are in  DeployPackage.ps1 
Import-CrmPackage –CrmConnection $CRMConn –PackageDirectory $PackageDirectory –PackageName $PackageName -Verbose

Error Details :
Invoke-Expression : The term 'Import-CrmPackage' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try

**Comment by WaelHamze** [comment]
Take a look at this script: https://github.com/WaelHamze/xrm-ci-framework/blob/master/MSDYNV9/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell.Scripts/DeployPackage.ps1

There is a step in there Import-Module that loads the required components.

Here is a reference to documentation too: https://technet.microsoft.com/en-us/library/dn647420.aspx

**Comment by sanjay1913** [comment]
Dear Wael,

I want my Dynamics.CRMpackge have Dynmics.Plugin.dll and Dynsmics.Workflow.dll and RegisterFile.crmregister file , Want to deploy in CRM using Powershell cmdlet in XRMFramewrok 7.0. I am using CRM 2016 version .

It is not a solution .zip file ,  [Actual it is package I want to deploy Dynamics.CRMpackge . Can you please share the powershell ? with parameter?

![deploy](https://user-images.githubusercontent.com/3985285/36515604-81044fbe-177a-11e8-82f4-4a1ea6517922.png)

**Comment by sanjay1913** [comment]
Hi Wael,

Used to call package ps but  getting below error: Not sure where failing

DeployPackage.ps1'

param(
[string]$AuthenticationType,
[string]$Username,
[string]$Password,
[string]$ServerUrl,
[string]$OrganizationName,
[string]$DeploymentRegion,
[string]$OnlineType,
[string]$HomRealmURL,
[string]$PackageName,
[string]$PackageDirectory
)


input parameter 
-AuthenticationType "AD" -Username "DOM\T"-Password $(MSDPass) -ServerUrl "ABC.com" -OrganizationName "CICD" -DeploymentRegion "" -OnlineType "AD" -HomRealmURL ""Active Directory" -PackageName '$(build.binariesdirectory)\DynamicsCrm.Package.dll'  -PackageDirectory '$(build.binariesdirectory)'

After parse :

 -AuthenticationType "AD" -Username "********"-Password ******** -ServerUrl "ABC.com" -OrganizationName "CICD" -DeploymentRegion "" -OnlineType "AD" -HomRealmURL ""Active Directory" -PackageName 'DynamicsCrm.Package.dll'  -PackageDirectory 'C:\Agent\_work\18\b'

Error :
... ve Directory" -PackageName 'C:\Agent\_work\18\b\Dynamic ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The string is missing the terminator: ".
At line:1 char:237
+ ... Clear() } ; Invoke-Expression -Command ([System.Text.Encoding]::UTF8. ...

**Comment by sanjay1913** [comment]
Got resolved removed " from  ""Active Directory" 
------------------------------

Now I am facing below , My script directory does not have below DLL, Not sure from where I can found, Not available in SDK 2016

Microsoft.Xrm.Tooling.PackageDeployment.dll' was not loaded because no valid module file was found in 
any module directory.

**Comment by WaelHamze** [comment]
You can download these libraries from Nuget. Note the Package Deployment from Xrm Tooling is different from the package that comes with the Developer Toolkit. I don't currently have a script that can automate the developer toolkit deployment. I believe you can achieve this using MSBuild

**Comment by sanjay1913** [comment]
Hi Wael,

Thank you for your response .

I was trying to automate Deployment Tool Kit.

Do you mean to say that Deploy can be acheive by following :+1:

**Comment by sanjay1913** [comment]
Hi Wael,

Project is able to build sucecssfully but if I include Deploy in option then getting below error
Am I missing any thing here ?

c:\Agent\_work\17\s\DynamicsCrm.Package\DynamicsCrm.Package.csproj : error MSB4057: The target "Deploy" does not exist in the project.
Done Building Project "c:\Agent\_work\17\s\DynamicsCrm.Package\DynamicsCrm.Package.csproj" (Clean;Build;Deploy target(s)) -- FAILED.

**Comment by WaelHamze** [comment]
@sanjay1913 I have not tried to do this actually. Did you manage to get it working?

**Comment by sanjay1913** [comment]
Dear Wael,

No , I am also trying .

**Comment by sanjay1913** [comment]
c
