### ISSUE TITLE
Export Solution

### ISSUE THREAD

**Issue by capuanodanilo** [WaelHamze/xrm-ci-framework#92]
Hi,
is possible when I using the Task Export Solution set into **Output Path** field my TFS branch path? 
Example: **$/DevOps (365)/Solutions** 
In this case i want collect all exported solution with version under folder in my project TFS.
Regards,

**Comment by WaelHamze** [comment]
@capuanodanilo the task doesn't support this as most users will be publishing the solution files as artifacts into TFS or another package management service. This would be my recommendation, source is designed to store source where as solution zip is equivalent to binaries. If you still want to do it then you will need to use the version control command line tools to publish the solution into your version control system.
