### ISSUE TITLE
SolutionPackager - Unpack solution build task

### ISSUE THREAD

**Issue by bo-stig-christensen** [WaelHamze/xrm-ci-framework#95]
There is a SolutionPackager Package Task available in the build tasks.
It would be great to have a SolutionPackager Unpack Task as well.

This would be used for extracting unmanaged solutions from a specific development environment, unpack it, and then check it into source control for change management and backup purposes.

**Comment by WaelHamze** [comment]
@bo-stig-christensen would you not rather has this done by a member of the team when certain requirement is completed or milestone is reached? This way you can see conflicts (if any) and have control over the operation.

**Comment by bo-stig-christensen** [comment]
@WaelHamze Actually, I would like to automate this as much as possible.
I have build, unit testing, deployments and integration tests close to fully automated in VSTS, so basically a complete CD pipeline. During this process, I want to ensure that I catch any customization changes done, so I back up the extracted solution to a separate "CRM Backup" repo for each project. - This ensures that I always have a quite accurate customization history for the solution.

I am aware that the most interesting backups are the "milestones" or "feature completed" checkpoints, which I am thinking that I can tag in git or similar.

I have a vision of developing a solution for CRM to hook into messages related to customizations such as PublishAll and similar to kind of have Change Logging backed by Git, but that's the next step in evolution for a later point in time ;-)

I guess that the implementation of this task would be basically a copy of the SolutionPackager Pack task, but with Unpack parameters :-)

**Comment by WaelHamze** [comment]
@bo-stig-christensen I can add a task for the unpack. I am presuming that you can handle the source control actions outside of this task? (otherwise this task will get complex and will take to take into account different types of version control and deltas)

**Comment by bo-stig-christensen** [comment]
@WaelHamze I already have the complete Git handling set up in a custom Task Group :-)
So yes, the only missing link is an easy way of unpacking the solution for the proper structure on commit.

**Comment by WaelHamze** [comment]
Excellent, are you able to share the Git handling code/setup on here?

**Comment by WaelHamze** [comment]
@bo-stig-christensen Also do you expect the export to happen independently using the existing tasks and then the unpack task would just run the solution packager?

**Comment by WaelHamze** [comment]
@bo-stig-christensen this task is almost ready just confirm the above so I can release

**Comment by WaelHamze** [comment]
Released to Marketplace 9.0.24. Let me know if any issues.
