### ISSUE TITLE
Connection to CRM is cached in onpremise using AD authentication

### ISSUE THREAD

**Issue by gceganesh** [WaelHamze/xrm-ci-framework#96]
1. Connect to a crm organization
2. Run the who am I command
3. Note down the org, BU, userid etc
4. Use a different connectionstring
5. Run the who am I command
6. It still shows the first org details

Both orgs are onpremise and hosted on the same server.

**Comment by iNSidemen** [comment]
Hi Ganesh,

the previously opened connection is reused, I guess to improve performance.

Just add „RequireNewInstance=true“ to your connection string and the world suddenly is a better place (phun intended).

See here for further details: https://msdn.microsoft.com/en-us/library/mt608573.aspx#Parameters

Best,
Norbert

**Comment by gceganesh** [comment]
Got it figured already.... Got a bit confused that crm still maintains the
connection even after you call the ServiceClient.Dispose
